# Generated by Django 5.2.5 on 2025-09-01 05:43

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def purge_self_referential(apps, schema_editor):
    Bom = apps.get_model('products', 'BillOfMaterial')
    # Delete any legacy rows where parent == component to allow constraint add
    Bom.objects.filter(parent_id=F('component_id')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='alternate_group',
            field=models.CharField(blank=True, default='', help_text='Group key for alternates', max_length=40),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='change_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Component unit cost snapshot at creation', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='dt_last_recalc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='is_alternate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='op_data',
            field=models.JSONField(blank=True, default=dict, help_text='Lightweight routing/tooling notes JSON'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='revision',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='yield_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional explicit yield (0-1). If provided, may override scrap calc', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='scrap_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Scrap ratio (0-1); applied as qty*(1+scrap)', max_digits=6),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['component'], name='bom_component_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['parent', 'revision', 'sequence'], name='bom_parent_rev_seq_idx'),
        ),
        migrations.RunPython(purge_self_referential, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('component')), _negated=True), name='ck_bom_parent_ne_component'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(check=models.Q(('scrap_factor__gte', 0), ('scrap_factor__lt', 1)), name='ck_bom_scrap_range'),
        ),
    ]
