# Generated by Django 5.2.5 on 2025-09-04 06:07

import apps.products.models.inventory_layer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogline',
            name='items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='inventorystack',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='inventorystack',
            name='cost',
            field=models.JSONField(blank=True, default=apps.products.models.inventory_layer.default_cost),
        ),
        migrations.AlterField(
            model_name='inventorystack',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
    ]
