# Generated by Django 5.2.8 on 2026-02-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='recalc_parent_cost_description',
            field=models.CharField(blank=True, db_column='recalc_parent_cost_description', help_text='Description for this parent item (denormalized from Item.description for convenience)', max_length=255),
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='recalc_parent_cost_description',
            new_name='parent_description',
        ),
    ]
