# Generated by Django 5.2.8 on 2025-12-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryreservation',
            name='invres_state_exp_idx',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='effective_from',
            new_name='dt_effective_from',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='effective_to',
            new_name='dt_effective_to',
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='committed_at',
            new_name='dt_committed',
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='expires_at',
            new_name='dt_expires',
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='released_at',
            new_name='dt_released',
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['state', 'dt_expires'], name='invres_state_exp_idx'),
        ),
    ]
