# Generated by Django 5.2.5 on 2025-09-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventory_cost_schema_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystack',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='PendingInventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('request_ref', models.JSONField(blank=True, default=dict)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('applied_dt', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=120)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_adjustments', to='products.inventorystack')),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='pendinv_state_idx'), models.Index(fields=['stack', 'state'], name='pendinv_stack_state_idx')],
            },
        ),
    ]
