# Generated by Django 5.2.8 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_recalc_parent_cost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='itemxref',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='serial',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='siteinventory',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
    ]
