# Generated by Django 5.2.1 on 2025-09-02 03:29

import apps.products.models.item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_billofmaterial_alternate_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.JSONField(blank=True, default=apps.products.models.item.cost_default_factory, help_text='Cost information dict; see default_cost() schema'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.JSONField(blank=True, default=apps.products.models.item.price_default_factory, help_text='Pricing information dict; see default_price() schema'),
        ),
    ]
