# Generated by Django 5.2.8 on 2025-12-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_billofmaterial_uniq_bom_parent_component_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemxref',
            name='uniq_item_source_sku',
        ),
        migrations.RemoveConstraint(
            model_name='siteinventory',
            name='uniq_item_site',
        ),
        migrations.AddConstraint(
            model_name='itemxref',
            constraint=models.UniqueConstraint(fields=('item_id', 'source', 'external_sku'), name='uniq_item_source_sku'),
        ),
        migrations.AddConstraint(
            model_name='siteinventory',
            constraint=models.UniqueConstraint(fields=('item_id', 'site_code'), name='uniq_item_site'),
        ),
    ]
