# Generated by Django 5.2.5 on 2025-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_billofmaterial_uuid_alter_catalog_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventorystack',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='item',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='itemxref',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='serial',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='siteinventory',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
