# Generated by Django 5.2.8 on 2025-12-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_itemusage_uniq_item_year_month_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemusage',
            name='uniq_item_year_month',
        ),
    ]
