# Generated by Django 5.2.5 on 2025-09-04 06:33

import apps.products.models.inventory_reservation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_inventory_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='context',
            field=models.JSONField(blank=True, default=apps.products.models.inventory_reservation.default_context),
        ),
    ]
