# Generated by Django 5.2.5 on 2025-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_inventoryreservation_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metrics', models.JSONField()),
            ],
            options={
                'ordering': ('-created_dt',),
                'indexes': [models.Index(fields=['created_dt'], name='invmet_snapshot_created_idx')],
            },
        ),
    ]
