# Generated by Django 5.2.8 on 2026-07-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_vendor_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryline',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='deliveryvisit',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='inventorycheck',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='inventorycheckline',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='orgitem',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='seriallog',
            old_name='data',
            new_name='config',
        ),
        migrations.AlterField(
            model_name='pendinginventoryadjustment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
