# Generated by Django 5.2.8 on 2026-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_data_to_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='annual_turns',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Units issued / avg on-hand, annualized', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(sale_price - cost_avg) / cost_avg × 100', max_digits=8),
        ),
        migrations.AddField(
            model_name='item',
            name='margin_velocity',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='(margin% × turns/year) — higher = better use of capital. Alice computes nightly.', max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='velocity_category',
            field=models.CharField(blank=True, db_index=True, default='', help_text='dead_capital | volume_driver | star | normal', max_length=20),
        ),
    ]
