# Generated by Django 5.2.5 on 2025-09-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_inventorymetricssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentProcessorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('global', 'Global'), ('stack', 'Stack')], db_index=True, max_length=12)),
                ('stack_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('started_dt', models.DateTimeField()),
                ('finished_dt', models.DateTimeField()),
                ('duration_s', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attempted', models.IntegerField(default=0)),
                ('applied', models.IntegerField(default=0)),
                ('skipped_locked', models.IntegerField(default=0)),
                ('still_locked', models.IntegerField(default=0)),
                ('insufficient', models.IntegerField(default=0)),
                ('canceled', models.IntegerField(default=0)),
                ('reserved_conflict_skipped', models.IntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_dt',),
                'indexes': [models.Index(fields=['run_type', 'created_dt'], name='invproc_run_type_created_idx')],
            },
        ),
    ]
