# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_billofmaterial_is_locked_catalog_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='catalogline',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='deliveryvisit',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorycheck',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorycheckline',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='itemxref',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='orgitem',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='siteinventory',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_locked',
        ),
    ]
