# Generated by Django 5.2.1 on 2025-09-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_serial_number_to_serial_ida'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serial',
            new_name='itemlinked_item_idx',
            old_name='serial_item_idx',
        ),
    ]
