# Generated by Django 5.2.8 on 2026-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_margin_velocity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='applies_to',
            field=models.JSONField(blank=True, default=dict, help_text="Targeting scope: {contacts: [id], contact_types: ['wholesale'], categories: [], all: false}"),
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_universal_pct',
            field=models.BooleanField(default=False, help_text='True = blanket % applied to all items; False = per-line rules in CatalogLine'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='margin_floor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimum margin % allowed — below triggers approval Action', max_digits=6),
        ),
        migrations.AddField(
            model_name='catalog',
            name='priority',
            field=models.IntegerField(db_index=True, default=0, help_text='Higher priority wins when multiple catalogs match. 0=default.'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='universal_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Universal discount % (used only when is_universal_pct=True)', max_digits=6),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('percent_off', 'Percent Off'), ('fixed_price', 'Fixed Price'), ('amount_off', 'Amount Off'), ('price_level', 'Price Level')], default='percent_off', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='adjustment_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Value depends on type: 15.0 = 15% off, or $15 fixed, or price level code', max_digits=14),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='max_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum qty for this price break (null = unlimited)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='min_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum qty for this price break (null = any)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text='What this line covers: {items: [id], categories: [], vendors: [], all_items: false}'),
        ),
    ]
