# Generated by Django 5.2.8 on 2026-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_billofmaterial_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryadjustmentprocessorrun',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='inventorymetricssnapshot',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveIndex(
            model_name='inventoryadjustmentprocessorrun',
            name='invproc_run_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymetricssnapshot',
            name='invmet_snapshot_created_idx',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='catalogline',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='deliveryvisit',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentprocessorrun',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='inventorycheck',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='inventorycheckline',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='inventorylayer',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='inventorymetricssnapshot',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='inventoryreservation',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='itemxref',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='orgitem',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='pendinginventoryadjustment',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='siteinventory',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='dt_modified',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ida',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this BOM line', max_length=255),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this BOM line', max_length=120),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this inventory check line', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this inventory check line', max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this reservation', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this reservation', max_length=120),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this usage record', max_length=255),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this usage record', max_length=120),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this org item', max_length=120),
        ),
        migrations.AddField(
            model_name='serial',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this serial', max_length=255),
        ),
        migrations.AddField(
            model_name='serial',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this serial', max_length=120),
        ),
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this variant', max_length=255),
        ),
        migrations.AddField(
            model_name='variant',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this variant', max_length=120),
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='description',
            field=models.CharField(blank=True, help_text='Description for this org item', max_length=255),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentprocessorrun',
            index=models.Index(fields=['run_type'], name='invproc_run_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymetricssnapshot',
            index=models.Index(fields=['id'], name='invmet_snapshot_id_idx'),
        ),
    ]
