# Generated by Django 5.2.8 on 2026-02-07 18:51

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_inventoryadjustmentprocessorrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='dt_created',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='dt_created',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='variant',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='variant',
            name='dt_created',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='variant',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='variant',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='variant',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='variant',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentprocessorrun',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorymetricssnapshot',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
