# Generated by Django 5.2.8 on 2026-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_billofmaterial_config_catalog_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginventoryadjustment',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
