# Generated by Django 5.2.8 on 2026-02-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_inherit_basemodel_for_variant_metrics_processor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billofmaterial',
            name='uniq_bom_parent_component',
        ),
        migrations.RemoveConstraint(
            model_name='billofmaterial',
            name='ck_bom_parent_ne_component',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_component_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_parent_rev_seq_idx',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='item_id',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='item_ida',
            new_name='parent_ida',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='description',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='child_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='bom_child', to='products.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='parent_name',
            field=models.CharField(blank=True, help_text='Description for this parent item (denormalized from Item.name for convenience)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['parent_id'], name='bom_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['child_id'], name='bom_component_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['parent_id', 'revision', 'sequence'], name='bom_parent_rev_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('parent_id', 'child_id'), name='uniq_bom_parent_component'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('parent_id', models.F('child_id')), _negated=True), name='ck_bom_parent_ne_component'),
        ),
    ]
