# Generated by Django 5.2.8 on 2026-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_billofmaterial_uniq_bom_parent_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='child_description',
            field=models.CharField(blank=True, help_text='Description for this child item (denormalized from Item.description for convenience)', max_length=255),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='child_ida',
            field=models.CharField(blank=True, db_index=True, help_text='String identifier for this BOM child item (denormalized from Item.ida for convenience)', max_length=120),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='recalc_parent_cost_description',
            field=models.CharField(blank=True, help_text='Description for this parent item (denormalized from Item.description for convenience)', max_length=255),
        ),
    ]
