# Generated by Django 5.2.8 on 2026-02-15 20:29

import apps.products.models.specification
import common.models
import common.stats_mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_rename_contact_id_orgbase_contact'),
        ('products', '0011_remove_billofmaterial_parent_name_and_more'),
        ('sync', '0007_alter_bundle_connection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('stats', models.JSONField(blank=True, default=common.stats_mixin.default_stats)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Optional lifecycle / state label', max_length=30)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_long', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='Optional canonical unit when numeric', max_length=30)),
                ('details', models.JSONField(blank=True, default=apps.products.models.specification.default_details, help_text='Structured value payload (kind, value, unit, etc.)')),
                ('docs', models.JSONField(blank=True, default=apps.products.models.specification.default_docs)),
                ('applies_to', models.JSONField(blank=True, default=apps.products.models.specification.default_applies)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='billofmaterial',
            name='uniq_bom_parent_component',
        ),
        migrations.RemoveConstraint(
            model_name='billofmaterial',
            name='ck_bom_parent_ne_component',
        ),
        migrations.RemoveConstraint(
            model_name='catalog',
            name='uniq_catalog_code_vendor',
        ),
        migrations.RemoveConstraint(
            model_name='catalogline',
            name='uniq_catalog_item',
        ),
        migrations.RemoveConstraint(
            model_name='deliveryline',
            name='uniq_delivery_visit_orgitem',
        ),
        migrations.RemoveConstraint(
            model_name='inventorycheckline',
            name='uniq_invchk_orgitem',
        ),
        migrations.RemoveConstraint(
            model_name='siteinventory',
            name='uniq_item_site',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_component_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofmaterial',
            name='bom_parent_rev_seq_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_vendor_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_customer_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_manufacturer_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_rep_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_employee_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalog',
            name='catalog_connection_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryvisit',
            name='delv_vendor_sched_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryvisit',
            name='delv_customer_sched_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorycheck',
            name='invchk_org_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorycheck',
            name='invchk_cat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorylayer',
            name='inv_item_wh_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='invmove_item_wh_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendinginventoryadjustment',
            name='pendinv_stack_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='serial',
            name='itemlinked_item_idx',
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='child_id',
            field=models.ForeignKey(db_column='child_id', on_delete=django.db.models.deletion.PROTECT, related_name='bom_child', to='products.item'),
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='child_id',
            new_name='child_item',
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='parent_id',
            field=models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='products.item'),
        ),
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='parent_id',
            new_name='parent_item',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='connection_id',
            field=models.ForeignKey(blank=True, db_column='connection_id', help_text='Sync connection managing external catalog integration (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='sync.connection'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='connection_id',
            new_name='connection',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='customer_orgbase_id',
            field=models.ForeignKey(blank=True, db_column='customer_orgbase_id', help_text='Target customer organization scope (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_catalogs', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='customer_orgbase_id',
            new_name='customer_orgbase',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='employee_orgbase_id',
            field=models.ForeignKey(blank=True, db_column='employee_orgbase_id', help_text='Internal employee / corporate organizational context (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_catalogs', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='employee_orgbase_id',
            new_name='employee_orgbase',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='manufacturer_orgbase_id',
            field=models.ForeignKey(blank=True, db_column='manufacturer_orgbase_id', help_text='Manufacturer associated with this catalog (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_catalogs', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='manufacturer_orgbase_id',
            new_name='manufacturer_orgbase',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='orgbase_id',
            field=models.ForeignKey(blank=True, db_column='orgbase_id', help_text='Owning / publishing vendor organization (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_catalogs', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='orgbase_id',
            new_name='orgbase',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='rep_orgbase_id',
            field=models.ForeignKey(blank=True, db_column='rep_orgbase_id', help_text='Representative / agent organization (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_catalogs', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='rep_orgbase_id',
            new_name='rep_orgbase',
        ),
        migrations.AlterField(
            model_name='catalogline',
            name='catalog_id',
            field=models.ForeignKey(db_column='catalog_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.catalog'),
        ),
        migrations.RenameField(
            model_name='catalogline',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='catalogline',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='catalogline',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='deliveryvisit_id',
            field=models.ForeignKey(db_column='deliveryvisit_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.deliveryvisit'),
        ),
        migrations.RenameField(
            model_name='deliveryline',
            old_name='deliveryvisit_id',
            new_name='delivery_visit',
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='orgitem_id',
            field=models.ForeignKey(db_column='orgitem_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='products.orgitem'),
        ),
        migrations.RenameField(
            model_name='deliveryline',
            old_name='orgitem_id',
            new_name='orgitem',
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='catalog_id',
            field=models.ForeignKey(blank=True, db_column='catalog_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_visits', to='products.catalog'),
        ),
        migrations.RenameField(
            model_name='deliveryvisit',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='customer_orgbase_id',
            field=models.ForeignKey(db_column='customer_orgbase_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_visits_as_customer', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='deliveryvisit',
            old_name='customer_orgbase_id',
            new_name='customer_orgbase',
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='orgbase_id',
            field=models.ForeignKey(db_column='orgbase_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_visits_as_vendor', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='deliveryvisit',
            old_name='orgbase_id',
            new_name='orgbase',
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='catalog_id',
            field=models.ForeignKey(blank=True, db_column='catalog_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_checks', to='products.catalog'),
        ),
        migrations.RenameField(
            model_name='inventorycheck',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='orgbase_id',
            field=models.ForeignKey(db_column='orgbase_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checks', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='inventorycheck',
            old_name='orgbase_id',
            new_name='orgbase',
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='inventorycheck',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='inventorycheckline',
            name='inventorycheck_id',
            field=models.ForeignKey(db_column='inventorycheck_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.inventorycheck'),
        ),
        migrations.RenameField(
            model_name='inventorycheckline',
            old_name='inventorycheck_id',
            new_name='inventory_check',
        ),
        migrations.AlterField(
            model_name='inventorycheckline',
            name='orgitem_id',
            field=models.ForeignKey(db_column='orgitem_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_check_lines', to='products.orgitem'),
        ),
        migrations.RenameField(
            model_name='inventorycheckline',
            old_name='orgitem_id',
            new_name='orgitem',
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='inventorylayer',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='warehouse_id',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_layers', to='products.warehouse'),
        ),
        migrations.RenameField(
            model_name='inventorylayer',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='inventorylayer_id',
            field=models.ForeignKey(blank=True, db_column='inventorylayer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.inventorylayer'),
        ),
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='inventorylayer_id',
            new_name='inventory_layer',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='warehouse_id',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.warehouse'),
        ),
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='inventorylayer_id',
            field=models.ForeignKey(blank=True, db_column='inventorylayer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='products.inventorylayer'),
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='inventorylayer_id',
            new_name='inventory_layer',
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.item'),
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='warehouse_id',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.warehouse'),
        ),
        migrations.RenameField(
            model_name='inventoryreservation',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='itemusage',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='itemxref',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='itemxref',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='catalog_id',
            field=models.ForeignKey(blank=True, db_column='catalog_id', help_text='Optional catalog / channel context scoping this association', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_items', to='products.catalog'),
        ),
        migrations.RenameField(
            model_name='orgitem',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='orgitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='orgbase_id',
            field=models.ForeignKey(db_column='orgbase_id', on_delete=django.db.models.deletion.CASCADE, related_name='org_items', to='orgs.orgbase'),
        ),
        migrations.RenameField(
            model_name='orgitem',
            old_name='orgbase_id',
            new_name='orgbase',
        ),
        migrations.AlterField(
            model_name='pendinginventoryadjustment',
            name='inventorylayer_id',
            field=models.ForeignKey(db_column='inventorylayer_id', on_delete=django.db.models.deletion.CASCADE, related_name='pending_adjustments', to='products.inventorylayer'),
        ),
        migrations.RenameField(
            model_name='pendinginventoryadjustment',
            old_name='inventorylayer_id',
            new_name='inventory_layer',
        ),
        migrations.AlterField(
            model_name='serial',
            name='inventorylayer_id',
            field=models.ForeignKey(blank=True, db_column='inventorylayer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='products.inventorylayer'),
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='inventorylayer_id',
            new_name='inventory_layer',
        ),
        migrations.AlterField(
            model_name='serial',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='serial_id',
            field=models.ForeignKey(db_column='serial_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.serial'),
        ),
        migrations.RenameField(
            model_name='seriallog',
            old_name='serial_id',
            new_name='serial',
        ),
        migrations.AlterField(
            model_name='service',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='service',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.RenameField(
            model_name='siteinventory',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['parent_item'], name='bom_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['child_item'], name='bom_component_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['parent_item', 'revision', 'sequence'], name='bom_parent_rev_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['orgbase'], name='catalog_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['customer_orgbase'], name='catalog_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['manufacturer_orgbase'], name='catalog_manufacturer_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['rep_orgbase'], name='catalog_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['employee_orgbase'], name='catalog_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['connection'], name='catalog_connection_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryvisit',
            index=models.Index(fields=['orgbase', 'dt_scheduled'], name='delv_vendor_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryvisit',
            index=models.Index(fields=['customer_orgbase', 'dt_scheduled'], name='delv_customer_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['orgbase', 'dt_performed'], name='invchk_org_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['catalog', 'dt_performed'], name='invchk_cat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['item', 'warehouse'], name='inv_item_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', 'warehouse'], name='invmove_item_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginventoryadjustment',
            index=models.Index(fields=['inventory_layer', 'state'], name='pendinv_stack_state_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['item'], name='itemlinked_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('parent_item', 'child_item'), name='uniq_bom_parent_component'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('parent_item', models.F('child_item')), _negated=True), name='ck_bom_parent_ne_component'),
        ),
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('code', 'orgbase'), name='uniq_catalog_code_vendor'),
        ),
        migrations.AddConstraint(
            model_name='catalogline',
            constraint=models.UniqueConstraint(fields=('catalog', 'item'), name='uniq_catalog_item'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.UniqueConstraint(fields=('delivery_visit', 'orgitem'), name='uniq_delivery_visit_orgitem'),
        ),
        migrations.AddConstraint(
            model_name='inventorycheckline',
            constraint=models.UniqueConstraint(fields=('inventory_check', 'orgitem'), name='uniq_invchk_orgitem'),
        ),
        migrations.AddConstraint(
            model_name='siteinventory',
            constraint=models.UniqueConstraint(fields=('item', 'site_code'), name='uniq_item_site'),
        ),
        migrations.AddField(
            model_name='specification',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['item', 'name'], name='spec_item_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('item', 'name'), name='uniq_item_spec_name'),
        ),
    ]
