# Generated by Django 5.2.8 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_serial_config_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemxref',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendinginventoryadjustment',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteinventory',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
    ]
