# Generated by Django 5.2.1 on 2025-06-11 13:15

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_type', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('full', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('opt_out', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('opt_out', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
    ]
