# filepath: /Users/williamjames/Documents/CommerceExpert/webClerk3/communications/migrations/0001_initial.py
# Generated by Django 5.2.1 on 2025-08-02 03:47

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_type', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('full', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('country_code', models.CharField(blank=True, help_text='Country code (e.g., +1)', max_length=5)),
                ('format', models.CharField(blank=True, help_text='Formatted phone number', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Display name for this phone', max_length=100)),
                ('attention', models.CharField(blank=True, help_text='Person or department attention line', max_length=100)),
                ('opt_out', models.BooleanField(default=False, help_text='Opted out of communications')),
                ('comment', models.TextField(blank=True, help_text='Additional notes about this phone', null=True)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Display name for this email', max_length=100)),
                ('attention', models.CharField(blank=True, help_text='Person or department attention line', max_length=100)),
                ('opt_out', models.CharField(blank=True, choices=[('', 'Active'), ('opted_out', 'Opted Out'), ('bounced', 'Bounced'), ('invalid', 'Invalid'), ('spam_complaint', 'Spam Complaint')], default='', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Additional notes about this email', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary email address')),
                ('is_verified', models.BooleanField(default=False, help_text='Email has been verified')),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
                'db_table': 'emails',
                'indexes': [models.Index(fields=['email'], name='emails_email_b814fb_idx'), models.Index(fields=['is_primary'], name='emails_is_prim_2479c4_idx'), models.Index(fields=['opt_out'], name='emails_opt_out_e796bc_idx')],
            },
        ),
    ]
