# filepath: /Users/williamjames/Documents/CommerceExpert/webClerk3/communications/migrations/0002_email_type.py
# Generated by Django 5.2.1 on 2025-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.CharField(blank=True, help_text='Type of email (e.g., work, personal)', max_length=50),
        ),
    ]
