# Generated by Django 5.2.1 on 2025-07-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='address',
            new_name='email',
        ),
    ]
