# Generated by Django 5.2.1 on 2025-08-17 01:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_domain_metadata_alter_domain_prefs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='email',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='email',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='email',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='location',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='location',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='location',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
    ]
