# Generated by Django 5.2.1 on 2025-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_rename_address_to_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email Address', 'verbose_name_plural': 'Email Addresses'},
        ),
        migrations.AddField(
            model_name='email',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary email address'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email address has been verified'),
        ),
        migrations.AddField(
            model_name='email',
            name='last_bounced',
            field=models.DateTimeField(blank=True, help_text='Last bounce date', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='attention',
            field=models.CharField(blank=True, help_text='Person or department attention line', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional notes about this email', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, help_text='Display name for this email', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='opt_out',
            field=models.CharField(blank=True, choices=[('', 'Active'), ('opted_out', 'Opted Out'), ('bounced', 'Bounced'), ('invalid', 'Invalid'), ('spam_complaint', 'Spam Complaint')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email'], name='emails_email_b814fb_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_primary'], name='emails_is_prim_2479c4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['opt_out'], name='emails_opt_out_e796bc_idx'),
        ),
    ]
