# Generated by Django 5.2.5 on 2025-08-24 03:03

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_domain_ida_email_ida_location_ida_phone_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='email',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='location',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='phone',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
    ]
