# Generated by Django 5.2.1 on 2025-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_address_uuid_domain_uuid_email_uuid_phone_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
