# Generated by Django 5.2.1 on 2025-07-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_email_options_email_is_primary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='last_bounced',
            new_name='dt_bounced',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='verified_at',
            new_name='dt_verified',
        ),
    ]
