# Generated by Django 5.2.1 on 2025-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_rename_datetime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dt_verified',
            field=models.DateTimeField(blank=True, help_text='When address was verified', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='dt_verified',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='dt_verified',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
    ]
