# Generated by Django 5.2.1 on 2025-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_address_dt_verified_domain_dt_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
