# Generated by Django 5.2.1 on 2025-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pres',
            field=models.JSONField(blank=True, default=dict, help_text='Various user defined preferences for the data'),
        ),
        migrations.AddField(
            model_name='domain',
            name='pres',
            field=models.JSONField(blank=True, default=dict, help_text='Various user defined preferences for the data'),
        ),
        migrations.AddField(
            model_name='email',
            name='pres',
            field=models.JSONField(blank=True, default=dict, help_text='Various user defined preferences for the data'),
        ),
        migrations.AddField(
            model_name='phone',
            name='pres',
            field=models.JSONField(blank=True, default=dict, help_text='Various user defined preferences for the data'),
        ),
        migrations.AlterField(
            model_name='address',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Health, profiles, undefined and other user defined data'),
        ),
        migrations.AlterField(
            model_name='address',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Keywords, tags, and related references'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Health, profiles, undefined and other user defined data'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Keywords, tags, and related references'),
        ),
        migrations.AlterField(
            model_name='email',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Health, profiles, undefined and other user defined data'),
        ),
        migrations.AlterField(
            model_name='email',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Keywords, tags, and related references'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Health, profiles, undefined and other user defined data'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Keywords, tags, and related references'),
        ),
    ]
