# Generated by Django 5.2.1 on 2025-08-01 04:34

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_address_pres_domain_pres_email_pres_phone_pres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pres',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='pres',
        ),
        migrations.RemoveField(
            model_name='email',
            name='pres',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='pres',
        ),
        migrations.AlterField(
            model_name='address',
            name='metadata',
            field=models.JSONField(blank=True, default=common.models.default_metadata, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='refs',
            field=models.JSONField(blank=True, default=common.models.default_refs, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='metadata',
            field=models.JSONField(blank=True, default=common.models.default_metadata, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='refs',
            field=models.JSONField(blank=True, default=common.models.default_refs, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='metadata',
            field=models.JSONField(blank=True, default=common.models.default_metadata, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='refs',
            field=models.JSONField(blank=True, default=common.models.default_refs, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='metadata',
            field=models.JSONField(blank=True, default=common.models.default_metadata, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='refs',
            field=models.JSONField(blank=True, default=common.models.default_refs, null=True),
        ),
    ]
