# Generated by Django 5.2.1 on 2025-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_remove_address_pres_remove_domain_pres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone Number', 'verbose_name_plural': 'Phone Numbers'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='dt_verified',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='dt_verified',
        ),
        migrations.RemoveField(
            model_name='email',
            name='dt_bounced',
        ),
        migrations.RemoveField(
            model_name='email',
            name='dt_verified',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='dt_verified',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='type',
        ),
        migrations.AlterField(
            model_name='email',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email has been verified'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='attention',
            field=models.CharField(blank=True, help_text='Person or department attention line', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional notes about this phone', null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code (e.g., +1)', max_length=5),
        ),
        migrations.AlterField(
            model_name='phone',
            name='format',
            field=models.CharField(blank=True, help_text='Formatted phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, help_text='Display name for this phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='opt_out',
            field=models.BooleanField(default=False, help_text='Opted out of communications'),
        ),
    ]
