/**
 * TaxReportPrintDocument — sales tax summary by jurisdiction.
 *
 * For quarterly/monthly filing. Shows:
 * - Company header with logo
 * - Period covered
 * - Tax collected by jurisdiction (state/county/city)
 * - Invoice count per jurisdiction
 * - Total tax collected
 * - Reconciliation checkbox
 */
import React from 'react';
import { formatCurrency } from './printTypes';
import { formatDt } from '@/utils/fieldFormatters';

export interface TaxReportLine {
  jurisdiction: string;
  jurisdiction_name: string;
  tax_collected: number;
  invoice_count: number;
}

export interface TaxReportData {
  period_label: string;      // "Q2 2026 (Apr-Jun)" or "June 2026"
  period_start: string;
  period_end: string;
  company: {
    name: string;
    address: string;
    city_state_zip: string;
    phone: string;
    tax_id: string;
    logo_url?: string;
  };
  lines: TaxReportLine[];
  total_tax: number;
  total_invoices: number;
}

const fmt = (n: number) => formatCurrency(n);

export default function TaxReportPrintDocument({ data }: { data: TaxReportData }) {
  const { company, lines, period_label, total_tax, total_invoices } = data;

  return (
    <div data-wc="tax-report-print-document" className="print-page">

      {/* Header */}
      <div className="print-header">
        <div>
          {company.logo_url && <img src={company.logo_url} alt="" className="print-logo" />}
          <div className="print-company-name">{company.name}</div>
          <div>{company.address}</div>
          <div>{company.city_state_zip}</div>
          <div>{company.phone}</div>
          {company.tax_id && <div>EIN: {company.tax_id}</div>}
        </div>
        <div className="print-right">
          <div className="print-text-title">Sales Tax Report</div>
          <div className="print-text-2xl print-text-subtle">{period_label}</div>
          <div className="print-text-sm print-text-dim">{data.period_start} to {data.period_end}</div>
        </div>
      </div>

      {/* Tax by Jurisdiction */}
      <table className="print-table-lg">
        <thead>
          <tr className="print-thead-row">
            <th className="print-th">Jurisdiction</th>
            <th className="print-th-r">Invoices</th>
            <th className="print-th-r">Tax Collected</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((line, i) => (
            <tr key={i} className="print-row">
              <td className="print-td">{line.jurisdiction_name || line.jurisdiction}</td>
              <td className="print-td-r">{line.invoice_count}</td>
              <td className="print-td-mono">{fmt(line.tax_collected)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="print-tfoot-row">
            <td className="print-td">Total</td>
            <td className="print-td-r">{total_invoices}</td>
            <td className="print-td-mono">{fmt(total_tax)}</td>
          </tr>
        </tfoot>
      </table>

      {/* Certification */}
      <div className="print-box-padded print-mb-3xl">
        <div className="print-semibold print-mb-md">Certification</div>
        <div className="print-text-sm print-mb-lg">
          I certify that this report accurately reflects the sales tax collected
          during the period {data.period_start} to {data.period_end} based on
          transaction records maintained by {company.name}.
        </div>
        <div className="print-flex print-gap-lg">
          <div>
            <div className="print-sig-line print-sig-line-md">&nbsp;</div>
            <div className="print-text-xs print-text-dim">Signature</div>
          </div>
          <div>
            <div className="print-sig-line print-sig-line-sm">&nbsp;</div>
            <div className="print-text-xs print-text-dim">Date</div>
          </div>
          <div>
            <div className="print-sig-line print-sig-line-md">&nbsp;</div>
            <div className="print-text-xs print-text-dim">Printed Name / Title</div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="print-footer">
        Generated by {company.name} · {formatDt(new Date(), 'date')}
      </div>
    </div>
  );
}
