# Generated by Django 5.2.8 on 2026-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
    ]
