# Generated by Django 5.2.5 on 2025-09-07 01:48

import common.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('exchange', models.JSONField(blank=True, default=dict, null=True)),
                ('currency_base', models.CharField(default='USD', max_length=10)),
                ('currency_target', models.CharField(default='USD', max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=20)),
                ('precision_convert', models.IntegerField(default=2)),
                ('precision_display', models.IntegerField(default=2)),
                ('connection_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acct_exchanges',
                'indexes': [models.Index(fields=['currency_base', 'currency_target', 'is_active'], name='acct_exch_cur_base_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency_base', 'currency_target', 'dt_start', 'dt_end'), name='uniq_acct_exchange_window')],
            },
        ),
    ]
