# Generated by Django 5.2.5 on 2025-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_currency_uuid_alter_exchangerate_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='term',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
