# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_currency_is_locked_exchangerate_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='exchangetransaction',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_locked',
        ),
    ]
