# Generated by Django 5.2.8 on 2026-03-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_is_locked_to_lifecycle'),
        ('orgs', '0004_add_is_locked_to_lifecycle'),
        ('transactions', '0006_add_is_locked_to_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org_id', help_text='Org (customer/vendor) for fast aging queries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orgs.orgbase'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='discount_potential',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Discount rate, e.g. 0.02 for 2%', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='value_available',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current unpaid balance (mutable by payments)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='value_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial amount when created (immutable)', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['org', 'model_name'], name='idx_ledger_org_model'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['org', 'dt_due'], name='idx_ledger_org_due'),
        ),
    ]
