# Generated by Django 5.2.8 on 2026-02-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_currency_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='dt_begin',
            field=models.DateField(blank=True, help_text='Fixed start date for schedule calculation (overrides invoice date)', null=True),
        ),
    ]
