# Generated by Django 5.2.8 on 2026-02-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_dt_begin_to_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Who approved this term for use', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='day_cut_off_due',
            field=models.IntegerField(blank=True, help_text='Due date cutoff day for statement cycles', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='day_cut_off_invoice',
            field=models.IntegerField(blank=True, help_text='Invoice cutoff day for statement cycles', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='days_discount',
            field=models.IntegerField(blank=True, help_text='Days within which discount applies', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='days_due',
            field=models.IntegerField(blank=True, help_text='Days until payment due (from invoice or dt_begin)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='days_in_period',
            field=models.IntegerField(blank=True, help_text='Days between installments (multi-period only)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.CharField(blank=True, help_text="Human-readable description (e.g., 'Net 30 Days')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='discount_rate',
            field=models.FloatField(blank=True, help_text='Early payment discount percentage (e.g., 2.0 for 2%)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='dt_begin',
            field=models.DateField(blank=True, help_text='Fixed start date for schedule (overrides invoice date)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, help_text="Term code (e.g., 'N30', '2%', 'COD')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='period_count',
            field=models.IntegerField(blank=True, help_text='Number of payment installments (1=single payment)', null=True),
        ),
    ]
