# Generated by Django 5.2.8 on 2026-03-08 13:08

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_org_fk_and_decimal_fields_to_ledger'),
        ('orgs', '0004_add_is_locked_to_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Erosion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('category', models.CharField(choices=[('margin', 'Margin Erosion'), ('discount', 'Discount Given'), ('fx_loss', 'Currency / FX Loss'), ('late_payment', 'Late Payment Carrying Cost'), ('return_credit', 'Return / Credit'), ('rework', 'Rework / Warranty'), ('shipping', 'Shipping / Freight'), ('bad_debt', 'Bad Debt Write-Off'), ('price_override', 'Price Override'), ('other', 'Other')], db_index=True, help_text='Type of value erosion', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Dollar value of erosion (always positive)', max_digits=12)),
                ('amount_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage erosion (e.g., 0.11 = 11 margin points lost)', max_digits=8, null=True)),
                ('source_model', models.CharField(choices=[('proposal', 'Proposal'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('credit_memo', 'Credit Memo')], help_text='Transaction type where erosion was detected', max_length=50)),
                ('source_id', models.BigIntegerField(db_index=True, help_text='PK of the source transaction')),
                ('compare_model', models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('credit_memo', 'Credit Memo')], help_text='Transaction type being compared (e.g., proposal for margin erosion on invoice)', max_length=50, null=True)),
                ('compare_id', models.BigIntegerField(blank=True, help_text='PK of the comparison transaction', null=True)),
                ('dt_event', models.DateTimeField(blank=True, help_text='When the erosion event occurred', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-text explanation of the erosion event')),
                ('is_auto', models.BooleanField(default=False, help_text='True if auto-calculated during save pipeline, False if manual')),
                ('contact', models.ForeignKey(blank=True, help_text='Rep or salesperson responsible (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erosion_events', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, help_text='Customer or vendor associated with this erosion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erosion_events', to='orgs.orgbase')),
            ],
            options={
                'db_table': 'erosion',
                'indexes': [models.Index(fields=['org', 'category'], name='idx_erosion_org_cat'), models.Index(fields=['org', 'dt_event'], name='idx_erosion_org_date'), models.Index(fields=['source_model', 'source_id'], name='idx_erosion_source')],
            },
        ),
    ]
