# Generated by Django 5.2.8 on 2026-02-09 05:17

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_gl_account_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('account_number', models.CharField(blank=True, db_index=True, help_text="GL account number (e.g., '10100-000-000')", max_length=50, null=True)),
                ('name', models.CharField(blank=True, help_text="Account name (e.g., 'Cash', 'Accounts Receivable')", max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('', 'Unspecified'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('contra', 'Contra')], help_text='Account type (asset, liability, equity, revenue, expense)', max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('cash', 'Cash'), ('receivables', 'Accounts Receivable'), ('payables', 'Accounts Payable'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('other', 'Other')], help_text='Account category for grouping', max_length=255, null=True)),
                ('type_id', models.CharField(blank=True, help_text='Product type/category ID for sales/COGS accounts', max_length=255, null=True)),
                ('account_credit', models.CharField(blank=True, help_text='Default credit account for journal entries', max_length=255, null=True)),
                ('account_debit', models.CharField(blank=True, help_text='Default debit account for journal entries', max_length=255, null=True)),
                ('used_for', models.CharField(blank=True, choices=[('posting', 'Posting'), ('reporting', 'Reporting'), ('tax', 'Tax'), ('consolidation', 'Consolidation'), ('other', 'Other')], help_text='Account usage classification', max_length=255, null=True)),
                ('division', models.IntegerField(blank=True, help_text='Division/department code', null=True)),
                ('comment', models.TextField(blank=True, help_text='Notes or description', null=True)),
            ],
            options={
                'db_table': 'gl_accounts',
            },
        ),
    ]
