# Generated by Django 5.2.8 on 2026-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_gl_journal_source_traceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gljournal',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Groups journal lines into a single posting batch (e.g., SJ-2026-06)', max_length=80),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='date_posted',
            field=models.DateField(blank=True, help_text='Accounting date for this entry (may differ from dt_created)', null=True),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='division',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Department/division code for GL segmentation', max_length=50),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='is_posted',
            field=models.BooleanField(db_index=True, default=False, help_text='True after exported to accounting package'),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='gljournal',
            index=models.Index(fields=['batch_id', 'account'], name='glj_batch_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='gljournal',
            index=models.Index(fields=['division', 'date_posted'], name='glj_div_date_idx'),
        ),
    ]
