# Generated by Django 5.2.8 on 2026-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_update_gl_idas_and_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='currency',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='erosion',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='term',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
