# Generated by Django 5.2.8 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_dt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='audit',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='currency',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='currency',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='erosion',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='erosion',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='term',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='term',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
    ]
