# Generated by Django 5.2.8 on 2026-08-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='ExchangeTransaction',
        ),
    ]
