# Generated by Django 5.2.8 on 2026-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_dt_journaled_consolidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='is_settled',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='dt_applied',
            field=models.DateTimeField(blank=True, help_text='When payment was applied (settled). Record remains editable. Non-null = settled.', null=True),
        ),
    ]
