#!/bin/bash
# WebClerk installer — sets up backend and frontend from a fresh clone
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR/frontend"

echo "========================================"
echo "  WebClerk Installer"
echo "========================================"
echo ""

# ── Check prerequisites ──────────────────────────────────────────

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is required but not installed."
    echo "  Install with: $2"
    exit 1
  fi
}

check_cmd python3 "brew install python@3.13"
check_cmd node "brew install node"
check_cmd npm "brew install node"
check_cmd psql "brew install postgresql@16 && brew services start postgresql@16"
check_cmd redis-cli "brew install redis && brew services start redis"

echo "All prerequisites found."
echo ""

# ── Backend setup ─────────────────────────────────────────────────

echo "── Backend ──"

cd "$BACKEND_DIR"

if [ ! -d "venv" ]; then
  echo "Creating Python virtual environment..."
  python3 -m venv venv
fi

echo "Installing Python dependencies..."
venv/bin/pip install --upgrade pip -q
venv/bin/pip install -r requirements.txt -q
echo "  $(venv/bin/pip list --format=columns 2>/dev/null | wc -l | tr -d ' ') packages installed"

# Create .env from template if it doesn't exist
if [ ! -f ".env" ]; then
  echo "Creating backend .env..."
  CURRENT_USER=$(whoami)
  cat > .env << ENVEOF
# WebClerk Backend Environment
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

DEBUG=True

DATA_SET_ID=DEV
DATA_SET_NAME=Development Server

# Database — local PostgreSQL
DB_MODE=local
LOCAL_DATABASE_HOST=localhost
LOCAL_DATABASE_PORT=5432
LOCAL_DATABASE_NAME=commerce_expert
LOCAL_DATABASE_USER=$CURRENT_USER
LOCAL_DATABASE_PASS=

# Email (configure for your provider)
EMAIL_HOST=
EMAIL_PORT=587
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=

# Optional services
SENTRY_DSN=
ENVEOF
  echo "  Created .env (edit to customize)"
else
  echo "  .env already exists — skipping"
fi

# Create database if it doesn't exist
if psql -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw commerce_expert; then
  echo "  Database 'commerce_expert' already exists"
else
  echo "Creating database 'commerce_expert'..."
  createdb commerce_expert 2>/dev/null || echo "  WARNING: Could not create database. Create it manually: createdb commerce_expert"
fi

# Run migrations
echo "Running migrations..."
venv/bin/python manage.py migrate --no-input 2>&1 | tail -1

# Create logs directory
mkdir -p logs

echo "Backend setup complete."
echo ""

# ── Frontend setup ────────────────────────────────────────────────

echo "── Frontend ──"

cd "$FRONTEND_DIR"

echo "Installing Node dependencies..."
npm install --silent 2>&1 | tail -3

# Create .env from template if it doesn't exist
if [ ! -f ".env" ]; then
  echo "Creating frontend .env..."
  cat > .env << ENVEOF
# WebClerk Frontend Environment
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

VITE_ENV='DEV'
VITE_URL="http://localhost:5173"
VITE_DEBUG_BADGES='true'

VITE_DATA_SET_ID='DEV'
VITE_DATA_SET_NAME='Development Server'

VITE_API_URL="http://localhost:8000"
VITE_AUTH_API_URL="http://localhost:8000"
VITE_API_URL_PROD=""
ENVEOF
  echo "  Created .env (edit to customize)"
else
  echo "  .env already exists — skipping"
fi

echo "Frontend setup complete."
echo ""

# ── Done ──────────────────────────────────────────────────────────

echo "========================================"
echo "  WebClerk installed successfully"
echo "========================================"
echo ""
echo "  Start:    ./start.sh"
echo "  Backend:  http://localhost:8000"
echo "  Frontend: http://localhost:5173"
echo ""
echo "  Create an admin user:"
echo "    cd backend && venv/bin/python manage.py createsuperuser"
echo ""
