[pytest]
DJANGO_SETTINGS_MODULE = webclerk3_api.settings
django_find_project = false
pythonpath = .
testpaths = apps tests
python_files = test_*.py

norecursedirs =
    .git
    .*
    build
    dist
    node_modules
    lib
    include
    bin
    share

addopts =
    -ra
    --maxfail=1
    --disable-warnings
    --ignore=lib
    --ignore=include
    --ignore=bin
    --ignore=share
    --ignore-glob=lib/python*/site-packages/*


# Optional: quiet known noisy warnings instead of --disable-warnings
# filterwarnings =
#     ignore::DeprecationWarning
#     ignore::UserWarning
