# Generated by Django 5.2.1 on 2025-05-22 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('verification_code', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_alert', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('name_first', models.CharField(blank=True, max_length=50)),
                ('name_last', models.CharField(blank=True, max_length=50)),
                ('name_middle', models.CharField(blank=True, max_length=50, null=True)),
                ('opt_out', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('publish', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Administrator'), ('SALE', 'Sales'), ('REP', 'Representative'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('USER', 'User'), ('PUBLIC', 'Public')], max_length=50), blank=True, default=list, size=None)),
                ('comment', models.TextField(blank=True, null=True)),
                ('refs', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_contact',
            },
        ),
    ]
