# Generated by Django 5.2.1 on 2025-08-02 03:19

import common.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('action_by', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_action', models.DateTimeField(blank=True, null=True)),
                ('dt_completed', models.DateTimeField(blank=True, null=True)),
                ('dt_due', models.DateTimeField(blank=True, null=True)),
                ('dt_updated', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Primary email address for login', max_length=254, unique=True)),
                ('name_first', models.CharField(blank=True, help_text='First name', max_length=100)),
                ('name_last', models.CharField(blank=True, help_text='Last name', max_length=100)),
                ('name_middle', models.CharField(blank=True, help_text='Middle name', max_length=100)),
                ('name_prefix', models.CharField(blank=True, help_text='Title (Mr., Ms., Dr.)', max_length=20)),
                ('name_suffix', models.CharField(blank=True, help_text='Suffix (Jr., Sr., III)', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest')], default='user', help_text='User role in system', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='User account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='User can access admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation date')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Universal API metadata: history, workflows, references')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['name_last', 'name_first'],
            },
        ),
    ]
