# Generated by Django 5.2.1 on 2025-05-29 16:17

import common.models
import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('action_by', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=255, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_due', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('refs', models.JSONField(blank=True, default=common.models.default_refs, null=True)),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, null=True)),
                ('metadata', models.JSONField(blank=True, default=common.models.default_metadata, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('opt_out', models.JSONField(default=None, null=True)),
                ('password', models.CharField(max_length=128)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Administrator'), ('SALE', 'Sales'), ('REP', 'Representative'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('USER', 'User'), ('PUBLIC', 'Public')], max_length=50), blank=True, default=list, size=None)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_alert', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('name_first', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('name_middle', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('publish', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
