# Generated by Django 5.2.5 on 2025-08-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='uuid',
        ),
        migrations.AddField(
            model_name='action',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='setting',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='template',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AlterField(
            model_name='pending',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
