# Generated by Django 5.2.1 on 2025-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role_default',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
