# Generated by Django 5.2.1 on 2025-08-08 01:25

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('ida', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caches',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments'),
        ),
    ]
