# Generated by Django 5.2.1 on 2025-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
