# Generated by Django 5.2.1 on 2025-08-16 20:38

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cache_contact_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='health_rating',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='references',
        ),
        migrations.AddField(
            model_name='pending',
            name='data',
            field=models.JSONField(default=common.models.default_data),
        ),
        migrations.AddField(
            model_name='pending',
            name='dt_processed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pending',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata),
        ),
        migrations.AlterField(
            model_name='pending',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs),
        ),
        migrations.AlterField(
            model_name='pending',
            name='refs',
            field=models.JSONField(default=common.models.default_refs),
        ),
        migrations.AlterModelTable(
            name='pending',
            table='pending',
        ),
    ]
