# Generated by Django 5.2.1 on 2025-07-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dt_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='dt_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='dt_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='dt_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
