# Generated by Django 5.2.1 on 2025-08-17 01:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_action_metadata_alter_action_prefs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='action',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='action',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='template',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='template',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='template',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
    ]
