# Generated by Django 5.2.8 on 2026-09-03 14:28

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_squashed_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliceobservation',
            name='category',
            field=models.CharField(choices=[('pattern', 'Workflow Pattern'), ('anomaly', 'Data Anomaly'), ('coaching', 'Coaching Suggestion'), ('alert', 'Alert'), ('search', 'Search Pattern'), ('layout', 'Layout Suggestion'), ('performance', 'Performance Issue'), ('schema', 'Pydantic Schema Question'), ('console', 'Console Capture'), ('escalation', 'Escalation to Claude'), ('pii_correction', 'PII Correction'), ('bill_question', 'Question for Bill')], db_index=True, default='pattern', max_length=30),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('episode_id', models.CharField(db_index=True, help_text='Natural key: EP-{hash}. Used for dedup across instances.', max_length=20, unique=True)),
                ('episode_type', models.CharField(choices=[('tfts', 'Try-Fail-Try-Succeed'), ('fault', 'System Fault'), ('scar', 'Scar (cost something)'), ('commerce', 'Commerce Event'), ('session', 'Session Summary'), ('pattern', 'Detected Pattern')], db_index=True, max_length=30)),
                ('domain', models.CharField(choices=[('SU', 'SketchUp'), ('PH', 'Physical'), ('RT', 'Route-Time'), ('WC3', 'WebClerk'), ('SYS', 'System'), ('ALLIE', 'Allie'), ('CROSS', 'Cross-domain')], db_index=True, default='CROSS', max_length=20)),
                ('severity', models.CharField(choices=[('lesson', 'Lesson'), ('scar', 'Scar'), ('win', 'Win')], db_index=True, default='lesson', max_length=20)),
                ('outcome', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('ongoing', 'Ongoing')], db_index=True, default='unresolved', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('narrative', models.TextField(blank=True, help_text='Full story: problem, what was tried, result, what was revealed.')),
                ('principle', models.TextField(blank=True, help_text='The lesson learned — the rule that made the final attempt obvious.')),
                ('actors', models.JSONField(blank=True, default=list, help_text='Who was involved (scrubbed before upstream push).')),
                ('related_episodes', models.JSONField(blank=True, default=list, help_text='episode_id list of related episodes.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags.')),
                ('source_ref', models.CharField(blank=True, help_text='Origin reference: tfts:filename, retro:id, sync:connection_ida.', max_length=200)),
                ('recall_count', models.IntegerField(default=0, help_text='Times recalled via similarity search.')),
                ('dt_last_recalled', models.BigIntegerField(default=0, help_text='Last recall timestamp (epoch ms).')),
                ('dt_start', models.BigIntegerField(default=0, help_text='When the episode began (epoch ms).')),
                ('dt_end', models.BigIntegerField(default=0, help_text='When the episode ended (epoch ms).')),
                ('source_instance', models.UUIDField(blank=True, db_index=True, help_text='UUID of the WC3 instance that created this episode.', null=True)),
                ('review_status', models.CharField(choices=[('raw', 'Raw — not yet reviewed'), ('pending', 'Pending review'), ('approved', 'Approved for feed'), ('rejected', 'Rejected (foolish or harmful)'), ('archived', 'Archived (superseded or stale)')], db_index=True, default='raw', help_text='Athena + Allie review gate. Only approved episodes enter the feed.', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, help_text='Who reviewed: athena, allie, or admin username.', max_length=50)),
                ('dt_reviewed', models.BigIntegerField(default=0, help_text='When the review happened (epoch ms).')),
                ('review_note', models.TextField(blank=True, help_text='Reviewer comment — why rejected, what was improved, etc.')),
                ('quality_score', models.FloatField(default=0.0, help_text='Quality rating: -1.0 (harmful) to 1.0 (excellent). Set by reviewer.')),
            ],
            options={
                'db_table': 'ai_episode',
                'ordering': ['-dt_created'],
                'indexes': [models.Index(fields=['episode_type', 'domain'], name='ep_type_domain_idx'), models.Index(fields=['severity', 'outcome'], name='ep_severity_outcome_idx'), models.Index(fields=['-dt_created'], name='ep_dt_created_idx'), models.Index(fields=['-recall_count'], name='ep_recall_count_idx'), models.Index(fields=['review_status'], name='ep_review_status_idx'), models.Index(fields=['source_instance'], name='ep_source_instance_idx')],
            },
        ),
    ]
