# Generated by Django 5.2.8 on 2026-08-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alicecoachinglog',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aliceinsight',
            name='contact',
            field=models.ForeignKey(help_text='The user Alice is learning about', on_delete=django.db.models.deletion.CASCADE, related_name='alice_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alice_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['started_at', 'session_type'], name='coding_sess_started_4bf455_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsession',
            index=models.Index(fields=['session_type'], name='coding_sess_session_13d0ab_idx'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gitevent',
            index=models.Index(fields=['committed_at', 'author_email'], name='git_event_committ_62bfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='gitevent',
            index=models.Index(fields=['commit_type'], name='git_event_commit__96d5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['created_at', 'category'], name='ai_inventor_created_b2edb8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['item_id', 'created_at'], name='ai_inventor_item_id_8c03d1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['transaction_id', 'transaction_type'], name='ai_inventor_transac_bcb487_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation'),
        ),
        migrations.AddField(
            model_name='schemadrift',
            name='git_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drift_records', to='ai_assistant.gitevent'),
        ),
        migrations.AddIndex(
            model_name='alicecoachinglog',
            index=models.Index(fields=['contact', 'completed'], name='alicecoach_contact_done_idx'),
        ),
        migrations.AddIndex(
            model_name='alicecoachinglog',
            index=models.Index(fields=['category'], name='alicecoach_category_idx'),
        ),
        migrations.AddIndex(
            model_name='aliceinsight',
            index=models.Index(fields=['agent', 'contact', 'subject_type'], name='aliceins_agent_ct_type_idx'),
        ),
        migrations.AddIndex(
            model_name='aliceinsight',
            index=models.Index(fields=['agent', 'subject_type', 'subject_key'], name='aliceins_agent_type_key_idx'),
        ),
        migrations.AddIndex(
            model_name='aliceinsight',
            index=models.Index(fields=['dt_last_updated'], name='aliceins_last_updated_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aliceinsight',
            unique_together={('agent', 'contact', 'subject_type', 'subject_key')},
        ),
        migrations.AddIndex(
            model_name='aliceobservation',
            index=models.Index(fields=['category', 'resolved'], name='aliceobs_cat_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='aliceobservation',
            index=models.Index(fields=['contact', 'acknowledged'], name='aliceobs_contact_ack_idx'),
        ),
        migrations.AddIndex(
            model_name='alicepreset',
            index=models.Index(fields=['preset_type', 'model_name'], name='alicepreset_type_model_idx'),
        ),
        migrations.AddIndex(
            model_name='schemadrift',
            index=models.Index(fields=['drift_type', 'is_resolved'], name='schema_drif_drift_t_75f09c_idx'),
        ),
        migrations.AddIndex(
            model_name='schemadrift',
            index=models.Index(fields=['file_path'], name='schema_drif_file_pa_d7f86b_idx'),
        ),
    ]
