# Generated by Django 5.2.8 on 2026-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alicecoachinglog',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aliceinsight',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aliceobservation',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alicepreset',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
    ]
