# Generated by Django 5.2.8 on 2026-09-04 21:11

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_add_episode_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('kind', models.CharField(choices=[('feedback', 'User feedback — tip, correction, change request'), ('help_lookup', 'Help lookup — shift-for-help query'), ('chat', 'Conversational exchange'), ('question', 'Question expecting an answer'), ('answer', 'Answer to a question'), ('observation', 'Agent pattern observation'), ('directive', 'Instruction between agents'), ('forward', 'Forwarded message')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet processed'), ('read', 'Read — seen by receiver'), ('reviewed', 'Reviewed — classified by Alice/admin'), ('actioned', 'Actioned — created task, updated help, etc.'), ('forwarded', 'Forwarded to another actor'), ('resolved', 'Resolved — no further action needed'), ('rejected', 'Rejected — not actionable')], db_index=True, default='pending', max_length=20)),
                ('sender', models.CharField(db_index=True, help_text='Actor name: user login, agent name (alice, allie, noelle, etc.), or wchq.', max_length=100)),
                ('sender_contact_id', models.IntegerField(blank=True, help_text='Contact FK when sender is a user. Null for agents.', null=True)),
                ('receiver', models.CharField(db_index=True, help_text='Actor name: alice, allie, wchq, bill, etc.', max_length=100)),
                ('receiver_contact_id', models.IntegerField(blank=True, help_text='Contact FK when receiver is a user. Null for agents.', null=True)),
                ('subject', models.CharField(blank=True, help_text='Short subject line — auto-generated from context if blank.', max_length=200)),
                ('body', models.TextField(help_text='The message content.')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured context: model, field, page, component, source_path.')),
                ('batch_id', models.CharField(blank=True, db_index=True, help_text='Groups related messages. E.g., all feedback from one help session.', max_length=50)),
                ('source_instance', models.UUIDField(blank=True, db_index=True, help_text='UUID of the WC3 instance that created this message.', null=True)),
                ('forward_of', models.ForeignKey(blank=True, help_text='Original message this was forwarded from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='ai_assistant.aimessage')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent message in a thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ai_assistant.aimessage')),
            ],
            options={
                'db_table': 'ai_message',
                'ordering': ['-dt_created'],
                'indexes': [models.Index(fields=['kind', 'status'], name='aimsg_kind_status_idx'), models.Index(fields=['sender', '-dt_created'], name='aimsg_sender_dt_idx'), models.Index(fields=['receiver', '-dt_created'], name='aimsg_receiver_dt_idx'), models.Index(fields=['batch_id'], name='aimsg_batch_idx')],
            },
        ),
    ]
