# Generated by Django 5.2.8 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_alicecoachinglog_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alicecoachinglog',
            name='alicecoach_contact_done_idx',
        ),
        migrations.RemoveIndex(
            model_name='aliceinsight',
            name='aliceins_agent_ct_type_idx',
        ),
        migrations.RemoveField(
            model_name='alicecoachinglog',
            name='contact',
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — coaching history survives)', null=True),
        ),
        migrations.RemoveField(
            model_name='aliceinsight',
            name='contact',
        ),
        migrations.AddField(
            model_name='aliceinsight',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — insights survive contact deletion)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='aliceinsight',
            unique_together={('agent', 'contact_id', 'subject_type', 'subject_key')},
        ),
        migrations.AddIndex(
            model_name='alicecoachinglog',
            index=models.Index(fields=['contact_id', 'completed'], name='alicecoach_contact_done_idx'),
        ),
        migrations.AddIndex(
            model_name='aliceinsight',
            index=models.Index(fields=['agent', 'contact_id', 'subject_type'], name='aliceins_agent_ct_type_idx'),
        ),
    ]
