# Generated by Django 5.2.8 on 2026-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_add_ai_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='classification',
            field=models.CharField(choices=[('technical', 'Technical — wc/react/system data. Safe to forward.'), ('operational', 'Operational — usage patterns, counts. Athena reviews.'), ('commercial', 'Commercial — prices, orders, customer data. Never leaves.'), ('personal', 'Personal — contact info, login, PII. Never leaves.')], db_index=True, default='technical', help_text='Data sensitivity. commercial/personal never leave the instance.', max_length=20),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='clearance',
            field=models.CharField(choices=[('local', 'Local only — not reviewed for forwarding'), ('pending', 'Pending Athena review'), ('cleared', 'Cleared — safe to forward'), ('blocked', 'Blocked — contains sensitive data')], db_index=True, default='local', help_text='Athena clearance for forwarding. commercial/personal auto-blocked.', max_length=20),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='scrubbed',
            field=models.BooleanField(default=False, help_text='True after PII scrubbing has been applied.'),
        ),
    ]
