# Generated by Django 5.2.8 on 2026-09-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_add_message_security_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alicecoachinglog',
            name='notes',
        ),
    ]
