# Generated by Django 5.2.8 on 2026-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_remove_alicecoachinglog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='event_type',
            field=models.CharField(choices=[('order_line_add', 'Line added to order'), ('order_line_update', 'Line quantity changed'), ('order_line_delete', 'Line removed from order'), ('order_convert_invoice', 'Order converted to invoice'), ('invoice_line_add', 'Line added to invoice'), ('invoice_line_update', 'Invoice line changed'), ('invoice_line_delete', 'Invoice line removed'), ('invoice_pack', 'Invoice lines packed/shipped'), ('po_create', 'Purchase order created'), ('po_line_add', 'PO line added'), ('po_line_update', 'PO line changed'), ('po_line_delete', 'PO line removed'), ('po_receive', 'PO goods received'), ('quote_line_add', 'Line added to quote'), ('quote_line_update', 'Quote line changed'), ('quote_line_delete', 'Quote line removed'), ('qty_adjust_up', 'Quantity increased'), ('qty_adjust_down', 'Quantity decreased'), ('cost_adjust', 'Unit cost changed'), ('below_reorder', 'Fell below reorder point'), ('below_safety', 'Fell below safety stock'), ('overstock', 'Exceeded max stock level'), ('pending_processed', 'Pending record processed')], db_index=True, max_length=30),
        ),
    ]
