# Generated by Django 5.2.8 on 2026-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_add_alice_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='alicecoachinglog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AlterField(
            model_name='aliceinsight',
            name='subject_type',
            field=models.CharField(choices=[('user', 'User Profile'), ('model', 'Model Usage'), ('flow', 'Transaction Flow'), ('sync', 'Sync Pattern'), ('coaching', 'Coaching Track'), ('security', 'Security Review'), ('risk', 'Risk Assessment'), ('system', 'System Health')], db_index=True, help_text='Category of insight', max_length=20),
        ),
        migrations.AlterField(
            model_name='alicepreset',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
