# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_alter_inventoryevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='alicecoachinglog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='aliceinsight',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='aliceobservation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='alicepreset',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_deleted',
        ),
    ]
