# Generated by Django 5.2.8 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_alicecoachinglog_config_aliceobservation_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alicecoachinglog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aliceinsight',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aliceobservation',
            name='category',
            field=models.CharField(choices=[('pattern', 'Workflow Pattern'), ('anomaly', 'Data Anomaly'), ('coaching', 'Coaching Suggestion'), ('alert', 'Alert'), ('search', 'Search Pattern'), ('layout', 'Layout Suggestion'), ('performance', 'Performance Issue'), ('schema', 'Pydantic Schema Question')], db_index=True, default='pattern', max_length=30),
        ),
    ]
