# Generated by Django 5.2.8 on 2026-09-22 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_remove_aimessage_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schemadrift',
            name='git_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drift_records', to='ai_assistant.gitevent'),
        ),
    ]
