# Generated by Django 5.2.8 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_purpose_to_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='alicecoachinglog',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='aliceinsight',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
    ]
