# Generated by Django 5.2.8 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_alter_conversation_user_alter_schemadrift_git_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='alicecoachinglog',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='aliceinsight',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='aliceobservation',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='alicepreset',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
    ]
