# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_target_model_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='alicecoachinglog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='aliceinsight',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='aliceobservation',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='alicepreset',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_locked',
        ),
    ]
