# Generated by Django 5.2.8 on 2026-08-15 15:54

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0012_add_bill_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alicecoachinglog',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='alicecoachinglog',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='aliceobservation',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='alicepreset',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
    ]
