# Generated by Django 5.2.5 on 2025-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, help_text='Source model this tag decorates', max_length=255, null=True),
        ),
    ]
