# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='linkageindex',
            name='linx_lkg_idx',
        ),
        migrations.RemoveIndex(
            model_name='linkageindex',
            name='linx_tbl_lkg_idx',
        ),
        migrations.RenameField(
            model_name='linkageindex',
            old_name='linkage',
            new_name='linkage_id',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answered_by_contact',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question_setting',
            new_name='setting_id',
        ),
        migrations.AddIndex(
            model_name='linkageindex',
            index=models.Index(fields=['linkage_id'], name='linx_lkg_idx'),
        ),
        migrations.AddIndex(
            model_name='linkageindex',
            index=models.Index(fields=['table_name', 'linkage_id'], name='linx_tbl_lkg_idx'),
        ),
    ]
