# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations, models


def _table_names(schema_editor) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return set(connection.introspection.table_names(cursor))


def _column_names(schema_editor, table_name: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _forward_compat_docs_0002(apps, schema_editor):
    tables = _table_names(schema_editor)

    if 'linkage_index' in tables:
        schema_editor.execute('DROP INDEX IF EXISTS linx_lkg_idx')
        schema_editor.execute('DROP INDEX IF EXISTS linx_tbl_lkg_idx')
        cols = _column_names(schema_editor, 'linkage_index')
        if 'linkage' in cols and 'linkage_id' not in cols:
            schema_editor.execute('ALTER TABLE linkage_index RENAME COLUMN linkage TO linkage_id')
        schema_editor.execute('CREATE INDEX IF NOT EXISTS linx_lkg_idx ON linkage_index (linkage_id)')
        schema_editor.execute('CREATE INDEX IF NOT EXISTS linx_tbl_lkg_idx ON linkage_index (table_name, linkage_id)')

    if 'qas' in tables:
        cols = _column_names(schema_editor, 'qas')
        if 'answered_by_contact_id' in cols and 'contact_id' not in cols:
            schema_editor.execute('ALTER TABLE qas RENAME COLUMN answered_by_contact_id TO contact_id')
        if 'question_setting_id' in cols and 'setting_id_id' not in cols:
            schema_editor.execute('ALTER TABLE qas RENAME COLUMN question_setting_id TO setting_id_id')


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward_compat_docs_0002, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='linkageindex',
                    name='linx_lkg_idx',
                ),
                migrations.RemoveIndex(
                    model_name='linkageindex',
                    name='linx_tbl_lkg_idx',
                ),
                migrations.RenameField(
                    model_name='linkageindex',
                    old_name='linkage',
                    new_name='linkage_id',
                ),
                migrations.RenameField(
                    model_name='questionanswer',
                    old_name='answered_by_contact',
                    new_name='contact_id',
                ),
                migrations.RenameField(
                    model_name='questionanswer',
                    old_name='question_setting',
                    new_name='setting_id',
                ),
                migrations.AddIndex(
                    model_name='linkageindex',
                    index=models.Index(fields=['linkage_id'], name='linx_lkg_idx'),
                ),
                migrations.AddIndex(
                    model_name='linkageindex',
                    index=models.Index(fields=['table_name', 'linkage_id'], name='linx_tbl_lkg_idx'),
                ),
            ],
        ),
    ]
