# Generated by Django 5.2.5 on 2025-08-29 16:00

import common.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('docs', '0002_delete_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='User comments and notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='document',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, help_text='Alternate ID for external systems (indexed)', max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized created timestamp (ms UTC)')),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized modified timestamp (ms UTC)')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1, help_text='Incremented on each successful save')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='User comments and notes')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'linkages',
                'indexes': [models.Index(fields=['purpose'], name='linkage_purpose_idx'), models.Index(fields=['name'], name='linkage_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, help_text='Alternate ID for external systems (indexed)', max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized created timestamp (ms UTC)')),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized modified timestamp (ms UTC)')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1, help_text='Incremented on each successful save')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='User comments and notes')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('question', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('security_level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('count_accessed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('answered_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_questions', to='core.setting')),
            ],
            options={
                'db_table': 'qas',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='qa_search_gin'), models.Index(fields=['security_level'], name='qa_sec_level_idx'), models.Index(fields=['status'], name='qa_status_idx'), models.Index(fields=['question'], name='qa_question_idx')],
            },
        ),
    ]
