# Generated by Django 5.2.8 on 2026-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_linkageindex_linx_lkg_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='confidential',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential'), ('secret', 'Secret')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='model_name',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('readme', 'Readme'), ('policy', 'Policy'), ('spec', 'Specification'), ('contract', 'Contract'), ('template', 'Template')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived'), ('retired', 'Retired')], db_index=True, max_length=255, null=True),
        ),
    ]
