# Generated by Django 5.2.8 on 2026-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_confidential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='linkage',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
    ]
