# Generated by Django 5.2.8 on 2026-07-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_seed_email_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='data',
            new_name='config',
        ),
    ]
