# Generated by Django 5.2.5 on 2025-08-29 16:29

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_comments_alter_document_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, help_text='Alternate ID for external systems (indexed)', max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized created timestamp (ms UTC)')),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized modified timestamp (ms UTC)')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1, help_text='Incremented on each successful save')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='User comments and notes')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('security_level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, db_index=True, help_text='Source table this tag decorates', max_length=255, null=True)),
                ('record_id', models.IntegerField(blank=True, db_index=True, help_text='ID in source table', null=True)),
                ('data', models.JSONField(blank=True, help_text='Arbitrary structured tag payload', null=True)),
                ('count_accessed', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'tags',
                'indexes': [models.Index(fields=['purpose'], name='tag_purpose_idx'), models.Index(fields=['status'], name='tag_status_idx'), models.Index(fields=['security_level'], name='tag_sec_level_idx'), models.Index(fields=['table_name', 'record_id'], name='tag_table_record_idx')],
            },
        ),
    ]
