# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_is_locked_linkage_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='linkage',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_locked',
        ),
    ]
