# Generated by Django 5.2.8 on 2026-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_rename_data_to_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_model_name_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='model_name',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_id',
            field=models.IntegerField(blank=True, help_text='ID of selected answer from Setting.config.questions[].answers[].id - set when user responds', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(blank=True, help_text='ID of the question from Setting.config.questions[].id', null=True),
        ),
    ]
