# Generated by Django 5.2.8 on 2026-02-05 20:04

from django.db import migrations, models


def _table_names(schema_editor) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return set(connection.introspection.table_names(cursor))


def _column_names(schema_editor, table_name: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _drop_column_if_exists(schema_editor, table_name: str, column_name: str):
    if table_name in _table_names(schema_editor):
        cols = _column_names(schema_editor, table_name)
        if column_name in cols:
            schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table_name)} DROP COLUMN {schema_editor.quote_name(column_name)}')


def _add_column_if_missing(schema_editor, table_name: str, column_sql: str, column_name: str):
    if table_name in _table_names(schema_editor):
        cols = _column_names(schema_editor, table_name)
        if column_name not in cols:
            schema_editor.execute(f'ALTER TABLE {schema_editor.quote_name(table_name)} ADD COLUMN {column_sql}')


def _forward_compat_docs_0006(apps, schema_editor):
    table_name = 'qas'
    if table_name not in _table_names(schema_editor):
        return

    _drop_column_if_exists(schema_editor, table_name, 'answered_by_name')
    _drop_column_if_exists(schema_editor, table_name, 'contact_id_id')
    _drop_column_if_exists(schema_editor, table_name, 'contact_id')

    _add_column_if_missing(
        schema_editor,
        table_name,
        'answer_id integer NULL',
        'answer_id',
    )
    _add_column_if_missing(
        schema_editor,
        table_name,
        'answered_by jsonb NULL',
        'answered_by',
    )
    _add_column_if_missing(
        schema_editor,
        table_name,
        'question_id integer NULL',
        'question_id',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_document_is_locked_remove_linkage_is_locked_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward_compat_docs_0006, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='questionanswer',
                    name='answered_by_name',
                ),
                migrations.RemoveField(
                    model_name='questionanswer',
                    name='contact_id',
                ),
                migrations.AddField(
                    model_name='questionanswer',
                    name='answer_id',
                    field=models.IntegerField(blank=True, help_text='ID of the selected answer option if applicable', null=True),
                ),
                migrations.AddField(
                    model_name='questionanswer',
                    name='answered_by',
                    field=models.JSONField(blank=True, help_text='Stores contact.id and contact.attention of who answered', null=True),
                ),
                migrations.AddField(
                    model_name='questionanswer',
                    name='question_id',
                    field=models.IntegerField(blank=True, help_text='ID of the question in the Setting if applicable', null=True),
                ),
                migrations.AlterField(
                    model_name='questionanswer',
                    name='answer',
                    field=models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
