# Generated by Django 5.2.8 on 2026-02-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_document_is_locked_remove_linkage_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answered_by_name',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_id',
            field=models.IntegerField(blank=True, help_text='ID of the selected answer option if applicable', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answered_by',
            field=models.JSONField(blank=True, help_text='Stores contact.id and contact.attention of who answered', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(blank=True, help_text='ID of the question in the Setting if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
