# Generated by Django 5.2.8 on 2026-02-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_parent_fields_to_qa'),
        ('docs', '0006_remove_questionanswer_answered_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='parent_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID of the parent record', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='parent_type',
            field=models.CharField(blank=True, db_index=True, help_text="Model name of the parent record (e.g., 'sales_order')", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['parent_type', 'parent_id'], name='qa_parent_idx'),
        ),
    ]
