# Generated by Django 5.2.8 on 2026-07-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_remove_questionanswer_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkageentry',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_id',
            field=models.IntegerField(blank=True, help_text='ID of selected answer from Document.config.questions[].answers[].id - set when user responds', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_questions', to='docs.document'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(blank=True, help_text='ID of the question from Document.config.questions[].id', null=True),
        ),
    ]
