# Generated by Django 5.2.8 on 2026-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_baseline_to_original'),
        ('docs', '0007_add_parent_fields_to_qa'),
    ]

    operations = [
        # Remove index first (it references the old field name)
        migrations.RemoveIndex(
            model_name='questionanswer',
            name='qa_parent_idx',
        ),
        # Rename the field (preserves existing data)
        migrations.RenameField(
            model_name='questionanswer',
            old_name='parent_type',
            new_name='parent_model_name',
        ),
        # Re-create index with new field name
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['parent_model_name', 'parent_id'], name='qa_parent_idx'),
        ),
    ]
