# Generated by Django 5.2.8 on 2026-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_rename_parent_type_to_parent_model_name'),
    ]

    operations = [
        # Remove existing index (references old field name)
        migrations.RemoveIndex(
            model_name='questionanswer',
            name='qa_parent_idx',
        ),
        # Rename the field (preserves data)
        migrations.RenameField(
            model_name='questionanswer',
            old_name='parent_model_name',
            new_name='parent_model',
        ),
        # Re-create index with new field name
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['parent_model', 'parent_id'], name='qa_parent_idx'),
        ),
    ]
