# Generated by Django 5.2.8 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_rename_parent_model_name_to_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_id',
            field=models.IntegerField(blank=True, help_text='ID of selected answer from Setting.data.questions[].answers[].id - set when user responds', null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='parent_model',
            field=models.CharField(blank=True, db_index=True, help_text="Model name of the parent record (e.g., 'order', 'customer')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(blank=True, help_text='ID of the question from Setting.data.questions[].id', null=True),
        ),
    ]
