# Generated by Django 5.2.8 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_add_document_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkageentry',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
    ]
