# Generated by Django 5.2.8 on 2026-02-10 00:27

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_questionanswer_answer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkageEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('group_id', models.BigIntegerField(db_index=True, help_text='Links with same group_id form a relationship cluster')),
                ('model_name', models.CharField(db_index=True, help_text="Target model (e.g., 'order', 'item', 'contact')", max_length=255)),
                ('record_id', models.BigIntegerField(db_index=True, help_text='ID in target model')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Linkage purpose/type', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text='Human-readable name', max_length=255, null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Notes about this specific link')),
                ('role', models.CharField(blank=True, db_index=True, help_text="Role in the linkage (e.g., 'source', 'target')", max_length=100, null=True)),
                ('sequence', models.IntegerField(db_index=True, default=0, help_text='Order within group')),
            ],
            options={
                'db_table': 'linkage_entries',
                'ordering': ['group_id', 'sequence', 'id'],
                'indexes': [models.Index(fields=['group_id'], name='linkent_group_idx'), models.Index(fields=['model_name', 'group_id'], name='linkent_model_group_idx'), models.Index(fields=['purpose'], name='linkent_purpose_idx'), models.Index(fields=['role'], name='linkent_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'record_id'), name='uniq_linkage_entry_record')],
            },
        ),
    ]
