# Generated by Django 5.2.8 on 2026-02-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_create_linkage_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkageindex',
            name='linkage_id',
        ),
        migrations.DeleteModel(
            name='Linkage',
        ),
        migrations.DeleteModel(
            name='LinkageIndex',
        ),
    ]
