# Generated by Django 5.2.8 on 2026-02-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_remove_linkageindex_linkage_id_delete_linkage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='setting_id',
            field=models.ForeignKey(blank=True, db_column='setting_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_questions', to='core.setting'),
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='setting_id',
            new_name='setting',
        ),
    ]
