# Generated by Django 5.2.8 on 2026-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modellinkconfig',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelroleconfig',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refsmismatchlog',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdailylog',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
    ]
