# Generated by Django 5.2.8 on 2026-08-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pending_status_alter_action_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='id_session',
            new_name='session_id',
        ),
    ]
