# Generated by Django 5.2.8 on 2026-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_prefix_to_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='employee',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Contact is an employee of this company'),
        ),
    ]
