# Generated by Django 5.2.8 on 2026-09-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_to_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='component',
            field=models.CharField(blank=True, help_text="React component path (e.g. 'apps/accounting/ApplyCash')", max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(help_text="Display name (e.g. 'Apply Cash')", max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='route',
            field=models.CharField(blank=True, help_text="URL route segment (e.g. '/app/apply-cash')", max_length=255),
        ),
    ]
