# Generated by Django 5.2.8 on 2026-09-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cash_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='script_after',
        ),
        migrations.RemoveField(
            model_name='report',
            name='script_before',
        ),
        migrations.RemoveField(
            model_name='report',
            name='script_during',
        ),
    ]
