# Generated by Django 5.2.8 on 2026-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_drop_setting_schema_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(blank=True, choices=[('', ''), ('call', 'Call'), ('email', 'Email'), ('visit', 'Visit'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('marketing', 'Marketing'), ('referral', 'Referral'), ('social', 'Social Media'), ('event', 'Event'), ('follow_up', 'Follow-up'), ('inquiry', 'Inquiry'), ('other', 'Other')], db_index=True, default='', help_text='Type of selling action: call, email, visit, demo, etc.', max_length=50),
        ),
    ]
