# Generated by Django 5.2.8 on 2026-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='output_type',
            field=models.CharField(blank=True, choices=[('print', 'Print / PDF'), ('email', 'Email (SMTP)'), ('api', 'POST to external endpoint'), ('json', 'Return structured JSON'), ('export', 'CSV / Excel download'), ('label', 'Label / barcode print'), ('merge', 'Word / spreadsheet merge')], default='print', help_text='What the report produces (print, email, api, json, export, label)', max_length=30, null=True),
        ),
    ]
