# Generated by Django 5.2.8 on 2026-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_action_type_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(help_text="Model that was changed (e.g., 'quote', 'order')", max_length=100),
        ),
    ]
