# Generated by Django 5.2.8 on 2026-09-20 22:15

from django.db import migrations, models


def stored_searches_become_reports(apps, schema_editor):
    """Bring the two legacy homes of a stored search into Report records.

    Before this, a stored search could be in any of three places: a Report with
    no marker, a Setting with purpose 'wc:search', or an entry in a user's
    UserProfile.prefs.search[] list. The first could not be told apart from a
    print form; the last two could not be listed, shared or carried in a bundle.
    After this there is one home, marked by purpose='search_stored'.
    """
    Report = apps.get_model('core', 'Report')
    Setting = apps.get_model('core', 'Setting')

    # 1. Reports that already are searches — mark them.
    Report.objects.filter(category__in=('search', 'list'), output_type='search').update(
        purpose='search_stored')
    Report.objects.filter(category='search').update(purpose='search_stored')

    # 2. Legacy Settings with purpose 'wc:search'.
    for setting in Setting.objects.filter(purpose='wc:search'):
        model_name = setting.parent_model or ''
        name = setting.name or ''
        if not name or not model_name:
            continue
        if Report.objects.filter(name=name, model_name=model_name,
                                 purpose='search_stored').exists():
            continue
        Report.objects.create(
            name=name,
            model_name=model_name,
            purpose='search_stored',
            category='search',
            output_type='search',
            role_required=getattr(setting, 'role', '') or '',
            description=getattr(setting, 'explanation', '') or '',
            config=setting.config if isinstance(setting.config, dict) else {},
            is_active=True,
        )

    # 3. Personal searches out of UserProfile.prefs.search[].
    try:
        UserProfile = apps.get_model('core', 'UserProfile')
    except LookupError:
        UserProfile = None
    if UserProfile is not None:
        for profile in UserProfile.objects.exclude(prefs=None):
            prefs = profile.prefs if isinstance(profile.prefs, dict) else {}
            entries = prefs.get('search')
            if not isinstance(entries, list) or not entries:
                continue
            owner_id = getattr(profile, 'user_id', None)
            for entry in entries:
                if not isinstance(entry, dict):
                    continue
                name = (entry.get('name') or '').strip()
                model_name = (entry.get('model_name') or '').strip()
                if not name or not model_name:
                    continue
                config = {k: v for k, v in entry.items()
                          if k not in ('name', 'model_name', 'dt_saved')}
                if owner_id is not None:
                    config['owner_user_id'] = owner_id
                if Report.objects.filter(name=name, model_name=model_name,
                                         purpose='search_stored',
                                         config__owner_user_id=owner_id).exists():
                    continue
                Report.objects.create(
                    name=name,
                    model_name=model_name,
                    purpose='search_stored',
                    category='list',
                    output_type='screen',
                    config=config,
                    is_active=True,
                )
            prefs.pop('search', None)
            profile.prefs = prefs
            profile.save(update_fields=['prefs'])


def stored_searches_stay_put(apps, schema_editor):
    """Reverse: unmark. The records stay — they are better where they are."""
    Report = apps.get_model('core', 'Report')
    Report.objects.filter(purpose='search_stored').update(purpose='')


def executables_lose_the_tally_category(apps, schema_editor):
    """'tally' was WC2's word. There is no Tally model — they are reports."""
    Report = apps.get_model('core', 'Report')
    Report.objects.filter(category='tally').update(
        category='report', purpose='report_executable')


def executables_regain_the_tally_category(apps, schema_editor):
    Report = apps.get_model('core', 'Report')
    Report.objects.filter(purpose='report_executable').update(category='tally')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form'), ('report', 'Report'), ('statement', 'Statement'), ('list', 'List'), ('summary', 'Summary'), ('letter', 'Letter / Email'), ('label', 'Label'), ('export', 'Export'), ('function', 'Function'), ('utility', 'Utility'), ('dashboard', 'Dashboard widget')], default='report', help_text='Menu grouping (report, statement, list, summary, etc.)', max_length=30, null=True),
        ),
        migrations.RunPython(executables_lose_the_tally_category,
                             executables_regain_the_tally_category),
        migrations.RunPython(stored_searches_become_reports,
                             stored_searches_stay_put),
    ]
