# Generated by Django 5.2.8 on 2026-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report_purpose_search_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
