# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pending_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='modellinkconfig',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='modelroleconfig',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='refsmismatchlog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='roleconfig',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userdailylog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='SoftDeleteLedger',
        ),
    ]
