# Generated by Django 5.2.8 on 2026-09-22 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_action_is_deleted_remove_apilog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailylog',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='User this daily summary belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
