# Generated by Django 5.2.8 on 2026-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_data_to_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this contact originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('view_edit', 'view_edit'), ('constants', 'constants'), ('db_defaults', 'db_defaults'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('keywords', 'keywords'), ('search', 'search'), ('workbench_fields', 'workbench_fields'), ('detail_field_access', 'detail_field_access'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings'), ('list_column_config', 'list_column_config'), ('alice_pending', 'alice_pending'), ('alice_log', 'alice_log'), ('field_access', 'field_access'), ('seed', 'seed'), ('alice_coaching', 'alice_coaching'), ('campaign', 'campaign'), ('company_profile', 'company_profile'), ('accounting_interface', 'accounting_interface')], max_length=255, null=True),
        ),
    ]
