# Generated by Django 5.2.8 on 2026-09-24 20:41

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_report_hook_slot_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pending',
            constraint=models.UniqueConstraint(django.db.models.fields.json.KeyTextTransform('gateway_event_id', 'changes'), condition=models.Q(('changes__has_key', 'gateway_event_id')), name='uniq_pending_gateway_event'),
        ),
    ]
