# Generated by Django 5.2.8 on 2026-07-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.JSONField(blank=True, db_column='action', default=dict, null=True),
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='task',
        ),
    ]
