# Generated by Django 5.2.8 on 2026-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_retrospection_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
