# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_target_model_setting_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='modellinkconfig',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='modelroleconfig',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='refsmismatchlog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='roleconfig',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='userdailylog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='is_locked',
        ),
    ]
