# Generated by Django 5.2.8 on 2026-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_pending_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending',
            name='changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pending',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
