# Generated by Django 5.2.8 on 2026-08-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pending_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='User contact ID — 0 = all users'),
        ),
        migrations.AddField(
            model_name='setting',
            name='org_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Organization ID — 0 = all orgs'),
        ),
        migrations.AddField(
            model_name='setting',
            name='scope',
            field=models.CharField(choices=[('system', 'System — all orgs, all users'), ('org', 'Organization — one business'), ('role', 'Role — one role within an org'), ('user', 'User — one person')], db_index=True, default='system', help_text='system=everyone, org=one business, role=one role, user=one person', max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(None, ''), (1, 'Easy (1)'), (4, 'Average (4)'), (8, 'Hard (8)'), (13, 'Complex (13)'), (21, 'Expert (21)')], default=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('detail_layout', 'detail_layout'), ('compact_layout', 'compact_layout'), ('list_column_config', 'list_column_config'), ('field_registry', 'field_registry'), ('view_edit', 'view_edit'), ('field_access', 'field_access'), ('detail_field_access', 'detail_field_access'), ('workbench_fields', 'workbench_fields'), ('db_defaults', 'db_defaults'), ('constants', 'constants'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('accounting_interface', 'accounting_interface'), ('print_defaults', 'print_defaults'), ('keywords', 'keywords'), ('search', 'search'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('alice_pending', 'alice_pending'), ('alice_log', 'alice_log'), ('alice_coaching', 'alice_coaching'), ('ai_prompt_history', 'ai_prompt_history'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings'), ('seed', 'seed'), ('system', 'system'), ('feature', 'feature'), ('schema_map', 'schema_map'), ('calculated_function', 'calculated_function'), ('campaign', 'campaign'), ('company_profile', 'company_profile'), ('collaborate_webclerk', 'collaborate_webclerk'), ('wchq_connection', 'wchq_connection'), ('sync_config', 'sync_config'), ('file_storage', 'file_storage'), ('gantt_defaults', 'gantt_defaults'), ('burndown_config', 'burndown_config')], max_length=255, null=True),
        ),
    ]
