# Generated by Django 5.2.8 on 2026-08-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_enable_fts_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='script_after',
            field=models.TextField(blank=True, default='', help_text='Completion phase: write results, format output, send notifications, update records'),
        ),
        migrations.AddField(
            model_name='report',
            name='script_before',
            field=models.TextField(blank=True, default='', help_text='Setup phase: initialize accumulators, apply filters, establish selections'),
        ),
        migrations.AddField(
            model_name='report',
            name='script_during',
            field=models.TextField(blank=True, default='', help_text='Calculation phase: the business logic — line extensions, bucket assignments, GL accumulation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form'), ('report', 'Report'), ('statement', 'Statement'), ('list', 'List'), ('summary', 'Summary'), ('letter', 'Letter / Email'), ('label', 'Label'), ('export', 'Export'), ('utility', 'Utility'), ('tally', 'Tally / Calculation'), ('dashboard', 'Dashboard widget')], default='report', help_text='Menu grouping (report, statement, list, summary, etc.)', max_length=30, null=True),
        ),
    ]
