# Generated by Django 5.2.8 on 2026-08-09 17:45

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_report_script_fields_and_tally_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='action',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Hashed password', max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='modellinkconfig',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='modellinkconfig',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='modelroleconfig',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='modelroleconfig',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='refsmismatchlog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='refsmismatchlog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='report',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='template',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='template',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='userdailylog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='userdailylog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
    ]
