# Generated by Django 5.2.8 on 2026-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_action_comments_alter_action_prefs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form'), ('report', 'Report'), ('statement', 'Statement'), ('list', 'List'), ('summary', 'Summary'), ('letter', 'Letter / Email'), ('label', 'Label'), ('export', 'Export'), ('function', 'Function'), ('utility', 'Utility'), ('tally', 'Tally / Calculation'), ('dashboard', 'Dashboard widget')], default='report', help_text='Menu grouping (report, statement, list, summary, etc.)', max_length=30, null=True),
        ),
    ]
