# Generated by Django 5.2.8 on 2026-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(blank=True, choices=[('', ''), ('call', 'Call'), ('email', 'Email'), ('visit', 'Visit'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('marketing', 'Marketing'), ('referral', 'Referral'), ('social', 'Social Media'), ('event', 'Event'), ('follow_up', 'Follow-up'), ('other', 'Other')], db_index=True, default='', help_text='Type of selling action: call, email, visit, demo, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='predicted_impact',
            field=models.PositiveIntegerField(choices=[(0, 'Not rated'), (1, 'Minimal (1)'), (2, 'Low (2)'), (3, 'Moderate (3)'), (4, 'High (4)'), (5, 'Critical (5)')], db_index=True, default=0, help_text='Subjective guess at scale of impact (1-5). Scored against actual outcomes.'),
        ),
    ]
