# Generated by Django 5.2.8 on 2026-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_predicted_impact_to_impact_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Report body content — interpreted according to editor_type (plain, markdown, or HTML)'),
        ),
        migrations.AddField(
            model_name='report',
            name='editor_type',
            field=models.CharField(blank=True, choices=[('plain', 'Plain text'), ('markdown', 'Markdown'), ('html', 'HTML (rich text)')], default='plain', help_text='Which editor the frontend renders for the content field', max_length=20, null=True),
        ),
    ]
