# Generated by Django 5.2.8 on 2026-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_workspace_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='What this Setting governs — human-readable description of purpose and parent_model relationship'),
        ),
        migrations.AddField(
            model_name='setting',
            name='paths',
            field=models.JSONField(blank=True, default=dict, help_text='Pointers to supporting documentation, schema files, pages, and related code'),
        ),
    ]
