# Generated by Django 5.2.8 on 2026-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_setting_add_explanation_and_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='What this report does, what config holds, how it relates to its model — human-readable'),
        ),
        migrations.AddField(
            model_name='report',
            name='paths',
            field=models.JSONField(blank=True, default=dict, help_text='Pointers to supporting files: schema, page, template, print definition'),
        ),
    ]
