# Generated by Django 5.2.8 on 2026-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_report_add_explanation_and_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
    ]
