# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_setting_purpose 2'),
        ('core', '0016_add_source_name 2'),
        ('core', '0022_alter_pending_config 2'),
        ('core', '0023_pending_attempts_changes 2'),
        ('core', '0027_purpose_to_basemodel 2'),
        ('core', '0028_seed_print_templates 2'),
        ('core', '0031_add_dt_approved 2'),
        ('core', '0035_alter_action_comments_alter_action_prefs_and_more 2'),
        ('core', '0036_add_commission_line_type_and_function_category 2'),
        ('core', '0040_contact_email_nullable 2'),
        ('core', '0041_add_wc_model_purpose 2'),
        ('core', '0045_drop_comment_field'),
    ]

    operations = [
    ]
