"""
Management command: generate_context

Auto-generates machine-readable context files for Copilot and the AI assistant.
Outputs to .copilot-context/ for indexing into ChromaDB.

Usage:
    python manage.py generate_context                  # generate everything
    python manage.py generate_context --target models   # model field reference only
    python manage.py generate_context --target fixtures  # golden fixture shapes only
    python manage.py generate_context --target imports   # canonical import paths only
    python manage.py generate_context --target endpoints # endpoint map only
"""
import json
import time
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import models


BASE_DIR = Path(settings.BASE_DIR)
WORKSPACE_ROOT = BASE_DIR.parent
CONTEXT_DIR = BASE_DIR / ".copilot-context"

# Apps we care about (skip django.contrib.*, etc.)
PROJECT_APP_PREFIXES = ("apps.", "common.")

TARGETS = ["models", "fixtures", "imports", "endpoints"]


class Command(BaseCommand):
    help = "Generate machine-readable context files for Copilot and AI assistant"

    def add_arguments(self, parser):
        parser.add_argument(
            "--target",
            type=str,
            choices=TARGETS + ["all"],
            default="all",
            help="Which context to generate (default: all)",
        )

    def handle(self, *args, **options):
        start = time.time()
        target = options["target"]

        # Ensure directories exist
        for subdir in ["models", "fixtures", "imports", "maps"]:
            (CONTEXT_DIR / subdir).mkdir(parents=True, exist_ok=True)

        targets = TARGETS if target == "all" else [target]

        for t in targets:
            self.stdout.write(f"\n{'='*60}")
            self.stdout.write(self.style.HTTP_INFO(f"Generating: {t}"))
            self.stdout.write(f"{'='*60}")

            handler = getattr(self, f"_generate_{t}", None)
            if handler:
                handler()
            else:
                self.stderr.write(self.style.ERROR(f"Unknown target: {t}"))

        elapsed = time.time() - start
        self.stdout.write(f"\n{'='*60}")
        self.stdout.write(self.style.SUCCESS(
            f"Context generation complete in {elapsed:.1f}s\n"
            f"  Output: {CONTEXT_DIR}"
        ))

    # ── Models ──────────────────────────────────────────────────

    def _generate_models(self):
        """Generate model-reference.md with every field of every project model."""
        lines = [
            "# Django Model Field Reference",
            "",
            "> Auto-generated by `python manage.py generate_context --target models`",
            f"> Generated: {time.strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
        ]

        project_models = self._get_project_models()
        self.stdout.write(f"Found {len(project_models)} project models")

        # Group by app
        by_app: dict[str, list] = {}
        for model in project_models:
            app = model._meta.app_label
            by_app.setdefault(app, []).append(model)

        for app_label in sorted(by_app.keys()):
            app_models = sorted(by_app[app_label], key=lambda m: m.__name__)
            lines.append(f"## {app_label}")
            lines.append("")

            for model in app_models:
                lines.extend(self._model_to_markdown(model))
                lines.append("")

        output = CONTEXT_DIR / "models" / "model-reference.md"
        output.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(
            f"  → {output.relative_to(BASE_DIR)} ({len(project_models)} models)"
        ))

        # Also generate hierarchy overview
        self._generate_model_hierarchy()

    def _model_to_markdown(self, model) -> list[str]:
        """Convert a single model to markdown documentation."""
        meta = model._meta
        lines = []

        # Header with inheritance chain
        mro_names = [
            c.__name__ for c in model.__mro__
            if c.__name__ not in ("object", "Model") and hasattr(c, "_meta")
        ]
        lines.append(f"### `{model.__name__}`")
        lines.append("")
        lines.append(f"- **App:** `{meta.app_label}`")
        lines.append(f"- **Table:** `{meta.db_table}`")
        lines.append(f"- **Abstract:** {'Yes' if meta.abstract else 'No'}")

        if len(mro_names) > 1:
            lines.append(f"- **Inherits:** {' → '.join(mro_names)}")

        if meta.ordering:
            lines.append(f"- **Ordering:** `{meta.ordering}`")

        if model.__doc__ and model.__doc__.strip():
            doc = model.__doc__.strip().split("\n")[0]  # First line only
            lines.append(f"- **Docstring:** {doc}")

        lines.append("")

        # Fields table
        fields = [f for f in meta.get_fields() if hasattr(f, "column") or hasattr(f, "field")]

        if fields:
            lines.append("| Field | Type | Null | Default | Notes |")
            lines.append("|-------|------|------|---------|-------|")

            for field in sorted(fields, key=lambda f: getattr(f, "name", "")):
                name = getattr(field, "name", str(field))
                field_type = type(field).__name__

                # Get details
                nullable = "Yes" if getattr(field, "null", False) else "No"
                blank = getattr(field, "blank", False)
                default = getattr(field, "default", models.NOT_PROVIDED)

                if default is models.NOT_PROVIDED:
                    default_str = "—"
                elif callable(default):
                    default_str = f"`{default.__name__}()`" if hasattr(default, "__name__") else "`callable`"
                elif isinstance(default, dict):
                    default_str = "`{}`" if not default else f"`{json.dumps(default)[:50]}`"
                elif isinstance(default, list):
                    default_str = "`[]`" if not default else f"`{json.dumps(default)[:50]}`"
                else:
                    default_str = f"`{default}`"

                # Notes column
                notes = []
                if getattr(field, "primary_key", False):
                    notes.append("PK")
                if getattr(field, "unique", False) and not getattr(field, "primary_key", False):
                    notes.append("unique")
                if blank:
                    notes.append("blank ok")
                if hasattr(field, "choices") and field.choices:
                    choices_display = [str(c[0]) for c in field.choices[:5]]
                    notes.append(f"choices: {', '.join(choices_display)}")
                if hasattr(field, "related_model") and field.related_model:
                    rel = field.related_model.__name__
                    rel_name_attr = getattr(field, "related_query_name", None)
                    rel_name = rel_name_attr() if callable(rel_name_attr) else (rel_name_attr or "")
                    notes.append(f"FK → {rel}")
                    if rel_name:
                        notes.append(f"related: {rel_name}")
                if hasattr(field, "max_length") and field.max_length:
                    notes.append(f"max={field.max_length}")
                if hasattr(field, "help_text") and field.help_text:
                    notes.append(str(field.help_text)[:60])

                notes_str = "; ".join(notes) if notes else "—"
                lines.append(f"| `{name}` | {field_type} | {nullable} | {default_str} | {notes_str} |")

        lines.append("")
        return lines

    def _generate_model_hierarchy(self):
        """Generate model-hierarchy.md showing the mixin chain."""
        lines = [
            "# Model Hierarchy",
            "",
            "> Auto-generated overview of the CoreModel → BaseModel mixin chain.",
            "",
            "---",
            "",
            "## Two-Tier Pattern",
            "",
            "| Base | Use Case | JSON Envelopes |",
            "|------|----------|----------------|",
            "| `CoreModel` | Lightweight entities (Pending, Log) | No |",
            "| `BaseModel` | Full entities (Contact, Order, Item) | Yes (metadata, refs, prefs, actions, comments) |",
            "| `TransactionBaseModel` | Transactions (Order, Invoice) | Yes + totals, status, flow fields |",
            "",
            "## BaseModel Composition",
            "",
            "```",
            "BaseModel",
            "  ├── CoreModel          (id, uuid, ida, dt_created, dt_modified, version, is_active, security_level)",
            "  ├── ActionsMixin        (actions JSONField — required, status, who, when, what)",
            "  ├── MetadataMixin       (metadata JSONField — history, health, flags, images, flow, source)",
            "  ├── RefsMixin           (refs JSONField — keywords, tags, links, parents, depends_on, categories)",
            "  ├── KeywordsMixin       (keywords TextField — full-text search)",
            "  ├── PrefsMixin          (prefs JSONField — user-defined settings)",
            "  ├── CommentsMixin       (comments JSONField — public, process, partner, notes[])",
            "  ├── HealthMixin         (health_rating IntegerField)",
            "  ├── LifecycleMixin      (is_deleted, is_archived + soft_delete/restore/archive)",
            "  ├── UniversalDictMixin  (to_universal_dict() serialization contract)",
            "  └── AtomicJSONMixin     (atomic_json_set, atomic_list_append for partial JSONB updates)",
            "```",
            "",
            "## Models by Base Class",
            "",
        ]

        project_models = self._get_project_models()

        core_models = []
        base_models = []
        transaction_models = []
        other_models = []

        for model in project_models:
            if model._meta.abstract:
                continue
            mro_names = [c.__name__ for c in model.__mro__]
            if "TransactionBaseModel" in mro_names:
                transaction_models.append(model)
            elif "BaseModel" in mro_names and "CoreModel" in mro_names:
                base_models.append(model)
            elif "CoreModel" in mro_names:
                core_models.append(model)
            else:
                other_models.append(model)

        def model_list(title, model_list):
            lines.append(f"### {title}")
            lines.append("")
            for m in sorted(model_list, key=lambda m: m.__name__):
                lines.append(f"- `{m._meta.app_label}.{m.__name__}`")
            lines.append("")

        if core_models:
            model_list("CoreModel (lightweight)", core_models)
        if base_models:
            model_list("BaseModel (full)", base_models)
        if transaction_models:
            model_list("TransactionBaseModel (transactions)", transaction_models)
        if other_models:
            model_list("Other", other_models)

        output = CONTEXT_DIR / "models" / "model-hierarchy.md"
        output.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  → {output.relative_to(BASE_DIR)}"))

    # ── Fixtures ────────────────────────────────────────────────

    def _generate_fixtures(self):
        """Generate golden fixture JSON for each model showing field shapes."""
        project_models = [m for m in self._get_project_models() if not m._meta.abstract]
        count = 0

        for model in sorted(project_models, key=lambda m: m.__name__):
            fixture = self._model_to_fixture(model)
            filename = f"{model.__name__.lower()}.json"
            output = CONTEXT_DIR / "fixtures" / filename
            output.write_text(
                json.dumps(fixture, indent=2, default=str),
                encoding="utf-8",
            )
            count += 1

        self.stdout.write(self.style.SUCCESS(
            f"  → {CONTEXT_DIR.relative_to(BASE_DIR)}/fixtures/ ({count} fixtures)"
        ))

    def _model_to_fixture(self, model) -> dict:
        """Build a shape-only fixture showing field types without real data."""
        fixture = {
            "__model__": f"{model._meta.app_label}.{model.__name__}",
            "__table__": model._meta.db_table,
        }

        for field in model._meta.get_fields():
            if not hasattr(field, "column"):
                continue

            name = field.name
            field_type = type(field).__name__

            # Generate a type-appropriate placeholder
            if isinstance(field, models.AutoField) or isinstance(field, models.BigAutoField):
                fixture[name] = "<int:pk>"
            elif isinstance(field, models.UUIDField):
                fixture[name] = "<uuid>"
            elif isinstance(field, models.CharField):
                max_len = field.max_length or 255
                if field.choices:
                    fixture[name] = f"<choice:{[c[0] for c in field.choices[:3]]}>"
                else:
                    fixture[name] = f"<str:max{max_len}>"
            elif isinstance(field, models.TextField):
                fixture[name] = "<text>"
            elif isinstance(field, models.IntegerField) or isinstance(field, models.SmallIntegerField):
                fixture[name] = "<int>"
            elif isinstance(field, models.BigIntegerField):
                fixture[name] = "<bigint>"
            elif isinstance(field, models.FloatField):
                fixture[name] = "<float>"
            elif isinstance(field, models.DecimalField):
                md = field.max_digits or 10
                dp = field.decimal_places or 2
                fixture[name] = f"<decimal:{md}.{dp}>"
            elif isinstance(field, models.BooleanField):
                default = getattr(field, "default", None)
                fixture[name] = default if isinstance(default, bool) else "<bool>"
            elif isinstance(field, models.DateTimeField):
                fixture[name] = "<datetime:ISO8601>"
            elif isinstance(field, models.DateField):
                fixture[name] = "<date:YYYY-MM-DD>"
            elif isinstance(field, models.TimeField):
                fixture[name] = "<time:HH:MM:SS>"
            elif isinstance(field, models.JSONField):
                default = getattr(field, "default", None)
                if callable(default):
                    try:
                        fixture[name] = default()
                    except Exception:
                        fixture[name] = "<json>"
                elif default is not None and default is not models.NOT_PROVIDED:
                    fixture[name] = default
                else:
                    fixture[name] = "<json>"
            elif isinstance(field, models.ForeignKey):
                fixture[name] = f"<fk:{field.related_model.__name__}>"
                fixture[f"{name}_id"] = "<int:fk>"
            elif isinstance(field, models.EmailField):
                fixture[name] = "<email>"
            elif isinstance(field, models.URLField):
                fixture[name] = "<url>"
            elif isinstance(field, models.FileField) or isinstance(field, models.ImageField):
                fixture[name] = "<file:path>"
            else:
                fixture[name] = f"<{field_type.lower()}>"

        return fixture

    # ── Imports ─────────────────────────────────────────────────

    def _generate_imports(self):
        """Generate canonical import path references for Django and React."""
        self._generate_django_imports()
        self._generate_react_imports()

    def _generate_django_imports(self):
        """Scan for service classes, view classes, and model classes."""
        lines = [
            "# Django Canonical Import Paths",
            "",
            "> Auto-generated. Every public class/function with its exact import path.",
            f"> Generated: {time.strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
        ]

        # Models
        lines.append("## Models")
        lines.append("")
        lines.append("| Class | Import |")
        lines.append("|-------|--------|")

        for model in sorted(self._get_project_models(), key=lambda m: m.__name__):
            module = model.__module__
            lines.append(f"| `{model.__name__}` | `from {module} import {model.__name__}` |")

        lines.extend(["", ""])

        # Services — scan files
        lines.append("## Services & Business Logic")
        lines.append("")
        lines.append("| Module | Key Exports |")
        lines.append("|--------|-------------|")

        services_data = self._scan_python_exports(
            BASE_DIR / "apps",
            file_patterns=["services/", "service.py"],
        )
        for module_path, exports in sorted(services_data.items()):
            exports_str = ", ".join(f"`{e}`" for e in exports[:5])
            if len(exports) > 5:
                exports_str += f" + {len(exports) - 5} more"
            lines.append(f"| `{module_path}` | {exports_str} |")

        lines.extend(["", ""])

        # Views
        lines.append("## Views")
        lines.append("")
        lines.append("| Module | Key Exports |")
        lines.append("|--------|-------------|")

        views_data = self._scan_python_exports(
            BASE_DIR / "apps",
            file_patterns=["views/", "views.py"],
        )
        for module_path, exports in sorted(views_data.items()):
            exports_str = ", ".join(f"`{e}`" for e in exports[:5])
            if len(exports) > 5:
                exports_str += f" + {len(exports) - 5} more"
            lines.append(f"| `{module_path}` | {exports_str} |")

        output = CONTEXT_DIR / "imports" / "django-imports.md"
        output.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  → {output.relative_to(BASE_DIR)}"))

    def _generate_react_imports(self):
        """Scan React2025/src/ for TypeScript exports."""
        lines = [
            "# React Canonical Import Paths",
            "",
            "> Auto-generated. Key React components, hooks, services, and types with import paths.",
            f"> Generated: {time.strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
        ]

        react_src = WORKSPACE_ROOT / "React2025" / "src"
        if not react_src.exists():
            self.stdout.write(self.style.WARNING("  React2025/src/ not found, skipping"))
            return

        # Scan categories
        categories = [
            ("Services", ["services/"], [".ts", ".tsx"]),
            ("Hooks", ["hooks/", "use"], [".ts", ".tsx"]),
            ("Pages", ["pages/"], [".tsx"]),
            ("Types", ["types/"], [".ts"]),
            ("API Clients", ["api/"], [".ts"]),
        ]

        for cat_label, patterns, extensions in categories:
            lines.append(f"## {cat_label}")
            lines.append("")
            lines.append("| File | Import Path |")
            lines.append("|------|-------------|")

            for filepath in sorted(react_src.rglob("*")):
                if not filepath.is_file():
                    continue
                if filepath.suffix not in extensions:
                    continue
                if any(part in filepath.parts for part in ("node_modules", ".git", "dist", "__tests__")):
                    continue

                rel = str(filepath.relative_to(react_src))
                if not any(pat in rel for pat in patterns):
                    continue

                # Skip index files and test files
                if filepath.stem.startswith("__") or ".test." in filepath.name or ".spec." in filepath.name:
                    continue

                import_path = rel.replace(filepath.suffix, "")
                lines.append(f"| `{filepath.name}` | `import from '@/{import_path}'` |")

            lines.extend(["", ""])

        output = CONTEXT_DIR / "imports" / "react-imports.md"
        output.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  → {output.relative_to(BASE_DIR)}"))

    # ── Endpoints ───────────────────────────────────────────────

    def _generate_endpoints(self):
        """Map URL patterns → views → purpose."""
        lines = [
            "# API Endpoint Map",
            "",
            "> Auto-generated from Django URL configuration.",
            f"> Generated: {time.strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
            "| URL Pattern | Method | View | Name |",
            "|-------------|--------|------|------|",
        ]

        try:
            from django.urls import get_resolver
            resolver = get_resolver()
            self._walk_resolver(resolver, "", lines)
        except Exception as e:
            self.stderr.write(self.style.ERROR(f"  Error walking URL resolver: {e}"))
            lines.append(f"| Error | — | — | {e} |")

        output = CONTEXT_DIR / "maps" / "endpoint-map.md"
        output.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  → {output.relative_to(BASE_DIR)}"))

    def _walk_resolver(self, resolver, prefix, lines):
        """Recursively walk URL patterns."""
        for pattern in resolver.url_patterns:
            full_pattern = prefix + str(getattr(pattern, "pattern", ""))

            if hasattr(pattern, "url_patterns"):
                # Nested resolver
                self._walk_resolver(pattern, full_pattern, lines)
            else:
                # Leaf pattern
                callback = getattr(pattern, "callback", None)
                view_name = "—"
                if callback:
                    cls = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
                    if cls:
                        view_name = f"`{cls.__module__}.{cls.__name__}`"
                    elif hasattr(callback, "__name__"):
                        view_name = f"`{callback.__module__}.{callback.__name__}`"

                name = getattr(pattern, "name", "—") or "—"
                method = "—"

                # Try to detect allowed methods
                if callback:
                    initkwargs = getattr(callback, "initkwargs", {})
                    if initkwargs:
                        method = ", ".join(
                            m.upper()
                            for m in ("get", "post", "put", "patch", "delete")
                            if m in [k.lower() for k in initkwargs.keys()]
                        ) or "—"

                    # Check view class for http_method_names
                    cls = getattr(callback, "cls", None) or getattr(callback, "view_class", None)
                    if cls and hasattr(cls, "http_method_names") and method == "—":
                        allowed = [
                            m.upper() for m in cls.http_method_names
                            if m != "options" and hasattr(cls, m)
                        ]
                        if allowed:
                            method = ", ".join(allowed)

                lines.append(
                    f"| `/{full_pattern}` | {method} | {view_name} | {name} |"
                )

    # ── Helpers ─────────────────────────────────────────────────

    def _get_project_models(self) -> list:
        """Get all Django models from project apps (not django.contrib)."""
        project_models = []
        for model in apps.get_models(include_auto_created=False):
            module = model.__module__
            if any(module.startswith(p) for p in PROJECT_APP_PREFIXES):
                project_models.append(model)
        return project_models

    def _scan_python_exports(
        self,
        root: Path,
        file_patterns: list[str],
    ) -> dict[str, list[str]]:
        """Scan Python files for class/function definitions and return module-path → exports."""
        import ast

        results: dict[str, list[str]] = {}

        for filepath in sorted(root.rglob("*.py")):
            if any(part in filepath.parts for part in ("__pycache__", "migrations", "venv", "venv312", "tests")):
                continue

            rel = str(filepath.relative_to(BASE_DIR))
            if not any(pat in rel for pat in file_patterns):
                continue

            # Skip __init__.py
            if filepath.name == "__init__.py":
                continue

            try:
                source = filepath.read_text(encoding="utf-8", errors="ignore")
                tree = ast.parse(source)
            except (SyntaxError, UnicodeDecodeError):
                continue

            exports = []
            for node in ast.iter_child_nodes(tree):
                if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                    exports.append(node.name)
                elif isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
                    exports.append(f"{node.name}()")

            if exports:
                # Convert filepath to module path
                module = (
                    str(filepath.relative_to(BASE_DIR))
                    .replace("/", ".")
                    .replace(".py", "")
                )
                results[module] = exports

        return results
