# Generated by Django 5.2.1 on 2025-09-05 02:12

import apps.products.models.item
from django.db import migrations, models, connection


def _prep_tax_code_to_json(apps, schema_editor):
    """Ensure existing textual tax_code values are valid JSON before type cast.

    Legacy values were simple identifiers like 'item_0' which are invalid JSON tokens.
    We wrap any non-empty string value into an object: {"code": <legacy_value>} and
    empty / null values become an empty object {}.
    """
    with connection.cursor() as cursor:
        # Non-empty -> object with code key
        cursor.execute(
            """
            UPDATE products_item
            SET tax_code = json_build_object('code', tax_code)::text
            WHERE tax_code IS NOT NULL AND tax_code <> '' AND tax_code NOT LIKE '{%';
            """
        )
        # Empty / null -> empty object
        cursor.execute(
            """
            UPDATE products_item
            SET tax_code = '{}'
            WHERE tax_code IS NULL OR tax_code = '';
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='default_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='default_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_back_order_allowed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_discountable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_linked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_not_tracked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_pacing',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_print_not',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_serialized',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_tally_by_type',
        ),
        migrations.AddField(
            model_name='item',
            name='flags',
            field=models.JSONField(blank=True, default=apps.products.models.item.default_flags, help_text='Operational flags cluster; replaces legacy boolean columns'),
        ),
    migrations.RunPython(_prep_tax_code_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='tax_code',
            field=models.JSONField(blank=True, default=apps.products.models.item.default_tax, help_text='Tax metadata JSON; includes code/category/rate plus jurisdiction_params stub for localized product-type handling'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'kind', 'security_level'], name='item_active_kind_sec_idx'),
        ),
    ]
