# Generated by Django 5.2.1 on 2025-09-05 02:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_drop_legacy_cost_price_and_flags_json'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='uniq_item_sku_lower'),
        ),
    ]
