# Generated by Django 5.2.1 on 2025-09-05 02:23

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """No-op placeholder: original auto-generated rename to Flow* suppressed.

    We intentionally retained DeliveryVisit / DeliveryLine class names & tables.
    This squashed migration is neutralized to prevent accidental model delete/recreate.
    """

    dependencies = [
        ('orgs', '0001_initial'),
        ('products', '0003_sku_lower_unique_constraint'),
    ]

    operations = []
