# Generated by Django 5.2.1 on 2025-09-05 14:03

import apps.products.models.catalog
import apps.products.models.service
import apps.products.models.usage
import apps.products.models.warehouse
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_delivery_to_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryadjustmentprocessorrun',
            options={'ordering': ('-dt_created',)},
        ),
        migrations.AlterModelOptions(
            name='inventorymetricssnapshot',
            options={'ordering': ('-dt_created',)},
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_sku_lower',
        ),
        migrations.RemoveIndex(
            model_name='inventoryadjustmentprocessorrun',
            name='invproc_run_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymetricssnapshot',
            name='invmet_snapshot_created_idx',
        ),
        migrations.RenameField(
            model_name='inventoryadjustmentprocessorrun',
            old_name='dt_created',
            new_name='dt_created',
        ),
        migrations.RenameField(
            model_name='inventoryadjustmentprocessorrun',
            old_name='dt_finished',
            new_name='dt_finished',
        ),
        migrations.RenameField(
            model_name='inventoryadjustmentprocessorrun',
            old_name='dt_started',
            new_name='dt_started',
        ),
        migrations.RenameField(
            model_name='inventorymetricssnapshot',
            old_name='dt_created',
            new_name='dt_created',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='qty_purchased',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='qty_returned',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='qty_sold',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cost_hourly',
        ),
        migrations.RemoveField(
            model_name='service',
            name='default_minutes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rate_hourly',
        ),
        migrations.RemoveField(
            model_name='service',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='counted_by',
        ),
        migrations.AddField(
            model_name='catalogline',
            name='metrics',
            field=models.JSONField(blank=True, default=apps.products.models.catalog.default_catalog_metrics, help_text='Line-level metrics snapshot (plan/actual/value deltas)'),
        ),
        migrations.AddField(
            model_name='item',
            name='row_version',
            field=models.IntegerField(db_index=True, default=0, help_text='Optimistic concurrency version (increments on each save)'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='metrics',
            field=models.JSONField(blank=True, default=apps.products.models.usage.default_metrics, help_text='Aggregated usage & planning metrics'),
        ),
        migrations.AddField(
            model_name='serial',
            name='site',
            field=models.JSONField(blank=True, default=dict, help_text='Lightweight site/location snapshot (geo codes, address refs)'),
        ),
        migrations.AddField(
            model_name='service',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Actionable steps and status tracking (schema_version key expected)'),
        ),
        migrations.AddField(
            model_name='service',
            name='billing',
            field=models.JSONField(blank=True, default=apps.products.models.service.default_billing, help_text='Billing tiers & travel pricing JSON structure (schema_version, extensions)'),
        ),
        migrations.AddField(
            model_name='service',
            name='billing_audit',
            field=models.JSONField(blank=True, default=list, help_text='Append-only log of billing tier changes'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='Service category or type', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Suggested base duration in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='display',
            field=models.TextField(blank=True, help_text='Rich text / HTML description'),
        ),
        migrations.AddField(
            model_name='service',
            name='purpose',
            field=models.CharField(blank=True, help_text='Intended purpose or audience for this service', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='row_version',
            field=models.PositiveIntegerField(default=0, help_text='Optimistic concurrency version counter'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='count',
            field=models.JSONField(blank=True, default=apps.products.models.warehouse.default_count, help_text='Inventory count snapshot JSON. Schema: {value, aisle, column, shelf, bin, counted_by, counted_by_id, dt_counted(ms epoch), deviation}'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serial_ida',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='service',
            name='process',
            field=models.JSONField(blank=True, default=apps.products.models.service.default_process, help_text='Workflow steps JSON structure'),
        ),
        migrations.AlterField(
            model_name='service',
            name='travel',
            field=models.JSONField(blank=True, default=apps.products.models.service.default_travel_details, help_text='Travel requirement JSON structure'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentprocessorrun',
            index=models.Index(fields=['run_type', 'dt_created'], name='invproc_run_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymetricssnapshot',
            index=models.Index(fields=['dt_created'], name='invmet_snapshot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(django.db.models.functions.text.Lower('sku'), name='item_sku_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'priority'], name='wh_active_priority_idx'),
        ),
    ]
