# Generated by Django 5.2.1 on 2025-09-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_inventoryadjustmentprocessorrun_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorycheck',
            new_name='invchk_org_dt_idx',
            old_name='invchk_org-dt_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorycheck',
            new_name='invchk_cat_dt_idx',
            old_name='invchk_cat-dt_idx',
        ),
        migrations.RenameIndex(
            model_name='seriallog',
            new_name='seriallog_serial_dt_idx',
            old_name='seriallog_serial-dt_idx',
        ),
    ]
