# Generated by Django 5.2.5 on 2025-09-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_billofmaterial_security_level_catalog_security_level_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='item_active_kind_sec_idx',
        ),
        migrations.RemoveIndex(
            model_name='orgitem',
            name='orgitem_org_sec_lvl_idx',
        ),
        migrations.AlterField(
            model_name='item',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'kind'], name='item_active_kind_idx'),
        ),
    ]
