import jsPDF from 'jspdf';
import { Proposal } from '../types/proposalType';
import { ProposalLine } from '../types/proposalLineType';

type ProposalSummary = Pick<Proposal, 'id' | 'status' | 'dt_created' | 'dt_modified'> & {
  ida?: Proposal['ida'];
};

interface ProposalPdfData {
  proposal: ProposalSummary;
  lines: Array<Partial<ProposalLine>>;
  customerName?: string;
  vendorName?: string;
}

export const generateProposalPdf = (data: ProposalPdfData): void => {
  const { proposal, lines, customerName, vendorName } = data;

  // Create new PDF document
  const doc = new jsPDF();

  // Set font
  doc.setFont('helvetica');

  // Company header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('WebClerk', 20, 30);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Proposal Document', 20, 40);

  // Proposal details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Proposal Details', 20, 60);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  let yPos = 75;

  doc.text(`Proposal ID: ${proposal.ida || proposal.id}`, 20, yPos);
  yPos += 8;
  doc.text(`Status: ${proposal.status}`, 20, yPos);
  yPos += 8;
  doc.text(`Customer: ${customerName || 'Not specified'}`, 20, yPos);
  yPos += 8;
  if (vendorName) {
    doc.text(`Vendor: ${vendorName}`, 20, yPos);
    yPos += 8;
  }
  doc.text(`Created: ${new Date(proposal.dt_created).toLocaleDateString()}`, 20, yPos);
  yPos += 8;
  doc.text(`Modified: ${new Date(proposal.dt_modified).toLocaleDateString()}`, 20, yPos);
  yPos += 15;

  // Line items table
  if (lines.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Line Items', 20, yPos);
    yPos += 10;

    // Table headers
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Item', 20, yPos);
    doc.text('Description', 60, yPos);
    doc.text('Qty', 140, yPos);
    doc.text('Price', 160, yPos);
    doc.text('Total', 180, yPos);
    yPos += 5;

    // Header line
    doc.line(20, yPos, 190, yPos);
    yPos += 8;

    // Table rows
    doc.setFont('helvetica', 'normal');
    lines.forEach((line) => {
      if (yPos > 270) { // Check if we need a new page
        doc.addPage();
        yPos = 30;
      }

      const itemName = line.item?.ida_item || 'Unknown';
      const description = line.item?.description || '';
      const quantity = line.quantity?.ordered || 0;
      const price = line.price?.unit || 0;
      const total = line.price?.extended || (quantity * price);

      // Truncate long text
      const truncatedItem = itemName.length > 15 ? itemName.substring(0, 15) + '...' : itemName;
      const truncatedDesc = description.length > 25 ? description.substring(0, 25) + '...' : description;

      doc.text(truncatedItem, 20, yPos);
      doc.text(truncatedDesc, 60, yPos);
      doc.text(quantity.toString(), 140, yPos);
      doc.text(`$${price.toFixed(2)}`, 160, yPos);
      doc.text(`$${total.toFixed(2)}`, 180, yPos);

      yPos += 8;
    });

    yPos += 5;

    // Totals section
    if (yPos > 250) {
      doc.addPage();
      yPos = 30;
    }

    doc.setFont('helvetica', 'bold');
    doc.line(140, yPos, 190, yPos);
    yPos += 8;

    // Calculate totals
    const subtotal = lines.reduce((sum, line) => sum + (line.price?.extended || 0), 0);
    const totalDiscount = lines.reduce((sum, line) => sum + (line.price?.discount_amount || 0), 0);
    const grandTotal = subtotal - totalDiscount;

    doc.text('Subtotal:', 140, yPos);
    doc.text(`$${subtotal.toFixed(2)}`, 180, yPos);
    yPos += 8;

    if (totalDiscount > 0) {
      doc.text('Discount:', 140, yPos);
      doc.text(`-$${totalDiscount.toFixed(2)}`, 180, yPos);
      yPos += 8;
    }

    doc.setFontSize(12);
    doc.text('Total:', 140, yPos);
    doc.text(`$${grandTotal.toFixed(2)}`, 180, yPos);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Page ${i} of ${pageCount}`, 20, 285);
    doc.text('Generated by WebClerk', 150, 285);
  }

  // Download the PDF
  const fileName = `Proposal_${proposal.ida || proposal.id}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};