# Generated by Django 5.2.5 on 2025-09-04 04:33

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_type', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('full', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('number', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('country_code', models.CharField(blank=True, help_text='Country code (e.g., +1)', max_length=5)),
                ('format', models.CharField(blank=True, help_text='Formatted phone number', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Display name for this phone', max_length=100)),
                ('attention', models.CharField(blank=True, help_text='Person or department attention line', max_length=100)),
                ('opt_out', models.BooleanField(default=False, help_text='Opted out of communications')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('path', models.CharField(blank=True, db_index=True, help_text='URL or handle (indexed)', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('other', 'Other')], db_index=True, max_length=50)),
                ('comment', models.TextField(blank=True, default='', help_text='General notes')),
                ('status', models.CharField(blank=True, db_index=True, default='active', max_length=30)),
                ('security_level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0, help_text='Custom ordering value')),
                ('count_accessed', models.PositiveIntegerField(default=0, help_text='Access counter')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'domains',
                'indexes': [models.Index(fields=['path'], name='domains_path_ffbbee_idx'), models.Index(fields=['type', 'status'], name='domains_type_f03f00_idx'), models.Index(fields=['security_level'], name='domains_securit_9bda51_idx')],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Display name for this email', max_length=100)),
                ('attention', models.CharField(blank=True, help_text='Person or department attention line', max_length=100)),
                ('type', models.CharField(blank=True, help_text='Type of email (e.g., work, personal)', max_length=50)),
                ('opt_out', models.CharField(blank=True, choices=[('', 'Active'), ('opted_out', 'Opted Out'), ('bounced', 'Bounced'), ('invalid', 'Invalid'), ('spam_complaint', 'Spam Complaint')], default='', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary email address')),
                ('is_verified', models.BooleanField(default=False, help_text='Email has been verified')),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
                'db_table': 'emails',
                'indexes': [models.Index(fields=['email'], name='emails_email_b814fb_idx'), models.Index(fields=['is_primary'], name='emails_is_prim_2479c4_idx'), models.Index(fields=['opt_out'], name='emails_opt_out_e796bc_idx')],
            },
        ),
    ]
