# Generated by Django 5.2.5 on 2025-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='count_accessed',
            field=models.PositiveIntegerField(default=0, help_text='Access counter'),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='security_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Custom ordering value'),
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='domain',
            name='path',
            field=models.CharField(blank=True, db_index=True, help_text='URL or handle (indexed)', max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['path'], name='domains_path_ffbbee_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['type', 'status'], name='domains_type_f03f00_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['security_level'], name='domains_securit_9bda51_idx'),
        ),
    ]
