# Generated by Django 5.2.5 on 2025-08-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='email',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
        migrations.AddField(
            model_name='phone',
            name='ida',
            field=models.CharField(blank=True, help_text='Alternate ID for external systems', max_length=40),
        ),
    ]
