# Generated by Django 5.2.8 on 2025-12-22 15:26

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        # Rename the historic `Location` model to `Address` at the state level
        # so we keep the existing `locations` DB table instead of attempting
        # to create it again (which causes duplicate-table errors).
        migrations.RenameModel(
            old_name='Location',
            new_name='Address',
        ),
        # Keep table name as 'locations' via model Meta on the Address model.
    ]
