# Generated by Django 5.2.5 on 2025-09-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_email_security_level_location_security_level_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='domain',
            name='domains_securit_9bda51_idx',
        ),
        migrations.AlterField(
            model_name='domain',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
