# Generated by Django 5.2.8 on 2025-12-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_address_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
