# Generated by Django 5.2.5 on 2025-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_domain_uuid_alter_email_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='email',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='location',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='phone',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
