# Generated by Django 5.2.8 on 2026-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_address_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('active', 'Active'), ('verifying', 'Verifying'), ('suspended', 'Suspended'), ('retired', 'Retired')], db_index=True, default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('other', 'Other')], db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('work', 'Work'), ('personal', 'Personal'), ('support', 'Support'), ('billing', 'Billing'), ('other', 'Other')], default='', help_text='Type of email (e.g., work, personal)', max_length=50),
        ),
    ]
