# Generated by Django 5.2.8 on 2026-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_add_is_locked_to_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='domain',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='email',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='phone',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
