# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_address_is_locked_domain_is_locked_email_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_locked',
        ),
    ]
