# Generated by Django 5.2.8 on 2026-08-12 02:31

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_add_commission_line_type_and_function_category'),
        ('core', '0038_rename_predicted_impact_to_impact_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('channel', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('visit', 'Visit'), ('text', 'Text/SMS'), ('meeting', 'Meeting')], db_index=True, help_text='Communication channel: call, email, visit, text, meeting', max_length=10)),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], db_index=True, default='out', help_text='Inbound or outbound', max_length=3)),
                ('subject', models.CharField(blank=True, help_text="Brief description — e.g. 'Discussed pricing'", max_length=255)),
                ('summary', models.TextField(blank=True, help_text='What happened, what was said, next steps')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (mainly for calls)', null=True)),
                ('email_message_id', models.CharField(blank=True, help_text='Email Message-ID header — paste from email program for cross-reference', max_length=255)),
                ('project_id', models.BigIntegerField(blank=True, db_index=True, help_text='Project this touch relates to', null=True)),
                ('logged_by', models.BigIntegerField(db_index=True, default=0, help_text='Contact ID of who recorded this touch')),
                ('action', models.ForeignKey(blank=True, help_text='Action that triggered this touch (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touches', to='core.action')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact who was touched', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Touch',
                'verbose_name_plural': 'Touches',
                'db_table': 'touches',
                'ordering': ['-dt_created'],
                'indexes': [models.Index(fields=['contact'], name='touches_contact_87df9b_idx'), models.Index(fields=['channel'], name='touches_channel_19377a_idx'), models.Index(fields=['direction'], name='touches_directi_ff989e_idx'), models.Index(fields=['-dt_created'], name='touches_dt_crea_8dd2e2_idx'), models.Index(fields=['action'], name='touches_action__9078d2_idx')],
            },
        ),
    ]
