# Generated by Django 5.2.8 on 2026-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_add_touch_org_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address3',
            field=models.CharField(blank=True, help_text='Third address line (international addresses, c/o, building wing)', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, help_text='County, district, borough, arrondissement — sub-region within state/province', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_name',
            field=models.CharField(blank=True, help_text='Neighborhood, ward, post office name — used in JP, KR, IN, BR addressing', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (US, GB, DE, JP, etc.)', max_length=2),
        ),
    ]
