# Generated by Django 5.2.8 on 2026-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_add_address3_district_postal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='impact',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Rep judgment of touch importance, 1-5 (0 = not rated)'),
        ),
        migrations.AddField(
            model_name='touch',
            name='outcome',
            field=models.CharField(blank=True, choices=[('connected', 'Connected'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer'), ('bounced', 'Bounced'), ('rescheduled', 'Rescheduled')], db_index=True, help_text='What happened: connected, voicemail, no_answer, bounced, rescheduled', max_length=12),
        ),
        migrations.AddField(
            model_name='touch',
            name='plan',
            field=models.JSONField(blank=True, default=list, help_text='Sequence of planned future touches: [{step, channel, when, note, done}]'),
        ),
    ]
