# Generated by Django 5.2.8 on 2026-08-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_add_touch_outcome_impact_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='linkage_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Linkage group — ties touch to the transaction graph (proposal→order→invoice)', null=True),
        ),
    ]
