# Generated by Django 5.2.8 on 2026-08-28 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_orgbase_status'),
        ('transactions', '0003_alter_invoice_status_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_payment_gateway_intent',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_contact_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id_gateway_payment_intent',
            new_name='gateway_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id_gateway_transaction',
            new_name='gateway_transaction_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='id_contact',
            new_name='contact_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_parent',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', help_text='Parent project for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='transactions.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['contact_id'], name='project_contact_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_intent_id', ''), _negated=True), fields=('gateway_payment_intent_id',), name='uniq_payment_gateway_intent'),
        ),
    ]
