# Generated by Django 5.2.8 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_id_prefix_to_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contact',
        ),
        migrations.AddField(
            model_name='payment',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — payment survives contact deletion)', null=True),
        ),
    ]
