# Generated by Django 5.2.8 on 2026-03-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_invoice_is_locked_remove_order_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
    ]
