# Generated by Django 5.2.8 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_is_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
    ]
