# Generated by Django 5.2.8 on 2026-06-29 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_is_locked_to_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, db_column='purchase_id', help_text='Purchase this payment applies to (AP — disbursed)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('received', 'Received'), ('disbursed', 'Disbursed')], db_index=True, default='received', help_text='Direction: received (AR, money in) or disbursed (AP, money out)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(db_column='contact_id', help_text='Contact who made or received the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', help_text='Invoice this payment applies to (AR — received)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.invoice'),
        ),
    ]
