# Generated by Django 5.2.8 on 2026-07-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_add_commission_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='data',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='commission',
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='commission',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='PendingPaymentApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('request_ref', models.JSONField(blank=True, default=dict)),
                ('dt_applied', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=120)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payments', to='transactions.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_applications', to='transactions.payment')),
            ],
            options={
                'db_table': 'pending_payment_applications',
                'indexes': [models.Index(fields=['state'], name='pendpay_state_idx'), models.Index(fields=['invoice', 'state'], name='pendpay_inv_state_idx')],
            },
        ),
    ]
