# Generated by Django 5.2.8 on 2026-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_purchase_capital_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, is_individual, attention, email, phone, domain, notes}'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, is_individual, attention, email, phone, domain, notes}'),
        ),
        migrations.AddField(
            model_name='order',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, is_individual, attention, email, phone, domain, notes}'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, is_individual, attention, email, phone, domain, notes}'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workorder',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, is_individual, attention, email, phone, domain, notes}'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workorder',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='probability',
            field=models.FloatField(db_index=True, default=0.0, help_text='Close probability 0.0–1.0. Feeds forecast: totals × probability = weighted pipeline.'),
        ),
    ]
