# Generated by Django 5.2.8 on 2026-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_stage1_invoice_type_payment_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='proposal',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='purchase',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
    ]
