# Generated by Django 5.2.8 on 2026-09-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_payment_customer_remove_payment_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashentry',
            name='notes',
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive=cash in, negative=cash out. SUM(amount) = net cash position.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='purchase',
            field=models.ForeignKey(blank=True, db_column='purchase_id', help_text='Purchase order this payment relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.purchase'),
        ),
    ]
