# Generated by Django 5.2.8 on 2026-09-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_fk_to_values'),
        ('transactions', '0012_remove_cashentry_notes_alter_cashentry_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashEntry',
            new_name='Cash',
        ),
    ]
