# Generated by Django 5.2.8 on 2026-07-30 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_invoice_config_invoiceline_config_order_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dt_end',
            field=models.BigIntegerField(default=0, help_text='Project end date (epoch ms)'),
        ),
        migrations.AddField(
            model_name='project',
            name='dt_start',
            field=models.BigIntegerField(default=0, help_text='Project start date (epoch ms)'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_parent',
            field=models.ForeignKey(blank=True, db_column='id_parent', help_text='Parent project for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='transactions.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='percent_complete',
            field=models.IntegerField(default=0, help_text='0-100 completion percentage'),
        ),
    ]
