# Generated by Django 5.2.8 on 2026-09-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_rename_cashentry_cash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
