# Generated by Django 5.2.8 on 2026-09-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_erosion_notes_alter_budget_account_debit_and_more'),
        ('orgs', '0005_retire_payment_term_repoint_to_term'),
        ('transactions', '0014_retire_payment_method_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='payment_term',
            field=models.ForeignKey(blank=True, db_column='paymentterm_id', help_text='Payment term applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='order',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
