# Generated by Django 5.2.8 on 2026-07-31 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_payment_nullable_for_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dt_payment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date the payment was made', null=True),
        ),
    ]
