# Generated by Django 5.2.8 on 2026-09-17 04:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cash_rename'),
        ('orgs', '0005_retire_payment_term_repoint_to_term'),
        ('transactions', '0017_delete_payment_applications'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cash',
            name='uniq_payment_gateway_intent',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='dt_payment',
            new_name='dt_cash',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='payment_term',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='statementline',
            old_name='payment_id',
            new_name='cash_id',
        ),
        migrations.AlterField(
            model_name='cash',
            name='dt_cash',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date the cash moved', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='term',
            field=models.ForeignKey(blank=True, db_column='term_id', help_text='Term applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='accounts.term'),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='cash_id',
            field=models.BigIntegerField(blank=True, help_text='Cash record ID created from this line', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — cash survives contact deletion)', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', help_text='Customer org — received cash_entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries_as_customer', to='orgs.orgbase'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='dt_processed',
            field=models.DateTimeField(blank=True, help_text='When the cash was processed by gateway', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='dt_reconciliation',
            field=models.DateTimeField(blank=True, help_text='When the cash was reconciled', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='gateway',
            field=models.CharField(choices=[('', '---------'), ('manual', 'Manual'), ('spreedly', 'Spreedly')], default='manual', help_text='Cash gateway used', max_length=20),
        ),
        migrations.AlterField(
            model_name='cash',
            name='gateway_payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment intent ID from Stripe or equivalent', max_length=255),
        ),
        migrations.AlterField(
            model_name='cash',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw response from cash gateway', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from the cash gateway', max_length=255),
        ),
        migrations.AlterField(
            model_name='cash',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', help_text='Invoice this cash applies to (AR — received)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='transactions.invoice'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the document where this cash was entered (order, invoice, customer)', null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='purchase',
            field=models.ForeignKey(blank=True, db_column='purchase_id', help_text='Purchase order this cash relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='transactions.purchase'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='receipt',
            field=models.ForeignKey(blank=True, db_column='receipt_id', help_text='Receipt this cash applies to (AP — cash_out)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='transactions.receipt'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='reconciled',
            field=models.BooleanField(default=False, help_text='Whether this cash has been reconciled'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Vendor org — expense cash_entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Cash history and balances', null=True),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='category',
            field=models.CharField(blank=True, help_text='Expense category — same select list as Cash.category', max_length=100),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='promoted',
            field=models.BooleanField(db_index=True, default=False, help_text='True = already created a Cash record from this line'),
        ),
        migrations.AddConstraint(
            model_name='cash',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_intent_id', ''), _negated=True), fields=('gateway_payment_intent_id',), name='uniq_cash_gateway_intent'),
        ),

        migrations.AlterField(
            model_name='cash',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', help_text='Customer org — cash received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries_as_customer', to='orgs.orgbase'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Vendor org — cash paid out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries_as_vendor', to='orgs.orgbase'),
        ),
    ]
