# Generated by Django 5.2.8 on 2026-09-17 05:06
# Schema only. Data backfill is 0022 — Postgres cannot create the indexes
# in the same transaction after rows were updated (pending trigger events).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_customer_facing_payment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='parent_line_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
