# Generated by Django 5.2.8 on 2026-09-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_line_parent_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='sell',
        ),
    ]
