# Generated by Django 5.2.8 on 2026-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_statement_line_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='dt_due',
            field=models.BigIntegerField(blank=True, help_text='Proposal expiry date (epoch ms) — quote valid until this date', null=True),
        ),
    ]
