# Generated by Django 5.2.8 on 2026-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_rename_proposal_to_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dt_due',
            field=models.BigIntegerField(blank=True, help_text='Quote expiry date (epoch ms) — quote valid until this date', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
    ]
