# Generated by Django 5.2.8 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_purpose_to_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='order',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='payment',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='pendingpaymentapplication',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='project',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
    ]
