# Generated by Django 5.2.8 on 2026-09-19 23:43

import apps.transactions.models.base_transaction_model
import apps.transactions.models.receipt
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """A receipt is a transaction now: it carries its vendor, terms and parent itself,
    taken from the purchase it belongs to (Bill, 2026-09-19)."""
    with schema_editor.connection.cursor() as cur:
        cur.execute("""
            update receipt r
               set vendor_id = p.vendor_id,
                   terms = p.terms,
                   terms_id = p.terms_id,
                   contact_id = p.contact_id,
                   parent_id = p.id,
                   parent_model = 'purchase'
              from purchases p
             where r.purchase_id = p.id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_erosion_parent_model_and_more'),
        ('orgs', '0005_retire_payment_term_repoint_to_term'),
        ('transactions', '0031_clear_stale_line_tax_rates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='addresses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='allocations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.AddField(
                model_name='receipt',
                name='commission',
                field=models.JSONField(blank=True, default=dict, null=True),
            ),
            ],
            database_operations=[
                # wc_demo already had this column from an older migration; a fresh
                # database does not. IF NOT EXISTS covers both.
                migrations.RunSQL(
                    sql='alter table receipt add column if not exists commission jsonb null',
                    reverse_sql='alter table receipt drop column if exists commission',
                ),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='conditions_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='conditions_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='emails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='flow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False, help_text='Order placed by manufacturer for commission'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='phones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price_level',
            field=models.CharField(blank=True, default='retail', max_length=30),
        ),
        migrations.AddField(
            model_name='receipt',
            name='priority',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shipping',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_shipping, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='How this transaction originated: Facebook, Referral, Walk-in, Trade Show, etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='receipt',
            name='terms',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='accounts.term'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Counterparty snapshot: {id, ida, name, contact_id, attention, full_address, phone, email, domain, is_individual}'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.receipt.default_receipt_totals, help_text='Σ line totals plus the AP leaves: total, freight, duty, handling, vat, paid, balance', null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
