# Generated by Django 5.2.8 on 2026-08-10 22:40

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_project_gantt_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='paymentapplication',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='paymentapplication',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
    ]
