# Generated by Django 5.2.8 on 2026-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_add_payment_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Change returned. tendered - amount when tendered > amount.', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tendered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount physically tendered (cash scenarios). May exceed amount.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount remaining to apply. Starts = amount, decremented as applied to invoices.', max_digits=15),
        ),
    ]
