# Generated by Django 5.2.8 on 2026-09-20 01:27

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_delivery_inventory_check'),
        ('transactions', '0034_receipt_line_parent_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='source_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('inventory_adjustment', 'Inventory Adjustment')], db_index=True, default='purchase_receipt', help_text='Type of receiving transaction', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkOrderCompletion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('line_number', models.IntegerField(db_index=True, default=0)),
                ('line_type', models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge')], db_index=True, default='product', max_length=20)),
                ('price_level', models.CharField(blank=True, db_column='price_level', max_length=50, null=True)),
                ('parent_line_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('item', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.JSONField(blank=True, default=dict, null=True)),
                ('cost', models.JSONField(blank=True, default=dict, null=True)),
                ('commission', models.JSONField(blank=True, default=dict, null=True)),
                ('tax', models.JSONField(blank=True, default=dict, null=True)),
                ('physical', models.JSONField(blank=True, default=dict, null=True)),
                ('totals', models.JSONField(blank=True, default=dict, null=True)),
                ('lot', models.CharField(blank=True, help_text='Lot number', max_length=100)),
                ('serial_batch', models.CharField(blank=True, help_text='Serial or batch number', max_length=100)),
                ('inventory_layer', models.ForeignKey(blank=True, help_text='Inventory layer created for this completion (FIFO/LIFO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_completions', to='products.inventorylayer')),
                ('item_fk', models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse the produced goods entered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_completions', to='products.warehouse')),
                ('workorder', models.ForeignKey(db_column='workorder_id', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='transactions.workorder')),
            ],
            options={
                'db_table': 'workorder_completion',
                'indexes': [models.Index(fields=['workorder', 'warehouse'], name='workorder_c_workord_55cca3_idx')],
            },
        ),
    ]
