# Generated by Django 5.2.8 on 2026-09-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_workorder_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='kind',
            field=models.CharField(choices=[('production', 'Production'), ('count', 'Count')], db_index=True, default='production', help_text='production — material becomes stock; count — an inventory audit', max_length=20),
        ),
    ]
