# Generated by Django 5.2.8 on 2026-09-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_line_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
        migrations.AddField(
            model_name='order',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
        migrations.AddField(
            model_name='quote',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='events',
            field=models.JSONField(blank=True, default=list, help_text='Append-only record of what happened to this document'),
        ),
    ]
