# Generated by Django 5.2.8 on 2026-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_record_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attention_rep',
            field=models.CharField(blank=True, help_text='The person at the rep', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Rep org credited with this document', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='attention_rep',
            field=models.CharField(blank=True, help_text='The person at the rep', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Rep org credited with this document', null=True),
        ),
    ]
