# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_landed_method_per_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='receiptline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='requisitionline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='statementline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='workorderline',
            name='is_deleted',
        ),
    ]
