# Generated by Django 5.2.8 on 2026-09-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_remove_cash_is_deleted_remove_invoice_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', help_text="Invoice this cash applies to (AR — received). SET_NULL: deleting an invoice reverses its applications and the money returns to available; CASCADE deleted the customer's cash with the document.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='transactions.invoice'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='purchase',
            field=models.ForeignKey(blank=True, db_column='purchase_id', help_text='Purchase order this cash relates to. SET_NULL, as invoice: a cash record is money, and a document delete never deletes money.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='transactions.purchase'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='receipt',
            field=models.ForeignKey(blank=True, db_column='receipt_id', help_text='Receipt this cash applies to (AP — cash_out). SET_NULL, as invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='transactions.receipt'),
        ),
    ]
