# Generated by Django 5.2.8 on 2026-09-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_cash_fk_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attention_rep',
            field=models.CharField(blank=True, help_text='The person at the rep', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Rep org credited with this sale', null=True),
        ),
    ]
