# Generated by Django 5.2.8 on 2026-09-24 02:31

from django.db import migrations, models

# Existing lines take their party ids from their headers (Bill, 2026-09-23). From here on the
# line save stamps them and the header save cascades them.
BACKFILL = """
UPDATE quote_lines l SET customer_id = h.customer_id, rep_id = h.rep_id
  FROM quotes h WHERE l.quote_id = h.id;
UPDATE order_lines l SET customer_id = h.customer_id, rep_id = h.rep_id
  FROM orders h WHERE l.order_id = h.id;
UPDATE invoice_lines l SET customer_id = h.customer_id, rep_id = h.rep_id
  FROM invoices h WHERE l.invoice_id = h.id;
UPDATE purchase_lines l SET vendor_id = h.vendor_id
  FROM purchases h WHERE l.purchase_id = h.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_invoice_rep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="The header's customer (derived)", null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The rep who made the sale (derived from the header)', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="The header's customer (derived)", null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The rep who made the sale (derived from the header)', null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='vendor_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="The purchase's vendor (derived)", null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="The header's customer (derived)", null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='The rep who made the sale (derived from the header)', null=True),
        ),
        migrations.RunSQL(BACKFILL, reverse_sql=migrations.RunSQL.noop),
    ]
