# Generated by Django 5.2.8 on 2026-09-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_line_party_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact responsible for this line', null=True),
        ),
    ]
