# Generated by Django 5.2.8 on 2026-09-27 01:01

import apps.transactions.models.base_line_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_comments_flat_default'),
        ('transactions', '0044_comments_flat_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='events',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_line_model.default_events, help_text='What happened to this line: one event per Pending applied to it'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='events',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_line_model.default_events, help_text='What happened to this line: one event per Pending applied to it'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='inventory_layer',
            field=models.ForeignKey(blank=True, help_text='Layer created for stock this line found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_lines', to='products.inventorylayer'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='events',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_line_model.default_events, help_text='What happened to this line: one event per Pending applied to it'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust')], db_index=True, default='product', max_length=20),
        ),
    ]
