# Generated by Django 5.2.8 on 2026-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_stock_line_events_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('commission', 'Commission'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('finance_charge', 'Finance Charge'), ('count', 'Count'), ('adjust', 'Adjust'), ('build', 'Build'), ('consume', 'Consume'), ('scrap', 'Scrap')], db_index=True, default='product', max_length=20),
        ),
    ]
