# Generated by Django 5.2.8 on 2026-09-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_workorder_line_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        # A cash journalized before today carried only is_locked. Its mark becomes the first GL
        # posting's time; a zero-amount cash (auto-completed, no GL) takes dt_processed, else
        # dt_modified. is_locked itself goes in a later migration.
        migrations.RunSQL(
            sql="""
                UPDATE transactions_cash c SET dt_journaled = COALESCE(
                    (SELECT MIN(g.dt_created) FROM gl_journals g
                      WHERE g.source_model = 'cash' AND g.source_id = c.id),
                    (EXTRACT(EPOCH FROM c.dt_processed) * 1000)::bigint,
                    c.dt_modified)
                WHERE c.is_locked
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
