# Generated by Django 5.2.8 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='linkageentry',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
    ]
