# Generated by Django 5.2.8 on 2026-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_document_status_alter_linkageentry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, help_text="Model this document is linked to (e.g. 'invoice', 'item', 'contact')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='record_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="PK of the linked record in model_name's table", null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['model_name', 'record_id'], name='doc_model_record_idx'),
        ),
    ]
