# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_copyright_to_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='linkageentry',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_deleted',
        ),
    ]
