# Generated by Django 5.2.8 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='linkageentry',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
    ]
