# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_target_model_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='linkageentry',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_locked',
        ),
    ]
