# Generated by Django 5.2.8 on 2026-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_linkageentry_config_questionanswer_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Document type: team_memory, readme, spec, report, template, etc.', max_length=255, null=True),
        ),
    ]
