# Generated by Django 5.2.8 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_add_dt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='document',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='linkageentry',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='linkageentry',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='tag',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='tag',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
    ]
