export const staticLists = {
  companyLatLng: [['lat', '38.7634288'], ['lng', '-92.4900556']],
  aQAType: [
    ['Dryer-Vent', 'Dryer-Vent'],
    ['Gas-Service-Call', 'Gas-Service-Call'],
    ['Inspection-Level-2', 'Inspection-Level-2'],
    ['Job-Setup', 'Job-Setup'],
    ['Pellet-Stove', 'Pellet-Stove']
  ],
  aQACustomer: [['Site-Inspection', 'Site-Inspection']],
  aTaxJuris: [],
  aDataCheckBox: [['Yes', 'yes'], ['No', 'no']],
  aNameID: [],
  aActions: [],
  aActionsOrders: [],
  aActionsInvoices: [],
  aActionsProposals: [],
  aActionsPOs: [],
  aTerms: [],
  aNeed: [],
  aSaleJurisSources: [
    ['Distributor', 'Distributor'],
    ['Retail', 'Retail'],
    ['Subcontract', 'Subcontract'],
    ['TrucktoCustomer', 'TrucktoCustomer'],
    ['TrucktoTruck', 'TrucktoTruck'],
    ['Wholesale', 'Wholesale']
  ],
  aStatus: [],
  aContractDetail: [],
  aAdSource: [],
  aTypeSale: [],
  aReps: [],
  aDataTrueFalse: [['true', 'true'], ['false', 'false']],
  aUseType: [['UseType', 'Reprints', 'WebPrints', 'Book', 'NewsLetter']],
  ajobList: [
    ['Job Class', 'Job Class'],
    ['*Estimate Job', '*Estimate Job'],
    ['*Sweeps Service', '*Sweeps Service'],
    ['Attic Insulation Shield/FS', 'Attic Insulation Shield/FS'],
    ['Chase Cover', 'Chase Cover'],
    ['Chimney Caps', 'Chimney Caps'],
    ['Class A Install', 'Class A Install'],
    ['Class B Install', 'Class B Install'],
    ['Firebox Repairs', 'Firebox Repairs'],
    ['FireStop Install', 'FireStop Install'],
    ['Flashings/Crickets', 'Flashings/Crickets'],
    ['Gas Insert', 'Gas Insert'],
    ['Gas Log Installs', 'Gas Log Installs'],
    ['Gas Stove', 'Gas Stove'],
    ['level Three Inspect', 'level Three Inspect'],
    ['New Const Gas FP', 'New Const Gas FP'],
    ['New Const Masonry', 'New Const Masonry'],
    ['New Const Wood FP', 'New Const Wood FP'],
    ['Pellet Insert', 'Pellet Insert'],
    ['Pellet Stove', 'Pellet Stove'],
    ['Plaster & Paint', 'Plaster & Paint'],
    ['R&R Brick Chimneys', 'R&R Brick Chimneys'],
    ['R&R Gas FP', 'R&R Gas FP'],
    ['R&R Wood Chases', 'R&R Wood Chases'],
    ['R&R Wood FP', 'R&R Wood FP'],
    ['Recrown', 'Recrown'],
    ['Reface FirePlace', 'Reface FirePlace'],
    ['Reline Gas', 'Reline Gas'],
    ['Reline Wood', 'Reline Wood'],
    ['Run Gas Line', 'Run Gas Line'],
    ['Water Repellant', 'Water Repellant'],
    ['Wood Insert', 'Wood Insert'],
    ['Wood Stove', 'Wood Stove']
  ],
  aImportance: [
    ['Emergency', 'Emergency'],
    ['High', 'High'],
    ['Medium', 'Medium'],
    ['Low', 'Low'],
    ['Objective', 'Objective']
  ],
  aStates: [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI",
    "ID", "IN", "IL", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN",
    "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
    "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA",
    "WV", "WI", "WY"
  ],
  usersColors: {
    Dale: "Blue",
    Omie: "Red",
    Cameron: "Green",
    Cedar: "Yellow",
    Dawn: "Brown",
    Jeff: "Indigo",
    Matt: "Gray"
  }
};

export default staticLists;