# Generated by Django 5.2.5 on 2025-09-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='dt_processed',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='purpose',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
