# Generated by Django 5.2.5 on 2025-09-07 19:22

from django.db import migrations
from django.db.migrations.operations.models import RenameIndex


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]
    operations = [
        RenameIndex(
            model_name='pending',
            new_name='pending_model_n_2705f6_idx',
            old_name='pending_model_na_8a7f2c_idx',
        ),
    ]
