# Generated by Django 5.2.8 on 2026-02-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('orgs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', help_text='Associated customer org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', help_text='Associated employee org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_employee', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='contact',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', help_text='Associated manufacturer org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='rep',
            field=models.ForeignKey(blank=True, db_column='rep_id', help_text='Associated sales rep org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_rep', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='contact',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Associated vendor org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='action',
            name='parent_action',
            field=models.ForeignKey(blank=True, db_column='action_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.action', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['model_name'], name='pending_model_n_2705f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['record_id'], name='pending_record__e5e38e_idx'),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['dt_processed'], name='pending_dt_proc_dc4dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='refsmismatchlog',
            index=models.Index(fields=['parent_model', 'dt_created'], name='refs_mismat_parent__cb5b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='refsmismatchlog',
            index=models.Index(fields=['related_model', 'dt_created'], name='refs_mismat_related_921be2_idx'),
        ),
        migrations.AddIndex(
            model_name='refsmismatchlog',
            index=models.Index(fields=['mismatch_type', 'dt_created'], name='refs_mismat_mismatc_846afa_idx'),
        ),
        migrations.AddField(
            model_name='softdeleteledger',
            name='content_type',
            field=models.ForeignKey(db_column='contenttype_id', on_delete=django.db.models.deletion.CASCADE, related_name='soft_delete_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='audit_logs_model_n_b007a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'dt_created'], name='audit_logs_user_id_2a37be_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'dt_created'], name='audit_logs_action_10d55c_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteledger',
            index=models.Index(fields=['dt_purge'], name='core_softde_dt_purg_1e3877_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteledger',
            index=models.Index(fields=['content_type', 'object_id'], name='core_softde_content_556e49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='softdeleteledger',
            unique_together={('content_type', 'object_id')},
        ),
    ]
