# Generated by Django 5.2.5 on 2025-09-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeleteLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('purge_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_delete_entries', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['purge_at'], name='core_softde_purge_a_3bb3e0_idx'), models.Index(fields=['content_type', 'object_id'], name='core_softde_content_b722e6_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
