# Generated by Django 5.2.5 on 2025-08-29 22:35

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='pending',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Denormalized created timestamp (ms UTC)'),
        ),
        migrations.AddField(
            model_name='pending',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='pending',
            name='ida',
            field=models.CharField(blank=True, db_index=True, help_text='Alternate ID for external systems (indexed)', max_length=40),
        ),
        migrations.AddField(
            model_name='pending',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pending',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pending',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Denormalized modified timestamp (ms UTC)'),
        ),
        migrations.AddField(
            model_name='pending',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pending',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented on each successful save'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='data',
            field=models.JSONField(default=common.models.default_data, help_text='Arbitrary payload awaiting processing'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='dt_processed',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Processing timestamp ms (0 = not processed)'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='record_id',
            field=models.CharField(blank=True, help_text='Target record ID (string form)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='table_name',
            field=models.CharField(blank=True, help_text='Target model/table this pending record relates to', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['table_name'], name='pending_table_n_b8acef_idx'),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['record_id'], name='pending_record__e5e38e_idx'),
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['dt_processed'], name='pending_dt_proc_dc4dfc_idx'),
        ),
    ]
