# Generated by Django 5.2.5 on 2025-08-24 03:03

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pending_uuid_action_ida_contact_ida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='contact',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='setting',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
        migrations.AddField(
            model_name='template',
            name='comments',
            field=models.JSONField(default=common.models.default_prefs, help_text='User comments and notes'),
        ),
    ]
