# Generated by Django 5.2.8 on 2026-02-22 14:58

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('source', models.CharField(choices=[('r25', 'React2025 Frontend'), ('wc3', 'WebClerk3 Internal'), ('ext', 'External Service')], help_text='System that initiated the request', max_length=10)),
                ('destination', models.CharField(help_text="Target system (e.g., 'wc3', 'shipstation', 'quickbooks', 'stripe')", max_length=100)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=500)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Request headers (sensitive data should be redacted)')),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Request body/payload')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Response headers')),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Response body (may be truncated for large responses)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='UUID to link related requests across systems', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (model_name, record_id, etc.)')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', help_text='User who triggered the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_logs',
                'indexes': [models.Index(fields=['source', 'dt_created'], name='api_logs_source_544397_idx'), models.Index(fields=['destination', 'dt_created'], name='api_logs_destina_7c1aa6_idx'), models.Index(fields=['endpoint', 'status_code'], name='api_logs_endpoin_93eabc_idx'), models.Index(fields=['correlation_id'], name='api_logs_correla_55eb95_idx'), models.Index(fields=['user_id', 'dt_created'], name='api_logs_user_id_6753d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDailyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('log_date', models.DateField(help_text='Calendar date (UTC) for the summary')),
                ('call_counts', models.JSONField(blank=True, default=dict, help_text='API call counts by method, endpoint, model, and source')),
                ('response_summary', models.JSONField(blank=True, default=dict, help_text='Success/error counts, durations, status code distribution')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Auto-generated diagnostic hints for the day')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='Top grouped errors with counts and timestamps')),
                ('total_calls', models.PositiveIntegerField(default=0, help_text='Total API calls for the day')),
                ('total_errors', models.PositiveIntegerField(default=0, help_text='Total error responses (4xx/5xx) for the day')),
                ('avg_duration_ms', models.PositiveIntegerField(default=0, help_text='Average request duration in milliseconds')),
                ('user', models.ForeignKey(db_column='user_id', help_text='User this daily summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_logs',
                'indexes': [models.Index(fields=['log_date'], name='user_daily__log_dat_aeaaed_idx'), models.Index(fields=['user', 'log_date'], name='user_daily__user_id_0f6985_idx')],
                'unique_together': {('user', 'log_date')},
            },
        ),
    ]
