# Generated by Django 5.2.5 on 2025-08-29 22:53

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pending_comments_pending_created_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='health_rating',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='prefs',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='refs',
        ),
        migrations.AlterField(
            model_name='pending',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pending',
            name='data',
            field=models.JSONField(default=common.models.default_data),
        ),
        migrations.AlterField(
            model_name='pending',
            name='dt_processed',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pending',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pending',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pending',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
