# Generated by Django 5.2.1 on 2025-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_template_data_template_dt_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='contact',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='pending',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='setting',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='template',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
