# Generated by Django 5.2.5 on 2025-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_action_uuid_alter_contact_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='template',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
