# Generated by Django 5.2.8 on 2025-12-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__first__'),
        ('core', '0003_rename_action_project_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pending',
            name='pending_record__e5e38e_idx',
        ),
        migrations.RemoveIndex(
            model_name='softdeleteledger',
            name='core_softde_purge_a_3bb3e0_idx',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='record_id',
            new_name='id_record',
        ),
        migrations.RenameField(
            model_name='softdeleteledger',
            old_name='created_at',
            new_name='dt_created',
        ),
        migrations.RenameField(
            model_name='softdeleteledger',
            old_name='purge_at',
            new_name='dt_purge',
        ),
        migrations.AddIndex(
            model_name='pending',
            index=models.Index(fields=['id_record'], name='pending_id_reco_51c00d_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteledger',
            index=models.Index(fields=['dt_purge'], name='core_softde_dt_purg_1e3877_idx'),
        ),
    ]
