# Generated by Django 5.2.5 on 2025-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_action_comments_contact_comments_setting_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
