# Generated by Django 5.2.5 on 2025-08-30 18:41

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pending_comments_remove_pending_health_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='template',
            name='comment',
        ),
        migrations.AlterField(
            model_name='action',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='action',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='action',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='action',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='action',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='General notes about this contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='setting',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='template',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='template',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='template',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
