# Generated by Django 5.2.8 on 2025-12-06 03:54

from django.db import migrations, models


def _table_names(schema_editor) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return set(connection.introspection.table_names(cursor))


def _column_names(schema_editor, table_name: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _forward_compat_0004(apps, schema_editor):
    tables = _table_names(schema_editor)

    if 'pending' in tables:
        schema_editor.execute('DROP INDEX IF EXISTS pending_record__e5e38e_idx')
        pending_cols = _column_names(schema_editor, 'pending')
        if 'record_id' in pending_cols and 'id_record' not in pending_cols:
            schema_editor.execute('ALTER TABLE pending RENAME COLUMN record_id TO id_record')
        schema_editor.execute('CREATE INDEX IF NOT EXISTS pending_id_reco_51c00d_idx ON pending (id_record)')

    if 'core_softdeleteledger' in tables:
        schema_editor.execute('DROP INDEX IF EXISTS core_softde_purge_a_3bb3e0_idx')
        soft_cols = _column_names(schema_editor, 'core_softdeleteledger')
        if 'created_at' in soft_cols and 'dt_created' not in soft_cols:
            schema_editor.execute('ALTER TABLE core_softdeleteledger RENAME COLUMN created_at TO dt_created')
        if 'purge_at' in soft_cols and 'dt_purge' not in soft_cols:
            schema_editor.execute('ALTER TABLE core_softdeleteledger RENAME COLUMN purge_at TO dt_purge')
        schema_editor.execute('CREATE INDEX IF NOT EXISTS core_softde_dt_purg_1e3877_idx ON core_softdeleteledger (dt_purge)')


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__first__'),
        ('core', '0003_rename_action_project_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward_compat_0004, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='pending',
                    name='pending_record__e5e38e_idx',
                ),
                migrations.RemoveIndex(
                    model_name='softdeleteledger',
                    name='core_softde_purge_a_3bb3e0_idx',
                ),
                migrations.RenameField(
                    model_name='pending',
                    old_name='record_id',
                    new_name='id_record',
                ),
                migrations.RenameField(
                    model_name='softdeleteledger',
                    old_name='created_at',
                    new_name='dt_created',
                ),
                migrations.RenameField(
                    model_name='softdeleteledger',
                    old_name='purge_at',
                    new_name='dt_purge',
                ),
                migrations.AddIndex(
                    model_name='pending',
                    index=models.Index(fields=['id_record'], name='pending_id_reco_51c00d_idx'),
                ),
                migrations.AddIndex(
                    model_name='softdeleteledger',
                    index=models.Index(fields=['dt_purge'], name='core_softde_dt_purg_1e3877_idx'),
                ),
            ],
        ),
    ]
