# Generated by Django 5.2.5 on 2025-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_convert_multilingual_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
