# Generated by Django 5.2.5 on 2025-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_action_comment_remove_setting_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
