# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__first__'),
        ('core', '0004_remove_pending_pending_record__e5e38e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='softdeleteledger',
            name='core_softde_content_b722e6_idx',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='parent',
            new_name='action_id',
        ),
        migrations.RenameField(
            model_name='softdeleteledger',
            old_name='content_type',
            new_name='contenttype_id',
        ),
        migrations.AlterUniqueTogether(
            name='softdeleteledger',
            unique_together={('contenttype_id', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='softdeleteledger',
            index=models.Index(fields=['contenttype_id', 'object_id'], name='core_softde_content_dc3d5f_idx'),
        ),
    ]
