# Generated by Django 5.2.8 on 2025-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_softdeleteledger_core_softde_content_b722e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attention',
            field=models.CharField(blank=True, help_text='Auto-filled attention line from first and last name', max_length=201),
        ),
    ]
