# Generated by Django 5.2.5 on 2025-11-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_action_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
