# Generated by Django 5.2.5 on 2025-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_action_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_joined',
            new_name='dt_joined',
        ),
    ]
