# Generated by Django 5.2.8 on 2026-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_attention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id_project',
        ),
        migrations.AddField(
            model_name='action',
            name='project_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
