# Generated by Django 5.2.8 on 2026-01-04 15:42

from django.db import migrations, models


def _table_names(schema_editor) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return set(connection.introspection.table_names(cursor))


def _column_names(schema_editor, table_name: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _forward_compat_0007(apps, schema_editor):
    if 'actions' not in _table_names(schema_editor):
        return

    columns = _column_names(schema_editor, 'actions')

    if 'project_id' not in columns:
        schema_editor.execute('ALTER TABLE actions ADD COLUMN project_id bigint NOT NULL DEFAULT 0')

    columns = _column_names(schema_editor, 'actions')
    if 'id_project' in columns:
        # Best-effort numeric transfer from old string field.
        schema_editor.execute(
            """
            UPDATE actions
            SET project_id = CASE
                WHEN id_project ~ '^[0-9]+$' THEN id_project::bigint
                ELSE COALESCE(project_id, 0)
            END
            """
        )
        schema_editor.execute('ALTER TABLE actions DROP COLUMN id_project')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_attention'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_forward_compat_0007, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='action',
                    name='id_project',
                ),
                migrations.AddField(
                    model_name='action',
                    name='project_id',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
    ]
