# Generated by Django 5.2.8 on 2026-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_action_id_project_action_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('view_edit', 'View / Edit Matrix'), ('constants', 'User Constants'), ('db_defaults', 'Database Defaults'), ('sales_defaults', 'Sales Defaults'), ('purchase_defaults', 'Purchase Defaults'), ('accounting_defaults', 'Accounting Defaults'), ('keywords', 'Keyword Tracking')], max_length=255, null=True),
        ),
    ]
