# Generated by Django 5.2.8 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rbac_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
    ]
