# Generated by Django 5.2.8 on 2026-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_locked_to_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['model_name', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('report', 'Report'), ('statement', 'Statement'), ('list', 'List'), ('summary', 'Summary'), ('letter', 'Letter / Email'), ('label', 'Label'), ('export', 'Export'), ('utility', 'Utility')], default='report', help_text='Menu grouping (report, statement, list, summary, etc.)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='output_type',
            field=models.CharField(blank=True, choices=[('print', 'Print / PDF'), ('email', 'Email (SMTP)'), ('api', 'POST to external endpoint'), ('json', 'Return structured JSON'), ('export', 'CSV / Excel download'), ('label', 'Label / barcode print')], default='print', help_text='What the report produces (print, email, api, json, export, label)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='role_required',
            field=models.CharField(blank=True, help_text='Role required to see/run this report (blank = all users)', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sort_order',
            field=models.IntegerField(default=0, help_text="Display order within the model's report menu"),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(default=dict, help_text='Extended config: endpoint_url, template, parameters, etc.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, help_text="Canonical model key (e.g. 'customer', 'order')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional: tie to a specific record', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('view_edit', 'view_edit'), ('constants', 'constants'), ('db_defaults', 'db_defaults'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('keywords', 'keywords'), ('workbench_fields', 'workbench_fields'), ('detail_field_access', 'detail_field_access'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings')], max_length=255, null=True),
        ),
    ]
