# Generated by Django 5.2.8 on 2026-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_setting_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(None, '---------'), (100, 'Extreme'), (50, 'Hard'), (15, 'Moderate'), (10, 'Normal'), (4, 'Easy'), (1, 'Trivial')], default=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='kanban_column',
            field=models.CharField(choices=[('', '---------'), ('Backlog', 'Backlog'), ('Planning', 'Planning'), ('InProcess', 'In Process'), ('Review', 'Review'), ('Complete', 'Complete')], default='Backlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('', '---------'), ('user', 'User'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest')], default='user', help_text='User role in system', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', '---------'), ('view_edit', 'View / Edit Matrix'), ('constants', 'User Constants'), ('db_defaults', 'Database Defaults'), ('sales_defaults', 'Sales Defaults'), ('purchase_defaults', 'Purchase Defaults'), ('accounting_defaults', 'Accounting Defaults'), ('keywords', 'Keyword Tracking')], max_length=255, null=True),
        ),
    ]
