# Generated by Django 5.2.8 on 2026-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_action_difficulty_alter_action_kanban_column_and_more'),
        ('core', '0010_action_burndown_action_percent_complete_and_more'),
    ]

    operations = [
    ]
