# Generated by Django 5.2.8 on 2026-03-11

from django.db import migrations, models
from django.db.models import Q


def deactivate_duplicate_list_column_configs(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')

    base_qs = (
        Setting.objects.filter(purpose='list_column_config', is_active=True)
        .exclude(parent_model__isnull=True)
        .exclude(parent_model='')
    )

    parent_models = list(
        base_qs.values_list('parent_model', flat=True).distinct()
    )

    for parent_model in parent_models:
        rows = list(
            base_qs.filter(parent_model=parent_model).order_by('-dt_modified', '-id')
        )
        if len(rows) <= 1:
            continue

        keep_id = rows[0].id
        Setting.objects.filter(
            purpose='list_column_config',
            is_active=True,
            parent_model=parent_model,
        ).exclude(id=keep_id).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_merge_output_type'),
    ]

    operations = [
        migrations.RunPython(
            deactivate_duplicate_list_column_configs,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(
                fields=('parent_model', 'purpose'),
                condition=(
                    Q(purpose='list_column_config')
                    & Q(is_active=True)
                    & Q(parent_model__isnull=False)
                    & ~Q(parent_model='')
                ),
                name='uniq_active_list_column_config_parent_model',
            ),
        ),
    ]
