# Generated by Django 5.2.8 on 2026-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260110_1331'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='contact',
                    name='role',
                    field=models.CharField(
                        choices=[('', '---------'), ('user', 'User'), ('employee', 'Employee'), ('admin', 'Admin')],
                        default='user',
                        help_text='User role in system',
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
