# Generated by Django 5.2.8 on 2026-01-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contact_customer_id_contact_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='contact_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
