# Generated by Django 5.2.8 on 2026-01-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260110_1331'),
        ('core', '0012_alter_contact_role'),
        ('core', '0013_contact_customer_id_contact_employee_id_and_more'),
        ('core', '0014_action_contact_id'),
    ]

    operations = [
    ]
