# Generated by Django 5.2.8 on 2026-07-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_setting_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='data',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='data',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='other_id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('view_edit', 'view_edit'), ('constants', 'constants'), ('db_defaults', 'db_defaults'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('keywords', 'keywords'), ('search', 'search'), ('workbench_fields', 'workbench_fields'), ('detail_field_access', 'detail_field_access'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings'), ('list_column_config', 'list_column_config'), ('alice_pending', 'alice_pending'), ('alice_log', 'alice_log'), ('field_access', 'field_access'), ('seed', 'seed'), ('alice_coaching', 'alice_coaching'), ('campaign', 'campaign')], max_length=255, null=True),
        ),
    ]
