# Generated by Django 5.2.8 on 2026-01-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260110_1331 2'),
        ('core', '0015_merge_20260115_1339'),
    ]

    operations = [
    ]
