# Generated by Django 5.2.8 on 2026-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260115_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='pending',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
    ]
