# Generated by Django 5.2.8 on 2026-01-16 19:24

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_action_is_locked_contact_is_locked_pending_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is logically locked')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('source', models.CharField(choices=[('r25', 'React2025 Frontend'), ('wc3', 'WebClerk3 Internal'), ('ext', 'External Service')], help_text='System that initiated the request', max_length=10)),
                ('destination', models.CharField(help_text="Target system (e.g., 'wc3', 'shipstation', 'quickbooks', 'stripe')", max_length=100)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=500)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Request headers (sensitive data should be redacted)')),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Request body/payload')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Response headers')),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Response body (may be truncated for large responses)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='UUID to link related requests across systems', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (model_name, record_id, etc.)')),
                ('user_id', models.ForeignKey(blank=True, help_text='User who triggered the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_logs',
                'indexes': [models.Index(fields=['source', 'dt_created'], name='api_logs_source_544397_idx'), models.Index(fields=['destination', 'dt_created'], name='api_logs_destina_7c1aa6_idx'), models.Index(fields=['endpoint', 'status_code'], name='api_logs_endpoin_93eabc_idx'), models.Index(fields=['correlation_id'], name='api_logs_correla_55eb95_idx'), models.Index(fields=['user_id', 'dt_created'], name='api_logs_user_id_61a3ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is logically locked')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('model_name', models.CharField(help_text="Model that was changed (e.g., 'proposal', 'sales_order')", max_length=100)),
                ('id_record', models.BigIntegerField(help_text='ID of the record that was changed')),
                ('action', models.CharField(help_text="Action performed (e.g., 'created', 'updated', 'deleted', 'transferred')", max_length=50)),
                ('changes', models.JSONField(default=dict, help_text='Details of what changed (old vs new values)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('id_session', models.CharField(blank=True, help_text='Session ID for tracking user sessions', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context about the action')),
                ('user_id', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['model_name', 'id_record'], name='audit_logs_model_n_246870_idx'), models.Index(fields=['user_id', 'dt_created'], name='audit_logs_user_id_d05e13_idx'), models.Index(fields=['action', 'dt_created'], name='audit_logs_action_10d55c_idx')],
            },
        ),
    ]
