# Generated by Django 5.2.8 on 2026-01-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260115_1344'),
        ('core', '0017_create_api_log'),
    ]

    operations = [
    ]
