# Generated by Django 5.2.8 on 2026-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_print_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='retrospection',
            field=models.JSONField(blank=True, default=dict, help_text='Structured learning: intent, points for/against, harms, benefits, risk, unknowns, tfts', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('view_edit', 'view_edit'), ('constants', 'constants'), ('db_defaults', 'db_defaults'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('keywords', 'keywords'), ('search', 'search'), ('workbench_fields', 'workbench_fields'), ('detail_field_access', 'detail_field_access'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings'), ('list_column_config', 'list_column_config'), ('alice_pending', 'alice_pending'), ('alice_log', 'alice_log'), ('field_access', 'field_access'), ('seed', 'seed'), ('alice_coaching', 'alice_coaching'), ('campaign', 'campaign'), ('company_profile', 'company_profile'), ('accounting_interface', 'accounting_interface'), ('wchq_connection', 'wchq_connection'), ('ai_prompt_history', 'ai_prompt_history'), ('calculated_function', 'calculated_function'), ('print_defaults', 'print_defaults'), ('collaborate_webclerk', 'collaborate_webclerk')], max_length=255, null=True),
        ),
    ]
