# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_0016_merge_20260115_1344_0017_create_api_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='due_by',
            new_name='deadline_by',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='dt_due',
            new_name='dt_deadline',
        ),
        migrations.RemoveField(
            model_name='action',
            name='dt_end',
        ),
        migrations.RemoveField(
            model_name='action',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_locked',
        ),
        migrations.DeleteModel(
            name='APILog',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
