# Generated by Django 5.2.8 on 2026-01-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_auditlog_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softdeleteledger',
            name='dt_created',
        ),
    ]
