# Generated by Django 5.2.8 on 2026-07-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_action_config_apilog_config_auditlog_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='task',
            new_name='action',
        ),
    ]
