# Generated by Django 5.2.8 on 2026-02-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_register_audit_report_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', '---------'), ('view_edit', 'View / Edit Matrix'), ('constants', 'User Constants'), ('db_defaults', 'Database Defaults'), ('sales_defaults', 'Sales Defaults'), ('purchase_defaults', 'Purchase Defaults'), ('accounting_defaults', 'Accounting Defaults'), ('keywords', 'Keyword Tracking'), ('workbench_fields', 'Workbench Fields'), ('detail_field_access', 'Detail Field Access'), ('qa_counters', 'Q&A Counters'), ('qa_questions', 'Q&A Questions')], max_length=255, null=True),
        ),
    ]
