# Generated by Django 5.2.8 on 2026-02-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_parent_fields_to_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='project_ida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
