# Generated by Django 5.2.8 on 2026-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pending_attempts_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Order within a connection. 0 = unordered.'),
        ),
    ]
