# Generated by Django 5.2.8 on 2026-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_project_ida_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='baseline_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='baseline_start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
