# Generated by Django 5.2.8 on 2026-02-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_baseline_dates_to_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='baseline_end',
            new_name='dt_end_original',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='baseline_start',
            new_name='dt_start_original',
        ),
    ]
