# Generated by Django 5.2.8 on 2026-08-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_setting_scope_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form'), ('report', 'Report'), ('statement', 'Statement'), ('list', 'List'), ('summary', 'Summary'), ('letter', 'Letter / Email'), ('label', 'Label'), ('export', 'Export'), ('utility', 'Utility')], default='report', help_text='Menu grouping (report, statement, list, summary, etc.)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='output_type',
            field=models.CharField(blank=True, choices=[('print', 'Print / PDF'), ('screen', 'Screen form'), ('email', 'Email (SMTP)'), ('api', 'POST to external endpoint'), ('json', 'Return structured JSON'), ('export', 'CSV / Excel download'), ('label', 'Label / barcode print'), ('merge', 'Word / spreadsheet merge')], default='print', help_text='What the report produces (print, email, api, json, export, label)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('detail_layout', 'detail_layout'), ('compact_layout', 'compact_layout'), ('list_column_config', 'list_column_config'), ('field_registry', 'field_registry'), ('view_edit', 'view_edit'), ('field_access', 'field_access'), ('detail_field_access', 'detail_field_access'), ('workbench_fields', 'workbench_fields'), ('db_defaults', 'db_defaults'), ('constants', 'constants'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('accounting_interface', 'accounting_interface'), ('print_defaults', 'print_defaults'), ('keywords', 'keywords'), ('search', 'search'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions'), ('alice_pending', 'alice_pending'), ('alice_log', 'alice_log'), ('alice_coaching', 'alice_coaching'), ('ai_prompt_history', 'ai_prompt_history'), ('admin', 'admin'), ('admin_selectlist', 'admin_selectlist'), ('React_settings', 'React_settings'), ('seed', 'seed'), ('system', 'system'), ('feature', 'feature'), ('schema_map', 'schema_map'), ('calculated_function', 'calculated_function'), ('campaign', 'campaign'), ('company_profile', 'company_profile'), ('collaborate_webclerk', 'collaborate_webclerk'), ('wchq_connection', 'wchq_connection'), ('sync_config', 'sync_config'), ('file_storage', 'file_storage'), ('gantt_defaults', 'gantt_defaults'), ('burndown_config', 'burndown_config'), ('line_card_fields', 'line_card_fields')], max_length=255, null=True),
        ),
    ]
