# Generated by Django 5.2.8 on 2026-02-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_baseline_to_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='model_target',
            new_name='parent_model',
        ),
    ]
