# Generated by Django 5.2.8 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_report_category_alter_report_output_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
    ]
