# Generated by Django 5.2.8 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_model_target_to_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(None, ''), (100, '100'), (50, '50'), (15, '15'), (10, '10'), (4, '4'), (1, '1')], default=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='kanban_column',
            field=models.CharField(choices=[('', ''), ('Backlog', 'Backlog'), ('Planning', 'Planning'), ('InProcess', 'InProcess'), ('Review', 'Review'), ('Complete', 'Complete')], default='Backlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('', ''), ('user', 'user'), ('employee', 'employee'), ('admin', 'admin')], default='user', help_text='User role in system', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', ''), ('view_edit', 'view_edit'), ('constants', 'constants'), ('db_defaults', 'db_defaults'), ('sales_defaults', 'sales_defaults'), ('purchase_defaults', 'purchase_defaults'), ('accounting_defaults', 'accounting_defaults'), ('keywords', 'keywords'), ('workbench_fields', 'workbench_fields'), ('detail_field_access', 'detail_field_access'), ('qa_counters', 'qa_counters'), ('qa_questions', 'qa_questions')], max_length=255, null=True),
        ),
    ]
