# Generated by Django 5.2.8 on 2026-02-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_action_difficulty_alter_action_kanban_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='dt_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='due_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
