# Generated by Django 5.2.8 on 2026-02-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_dt_end_due_by_to_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='dt_end',
        ),
        migrations.RemoveField(
            model_name='action',
            name='due_by',
        ),
    ]
