# Generated by Django 5.2.8 on 2026-02-14 21:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_action_dt_end_remove_action_due_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefsMismatchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('parent_model', models.CharField(help_text='Parent model name (e.g. customer)', max_length=50)),
                ('parent_id', models.BigIntegerField(help_text='Parent record ID')),
                ('related_model', models.CharField(help_text='Related model name (e.g. contact)', max_length=50)),
                ('fk_field', models.CharField(help_text='FK field name on the related model', max_length=50)),
                ('mismatch_type', models.CharField(choices=[('fk_only', 'Record found by FK but missing from refs.links'), ('refs_only', 'Record in refs.links but FK does not match'), ('both_differ', 'Both exist but sets differ')], help_text='Type of mismatch detected', max_length=20)),
                ('fk_ids', models.JSONField(default=list, help_text='IDs found via FK query')),
                ('refs_ids', models.JSONField(default=list, help_text='IDs found in refs.links')),
                ('only_in_fk', models.JSONField(default=list, help_text='IDs present in FK but missing from refs')),
                ('only_in_refs', models.JSONField(default=list, help_text='IDs present in refs but missing from FK')),
                ('caller', models.CharField(blank=True, help_text='Function or endpoint that triggered the comparison', max_length=200)),
                ('user_id', models.BigIntegerField(blank=True, help_text='User who triggered the check (if known)', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context')),
            ],
            options={
                'db_table': 'refs_mismatch_log',
                'ordering': ['-dt_created'],
                'indexes': [models.Index(fields=['parent_model', 'dt_created'], name='refs_mismat_parent__cb5b1a_idx'), models.Index(fields=['related_model', 'dt_created'], name='refs_mismat_related_921be2_idx'), models.Index(fields=['mismatch_type', 'dt_created'], name='refs_mismat_mismatc_846afa_idx')],
            },
        ),
    ]
