# Generated by Django 5.2.8 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_list_report_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='contact',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='pending',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='report',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='setting',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='template',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
    ]
