# Generated by Django 5.2.8 on 2026-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_refs_mismatch_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_full',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
