# Generated by Django 5.2.8 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_dt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='action',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='contact',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='contact',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='modellinkconfig',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='modelroleconfig',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='notification',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='pending',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='pending',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='refsmismatchlog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='report',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='report',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='roleconfig',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='setting',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='setting',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='template',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='template',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='userdailylog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
    ]
