# Generated by Django 5.2.8 on 2026-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contact_address_full_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_id',
            field=models.BigIntegerField(blank=True, help_text='Optional FK to primary address record if needed', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_id',
            field=models.BigIntegerField(blank=True, help_text='Optional FK to primary email record if needed', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_id',
            field=models.BigIntegerField(blank=True, help_text='Optional FK to primary phone record if needed', null=True),
        ),
    ]
