# Generated by Django 5.2.8 on 2026-02-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contact_address_id_contact_email_id_contact_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='domain',
            field=models.CharField(blank=True, help_text='Primary domain extracted from email for quick search', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='domain_id',
            field=models.BigIntegerField(blank=True, help_text='Optional FK to primary domain record if needed', null=True),
        ),
    ]
