# Generated by Django 5.2.8 on 2026-02-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contact_domain_contact_domain_id'),
        ('orgs', '0009_remove_conditions_from_orgbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='rep_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', help_text='Associated customer org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', help_text='Associated employee org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_employee', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', help_text='Associated manufacturer org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='rep',
            field=models.ForeignKey(blank=True, db_column='rep_id', help_text='Associated sales rep org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_rep', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='contact',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Associated vendor org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_as_vendor', to='orgs.orgbase'),
        ),
    ]
