# Generated by Django 5.2.8 on 2026-02-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0035_remove_contact_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_user_id_d05e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='softdeleteledger',
            name='core_softde_content_dc3d5f_idx',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_id',
            field=models.ForeignKey(blank=True, db_column='action_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.action', to_field='uuid'),
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action_id',
            new_name='parent_action',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='softdeleteledger',
            name='contenttype_id',
            field=models.ForeignKey(db_column='contenttype_id', on_delete=django.db.models.deletion.CASCADE, related_name='soft_delete_entries', to='contenttypes.contenttype'),
        ),
        migrations.RenameField(
            model_name='softdeleteledger',
            old_name='contenttype_id',
            new_name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='softdeleteledger',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'dt_created'], name='audit_logs_user_id_2a37be_idx'),
        ),
        migrations.AddIndex(
            model_name='softdeleteledger',
            index=models.Index(fields=['content_type', 'object_id'], name='core_softde_content_556e49_idx'),
        ),
    ]
