# Generated by Django 5.2.8 on 2026-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_action_type_predicted_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='predicted_impact',
        ),
        migrations.AddField(
            model_name='action',
            name='impact',
            field=models.JSONField(blank=True, default=dict, help_text='Impact — not precision, but retrospection. predicted: waffly 1-5 gut feel at time of action. actual: waffly 1-5 looking back at what happened. The gap between them is the learning signal. refs: {transactions: [{model, id, ida, value}], explanation: why the gap exists}. Alice and users both contribute to defining actual.', null=True),
        ),
    ]
