# Generated by Django 5.2.8 on 2026-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_report_editor_type_and_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email address — required for login, null for record-only contacts', max_length=254, null=True, unique=True),
        ),
    ]
