# Generated by Django 5.2.8 on 2026-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_contact_email_nullable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='setting',
            name='uniq_active_list_column_config_parent_model',
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('purpose', 'wc:list_column_config'), ('is_active', True), ('parent_model__isnull', False), models.Q(('parent_model', ''), _negated=True)), fields=('parent_model', 'purpose'), name='uniq_active_list_column_config_parent_model'),
        ),
    ]
