# Generated by Django 5.2.8 on 2026-08-26 18:52

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('', 'Unspecified'), ('api', 'API'), ('sftp', 'SFTP'), ('database', 'Database'), ('webhook', 'Webhook'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=255)),
                ('status', models.CharField(blank=True, choices=[('', 'Unspecified'), ('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('retired', 'Retired')], max_length=32, null=True)),
                ('scripts', models.JSONField(blank=True, null=True)),
                ('relationships', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('maps', models.JSONField(blank=True, null=True)),
                ('encryption', models.JSONField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('conflicts', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('direction', models.CharField(choices=[('', 'Unspecified'), ('push', 'Push'), ('pull', 'Pull'), ('sync', 'Sync')], max_length=255)),
                ('status', models.CharField(blank=True, choices=[('', 'Unspecified'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=32, null=True)),
                ('dt_processed', models.BigIntegerField(db_index=True, default=0)),
                ('alert', models.CharField(blank=True, choices=[('', 'Unspecified'), ('none', 'None'), ('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=255, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('duration', models.BigIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('maps', models.JSONField(blank=True, null=True)),
                ('encryption', models.JSONField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('conflicts', models.JSONField(blank=True, null=True)),
                ('connection', models.ForeignKey(db_column='connection_id', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='sync.connection')),
            ],
            options={
                'db_table': 'bundles',
            },
        ),
    ]
