# Generated by Django 5.2.8 on 2026-08-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_bundle_status_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
