# Generated by Django 5.2.8 on 2026-09-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_add_bundle_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('', 'Unspecified'), ('api', 'API'), ('sftp', 'SFTP'), ('database', 'Database'), ('webhook', 'Webhook'), ('manual', 'Manual'), ('internal', 'Internal'), ('bank', 'Bank Account'), ('gateway', 'Cash Gateway')], max_length=255),
        ),
    ]
