# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_athena_token_to_encryption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='is_deleted',
        ),
    ]
