# Generated by Django 5.2.8 on 2026-09-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_remove_bundle_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('buyer', 'buyer'), ('vendor', 'vendor'), ('manufacturer', 'manufacturer'), ('rep', 'rep'), ('employee', 'employee'), ('accounting', 'accounting'), ('sales', 'sales'), ('production', 'production'), ('warehouse', 'warehouse')], default='', help_text='The role this Connection acts as (access.CONNECTION_ROLES)', max_length=30),
        ),
        migrations.AddField(
            model_name='connection',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text='Ids this Connection speaks for, e.g. {"vendor": [12]}'),
        ),
    ]
