# Generated by Django 5.2.8 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_connection_role_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
    ]
