# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_sync_key_to_encryption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='is_locked',
        ),
    ]
