# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_add_deploy_training_purposes 2'),
        ('sync', '0005_bundle_dt_processed_remove_local_config 2'),
        ('sync', '0006_purpose_to_basemodel 2'),
        ('sync', '0007_add_dt_approved 2'),
        ('sync', '0008_add_times_used_dt_last_used 2'),
        ('sync', '0009_add_commission_line_type_and_function_category 2'),
        ('sync', '0010_drop_comment_field 2'),
        ('sync', '0010_drop_comment_field'),
    ]

    operations = [
    ]
