"""
IDA prefix utilities — born-on identity for cross-database sync.

Identity Model (§25 — Sync Topologies):
    id   — PK, dataset-scoped. Primary's id overwrites satellites in
           hub-spoke merge; always new in peer transfer.
    ida  — Born-on soft identifier with environment prefix. Generated
           once on first save. CAN be overwritten during hub-spoke
           merge (primary is authoritative); always new in peer transfer.
    uuid — Cross-database matching key. ONLY truly immutable identity.

The ida prefix tells users *where* a record was created:
    DEV-42   → record 42, born on the DEV database
    LOC-42   → record 42, born on a LOCAL database
    ida-1087 → record 1087, born on PRODUCTION

Sync behaviour:
    Hub & Spoke: primary's ida overwrites satellite's ida on merge.
    Peer Transfer: target generates a fresh ida (source ida ignored).
    Write-Through: remote is primary — its ida flows to local.

Configuration:
    IDA_PREFIX env var (explicit override) takes precedence.
    Otherwise derived from DATA_SET_ID:
        LOCAL      → "LOC"
        DEV        → "DEV"
        STAGING    → "STG"
        PRODUCTION → "ida"

Usage:
    from common.ida import get_ida_prefix, generate_ida

    prefix = get_ida_prefix()     # e.g. "DEV"
    ida    = generate_ida(pk=42)  # e.g. "DEV-42"
"""
from __future__ import annotations

import logging
from functools import lru_cache
from typing import Optional

logger = logging.getLogger(__name__)

# ── Prefix derivation from DATA_SET_ID ──────────────────────────────

_DATA_SET_PREFIX_MAP = {
    "LOCAL":      "LOC",
    "DEV":        "DEV",
    "STAGING":    "STG",
    "PRODUCTION": "ida",
    "PROD":       "ida",
}


@lru_cache(maxsize=1)
def get_ida_prefix() -> str:
    """Return the ida prefix for this environment.

    Resolution order:
        1. IDA_PREFIX env var / settings (explicit)
        2. Derived from DATA_SET_ID via _DATA_SET_PREFIX_MAP
        3. Fallback: "ida"
    """
    from django.conf import settings

    # 1. Explicit IDA_PREFIX in settings (set from .env)
    explicit = getattr(settings, 'IDA_PREFIX', None)
    if explicit:
        return explicit

    # 2. Derive from DATA_SET_ID
    data_set_id = getattr(settings, 'DATA_SET_ID', 'UNKNOWN')
    prefix = _DATA_SET_PREFIX_MAP.get(data_set_id.upper(), None)
    if prefix:
        return prefix

    # 3. Fallback
    logger.debug("No IDA_PREFIX configured and DATA_SET_ID=%r not mapped; using 'ida'", data_set_id)
    return "ida"


def generate_ida(pk: int, prefix: Optional[str] = None) -> str:
    """Generate a born-on ida value for a record.

    Args:
        pk:     The primary key of the record (from the *creating* database).
        prefix: Override prefix; if None, uses get_ida_prefix().

    Returns:
        String like "DEV-42" or "ida-1087".
    """
    if prefix is None:
        prefix = get_ida_prefix()
    return f"{prefix}-{pk}"


def is_local_ida(ida_value: str) -> bool:
    """Check whether an ida was generated by *this* environment.

    Useful for determining if a record was born locally vs. received
    from another database during sync.
    """
    prefix = get_ida_prefix()
    return ida_value.startswith(f"{prefix}-")


def parse_ida(ida_value: str) -> tuple[str, str]:
    """Split an ida into (prefix, local_pk_str).

    Example:
        parse_ida("DEV-42") → ("DEV", "42")
        parse_ida("ida-1087") → ("ida", "1087")
    """
    if '-' in ida_value:
        prefix, _, rest = ida_value.partition('-')
        return prefix, rest
    return "", ida_value
