# Generated by Django 5.2.5 on 2025-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_invoiceline_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=40, unique=True)),
                ('dt_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_receipts',
            },
        ),
    ]
