# Generated by Django 5.2.1 on 2025-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_purchasereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='requisitionstd',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
