# Generated by Django 5.2.5 on 2025-09-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_invoiceline_security_level_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_security_range',
        ),
        migrations.AlterField(
            model_name='project',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
