# Generated by Django 5.2.5 on 2025-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_project_project_security_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Lifecycle + lineage (parent_link, history, forms, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Preference / option flags (currency, terms, locale, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='Structured references (bill_to, ship_to, campaign, serials, etc.)', null=True),
        ),
    ]
