# filepath: /Users/williamjames/Documents/CommerceExpert/webClerk3/core/services/notused/api_outside.py
#payments
#shippers
#scrum
#gantt
#tax_jurisdictions
#exchange_rates
#address_validation
#shipping_rates
#shipping_labels
#tracking
#inventory
#warehouses
#inventory_adjustments
#inventory_transfers
#inventory_stacks
#items
#item_variants
#item_locations
#item_barcodes
#item_serial_numbers
#inventory_item_kits
#boms
#forecasts
#projects
#project_tasks
#project_milestones
#project_time_entries
#project_expenses
#project_invoices
#project_documents
#project_comments
#project_tags
#project_members
#project_templates
#project_template_tasks
#project_template_milestones
#project_template_time_entries
#project_template_expenses
#project_template_invoices
#project_template_documents
#project_template_comments
#project_template_tags
#project_template_members
#notifications
#notification_templates
#notification_settings
#logs
#audit_logs
#system_settings
#user_settings
#app_settings
#feature_flags
#api_keys
#webhooks
#integrations
#third_party_services
#data_imports
#data_exports
#reports
#report_templates
#report_schedules
#dashboards
#dashboard_widgets
#dashboard_layouts
#analytics
#metrics
#kpis
#goals
#objectives
#key_results
#performance_reviews
#feedback
#surveys
#survey_responses
#survey_templates
#survey_questions
#survey_answers
#survey_participants
#survey_results
#help_articles
#faqs
#knowledge_base
#documentation
#changelogs
#release_notes
#roadmap
#ideas
#feature_requests
#bug_reports
#issues
#issue_comments
#issue_labels
#issue_milestones
#forecast_items
#cash_flows
#bots
#automation_rules
#automation_triggers
#automation_actions
#schedules
#tasks
#task_comments
#task_labels
#task_attachments
#sync
