# Generated by Django 5.2.5 on 2025-09-15 11:06

import common.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32)),
                ('priority', models.CharField(blank=True, max_length=32, null=True)),
                ('price_level', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.BigIntegerField(db_index=True, default=0)),
                ('manufacturer_id', models.BigIntegerField(db_index=True, default=0)),
                ('vendor_id', models.BigIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('price_level', models.CharField(blank=True, db_column='price_level', max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.JSONField(blank=True, default=dict, null=True)),
                ('cost', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.JSONField(blank=True, default=dict, null=True)),
                ('tax', models.JSONField(blank=True, default=dict, null=True)),
                ('action', models.JSONField(blank=True, default=dict, null=True)),
                ('physical', models.JSONField(blank=True, default=dict, null=True)),
                ('flow', models.JSONField(blank=True, default=dict, null=True)),
                ('source', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity_packed', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.invoice')),
            ],
            options={
                'db_table': 'invoice_lines',
            },
        ),
    ]
