# Generated by Django 5.2.5 on 2025-10-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={},
        ),
    ]
