# Generated by Django 5.2.5 on 2025-08-30 03:42

import common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionStd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, help_text='Alternate ID for external systems (indexed)', max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized created timestamp (ms UTC)')),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0, help_text='Denormalized modified timestamp (ms UTC)')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('version', models.PositiveIntegerField(default=1, help_text='Incremented on each successful save')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal API metadata structure')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='References: keywords, tags, categories')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences and settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='User comments and notes')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, default='draft', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('cost_extended', models.FloatField(blank=True, default=0, null=True)),
                ('lead_days', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_extended', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'requisitions',
                'indexes': [models.Index(fields=['purpose'], name='requisition_purpose_126bf1_idx'), models.Index(fields=['status'], name='requisition_status_e258b0_idx'), models.Index(fields=['name'], name='requisition_name_eb071f_idx')],
            },
        ),
    ]
