# Generated by Django 5.2.5 on 2025-08-31 13:01

import apps.transactions.models.projects
import common.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('situation', models.TextField(blank=True, default='', help_text='Current context / problem narrative')),
                ('objective', models.JSONField(default=apps.transactions.models.projects.default_objective, help_text='Structured goal & success metrics')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 (highest) – 5 (lowest)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('onhold', 'On Hold'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32)),
                ('attention', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('contact_id', models.BigIntegerField(blank=True, db_index=True, help_text='Owning / primary contact id', null=True)),
                ('tasks', models.JSONField(default=apps.transactions.models.projects.default_tasks, help_text='Backlog tasks + derived counters')),
                ('burndown', models.PositiveSmallIntegerField(default=0, help_text='0-100 percent completion snapshot')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('intent', models.CharField(blank=True, default='', help_text='Short intent tagline / elevator pitch', max_length=255)),
                ('logistics', models.JSONField(default=apps.transactions.models.projects.default_logistics, help_text='Budget / schedule / resource data')),
                ('slug', models.CharField(blank=True, db_index=True, help_text='URL / human friendly identifier derived from intent (unique)', max_length=180)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Projected or realized profit (base currency with cents)', max_digits=14)),
                ('profit_velocity', models.IntegerField(default=0, help_text='Profit per time unit (arbitrary) for trend')),
                ('security_level', models.PositiveSmallIntegerField(default=0, help_text='0 (open) – 5 (restricted)')),
                ('data', models.JSONField(blank=True, default=apps.transactions.models.projects.default_data, help_text='Arbitrary project-specific data payload (nullable)', null=True)),
            ],
            options={
                'db_table': 'projects',
                'indexes': [models.Index(fields=['status'], name='project_status_idx'), models.Index(fields=['priority'], name='project_priority_idx'), models.Index(fields=['attention'], name='project_attention_idx'), models.Index(fields=['category'], name='project_category_idx'), models.Index(fields=['contact_id'], name='project_contact_idx'), models.Index(fields=['status', 'priority'], name='project_status_priority_idx'), models.Index(fields=['slug'], name='project_slug_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='project_priority_range'), models.CheckConstraint(condition=models.Q(('burndown__gte', 0), ('burndown__lte', 100)), name='project_burndown_range'), models.CheckConstraint(condition=models.Q(('security_level__gte', 0), ('security_level__lte', 5)), name='project_security_range')],
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='RequisitionStd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, default='draft', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('cost_extended', models.FloatField(blank=True, default=0, null=True)),
                ('lead_days', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_extended', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'requisitions_std',
                'indexes': [models.Index(fields=['purpose'], name='requisition_purpose_227b42_idx'), models.Index(fields=['status'], name='requisition_status_e07d82_idx'), models.Index(fields=['name'], name='requisition_name_2c639c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(choices=[('proposal', 'Proposal'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('workorder', 'Workorder'), ('requisition', 'Requisition')], db_index=True, max_length=32)),
                ('object_id', models.BigIntegerField(db_index=True)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='transactions.project')),
            ],
            options={
                'db_table': 'project_associations',
                'indexes': [models.Index(fields=['model_code', 'object_id'], name='projassoc_target_idx')],
                'unique_together': {('project', 'model_code', 'object_id')},
            },
        ),
    ]
