# Generated by Django 5.2.5 on 2025-08-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='requisitionstd',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
    ]
