# Generated by Django 5.2.8 on 2026-02-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_invoice_is_locked_order_is_locked_proposal_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='orderline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='line_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='line_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
