# Generated by Django 5.2.5 on 2025-10-26 20:55

from django.db import migrations


def create_purchase_order_line_table(apps, schema_editor):
    PurchaseOrderLine = apps.get_model('transactions', 'PurchaseOrderLine')
    table_name = PurchaseOrderLine._meta.db_table
    existing = schema_editor.connection.introspection.table_names()
    if table_name in existing:
        return
    schema_editor.create_model(PurchaseOrderLine)


def drop_purchase_order_line_table(apps, schema_editor):
    PurchaseOrderLine = apps.get_model('transactions', 'PurchaseOrderLine')
    table_name = PurchaseOrderLine._meta.db_table
    existing = schema_editor.connection.introspection.table_names()
    if table_name not in existing:
        return
    schema_editor.delete_model(PurchaseOrderLine)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_purchaseorderline_options'),
    ]

    operations = [
        migrations.RunPython(create_purchase_order_line_table, drop_purchase_order_line_table),
    ]
