# Generated by Django 5.2.5 on 2025-08-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_requisitionstd'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requisitionstd',
            new_name='requisition_purpose_227b42_idx',
            old_name='requisition_purpose_126bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='requisitionstd',
            new_name='requisition_status_e07d82_idx',
            old_name='requisition_status_e258b0_idx',
        ),
        migrations.RenameIndex(
            model_name='requisitionstd',
            new_name='requisition_name_2c639c_idx',
            old_name='requisition_name_eb071f_idx',
        ),
        migrations.AlterModelTable(
            name='requisitionstd',
            table='requisitions_std',
        ),
    ]
