# Generated by Django 5.2.5 on 2025-09-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_workorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='quantity_packed',
        ),
    ]
