# Generated by Django 5.2.8 on 2026-02-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_line_number_and_line_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='is_locked',
        ),
    ]
