# Generated by Django 5.2.8 on 2025-12-06 03:54

import apps.transactions.models.project
import common.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_id_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='dt_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='dt_processed',
            field=models.DateTimeField(blank=True, help_text='When the payment was processed by gateway', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dt_reconciliation',
            field=models.DateTimeField(blank=True, help_text='When the payment was reconciled', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Processing fee charged by gateway', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='manual', help_text='Payment gateway used', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw response from payment gateway', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_gateway_payment_intent',
            field=models.CharField(blank=True, help_text='Payment intent ID from Stripe or equivalent', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_gateway_transaction',
            field=models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciled',
            field=models.BooleanField(default=False, help_text='Whether this payment has been reconciled'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', help_text='Current payment status', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('situation', models.TextField(blank=True, default='', help_text='Current context / problem narrative')),
                ('objective', models.JSONField(default=apps.transactions.models.project.default_objective, help_text='Structured goal & success metrics')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 (highest) – 5 (lowest)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('onhold', 'On Hold'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32)),
                ('attention', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('id_contact', models.BigIntegerField(blank=True, db_index=True, help_text='Owning / primary contact id', null=True)),
                ('tasks', models.JSONField(default=apps.transactions.models.project.default_tasks, help_text='Backlog tasks + derived counters')),
                ('burndown', models.PositiveSmallIntegerField(default=0, help_text='0-100 percent completion snapshot')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('intent', models.CharField(blank=True, default='', help_text='Short intent tagline / elevator pitch', max_length=255)),
                ('logistics', models.JSONField(default=apps.transactions.models.project.default_logistics, help_text='Budget / schedule / resource data')),
                ('slug', models.CharField(blank=True, db_index=True, help_text='URL / human friendly identifier derived from intent (unique)', max_length=180)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Projected or realized profit (base currency with cents)', max_digits=14)),
                ('profit_velocity', models.IntegerField(default=0, help_text='Profit per time unit (arbitrary) for trend')),
                ('data', models.JSONField(blank=True, default=apps.transactions.models.project.default_data, help_text='Arbitrary project-specific data payload (nullable)', null=True)),
            ],
            options={
                'db_table': 'projects',
                'indexes': [models.Index(fields=['status'], name='project_status_idx'), models.Index(fields=['priority'], name='project_priority_idx'), models.Index(fields=['attention'], name='project_attention_idx'), models.Index(fields=['category'], name='project_category_idx'), models.Index(fields=['id_contact'], name='project_contact_idx'), models.Index(fields=['status', 'priority'], name='project_status_priority_idx'), models.Index(fields=['slug'], name='project_slug_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='project_priority_range'), models.CheckConstraint(condition=models.Q(('burndown__gte', 0), ('burndown__lte', 100)), name='project_burndown_range')],
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of this payment applied to this invoice', max_digits=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='When this application was created')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this application')),
                ('invoice', models.ForeignKey(help_text='The invoice receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='transactions.invoice')),
                ('payment', models.ForeignKey(help_text='The payment being applied', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transactions.payment')),
            ],
            options={
                'db_table': 'payment_applications',
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
