# Generated by Django 5.2.5 on 2025-10-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_create_purchase_order_line_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.purchaseorder'),
        ),
    ]
