# Generated by Django 5.2.5 on 2025-08-30 21:28

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_requisition_purpose_126bf1_idx_requisition_purpose_227b42_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='created_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='modified_dt',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
