# Generated by Django 5.2.8 on 2025-12-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_payment_date_payment_dt_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id_manufacturer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='id_vendor',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='id_manufacturer',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='id_vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id_manufacturer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id_vendor',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='id_manufacturer',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='id_vendor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id_manufacturer',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id_vendor',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manufacturer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='manufacturer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manufacturer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manufacturer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vendor_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='manufacturer_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
