# Generated by Django 5.2.5 on 2025-09-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_salesorder_salesorderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderline',
            name='quantity_invoiced',
        ),
    ]
