# Generated by Django 5.2.5 on 2025-09-12 13:49

import common.models
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_shorten_workorderline_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectassociation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proposal',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='dt_created',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisition',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='requisition',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='dt_modified',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='health_rating',
            field=models.IntegerField(default=0, help_text='Data quality rating (0-100)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='ida',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Record is logically active'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE transactions_invoice "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE transactions_invoice "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='invoice',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectassociation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE transactions_proposal "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE transactions_proposal "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='proposal',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE purchase_orders "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE purchase_orders "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='purchaseorder',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE transactions_requisition "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE transactions_requisition "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='requisition',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='requisition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE sales_orders "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE sales_orders "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='salesorder',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE work_orders "
                        "ALTER COLUMN dt_created TYPE bigint "
                        "USING ROUND(EXTRACT(EPOCH FROM dt_created) * 1000)::bigint;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE work_orders "
                        "ALTER COLUMN dt_created TYPE timestamptz "
                        "USING to_timestamp(dt_created / 1000.0);"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='workorder',
                    name='dt_created',
                    field=models.BigIntegerField(db_index=True, default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='metadata',
            field=models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['refs'], name='transaction_refs_d287ff_gin'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prefs'], name='transaction_prefs_f2a515_gin'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['refs'], name='transaction_refs_7e439d_gin'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prefs'], name='transaction_prefs_c4441a_gin'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['refs'], name='transaction_refs_4b5b33_gin'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prefs'], name='transaction_prefs_739e44_gin'),
        ),
    ]
