# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_invoice_id_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='parent',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='contact',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='invoice',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='paymentmethod_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_term',
            new_name='paymentterm_id',
        ),
        migrations.RenameField(
            model_name='paymentapplication',
            old_name='invoice',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='paymentapplication',
            old_name='payment',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='proposalline',
            old_name='parent',
            new_name='proposal_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='parent',
            new_name='purchaseorder_id',
        ),
        migrations.RenameField(
            model_name='requisitionline',
            old_name='parent',
            new_name='requisition_id',
        ),
        migrations.RenameField(
            model_name='salesorderline',
            old_name='parent',
            new_name='salesorder_id',
        ),
        migrations.RenameField(
            model_name='workorderline',
            old_name='parent',
            new_name='workorder_id',
        ),
        migrations.AlterUniqueTogether(
            name='paymentapplication',
            unique_together={('payment_id', 'invoice_id')},
        ),
    ]
