# Generated by Django 5.2.5 on 2025-08-31 12:37

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_project_enhancements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_slug_unique',
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prefs',
            field=models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='project',
            name='refs',
            field=models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='URL / human friendly identifier derived from intent (unique)', max_length=180),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('slug',)},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='project_slug_idx'),
        ),
    ]
