# Generated by Django 5.2.8 on 2025-12-07 18:18

import apps.transactions.models.payment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_parent_invoiceline_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Payment history and balances', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='refs',
            field=models.JSONField(blank=True, default=dict, help_text='References like order_id', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=apps.transactions.models.payment.default_metadata, help_text='Additional metadata for reconciliation, gateway data, and audit trail', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refs',
            field=models.JSONField(blank=True, default=apps.transactions.models.payment.default_refs, help_text='References to related transactions (invoices, orders, etc.)', null=True),
        ),
    ]
