# Generated by Django 5.2.8 on 2025-12-08 15:09

import apps.transactions.models.base_transaction_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_invoice_metadata_alter_invoice_refs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
    ]
