# Generated by Django 5.2.8 on 2025-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_invoice_totals_proposal_totals_purchaseorder_totals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('work_order', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('work_order', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('work_order', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('work_order', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the parent transaction', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('work_order', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
    ]
