# Generated by Django 5.2.8 on 2026-07-04 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_rename_data_to_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Pro Forma'), ('credit_note', 'Credit Note'), ('deposit', 'Deposit')], db_index=True, default='invoice', help_text='Invoice / Pro Forma / Credit Note / Deposit', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('id_gateway_payment_intent', ''), _negated=True), fields=('id_gateway_payment_intent',), name='uniq_payment_gateway_intent'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
