# Generated by Django 5.2.8 on 2026-01-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_rename_purchase_receipt_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='balance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
