# Generated by Django 5.2.8 on 2026-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_add_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='order',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
