# Generated by Django 5.2.8 on 2026-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_invoice_balance_invoice_total_proposal_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Short name or title', max_length=255),
        ),
    ]
