# Generated by Django on-the-fly to add RequisitionStd model
from django.db import migrations, models
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_proposal_purchaseorder_requisition_requisitionline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionStd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(db_index=True, default='', max_length=128)),
                ('purpose', models.CharField(db_index=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, db_index=True, default='draft', max_length=50)),
            ],
            options={
                'db_table': 'requisitions_std',
            },
        ),
    ]
