# Generated by Django 5.2.8 on 2026-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_payment_gateway'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('', '---------'), ('manual', 'Manual'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='manual', help_text='Payment gateway used', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='attention',
            field=models.CharField(choices=[('', '---------'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='URL / human friendly identifier derived from intent', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('active', 'Active'), ('onhold', 'On Hold'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('planned', 'Planned'), ('released', 'Released'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('complete', 'Complete'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=32),
        ),
    ]
