# Generated by Django 5.2.8 on 2026-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_pendingpaymentapplication_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Expense bucket (e.g. Office Supplies, Travel). Maps to GL via select_list in Setting.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive=money in (received), negative=money out (disbursed). SUM(amount) = net cash position.', max_digits=15),
        ),
    ]
