# Generated by Django 5.2.8 on 2026-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_invoice_status_alter_payment_gateway_and_more'),
        ('transactions', '0014_alter_project_unique_together_alter_invoice_status_and_more'),
    ]

    operations = [
    ]
