# Generated by Django 5.2.8 on 2026-01-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_merge_20260110_1331 2'),
        ('transactions', '0015_merge_20260110_1331'),
    ]

    operations = [
    ]
