# Generated by Django 5.2.8 on 2026-07-31 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_payment_add_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive=money in (received), negative=money out (disbursed). SUM(amount) = net cash position.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', help_text='Contact who made or received the payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dt_payment',
            field=models.DateTimeField(blank=True, help_text='Date the payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('received', 'Received'), ('expense', 'Expense')], db_index=True, default='expense', help_text='Required. Received=money in, Expense=money out. Category tells the rest.', max_length=20),
        ),
    ]
