# Generated by Django 5.2.8 on 2026-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_merge_20260115_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
    ]
