# Generated by Django 5.2.5 on 2025-09-17 00:43

import apps.transactions.models.projects
import common.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_add_work_no_to_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('situation', models.TextField(blank=True, default='', help_text='Current context / problem narrative')),
                ('objective', models.JSONField(default=apps.transactions.models.projects.default_objective, help_text='Structured goal & success metrics')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 (highest) – 5 (lowest)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('onhold', 'On Hold'), ('blocked', 'Blocked'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32)),
                ('attention', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('contact_id', models.BigIntegerField(blank=True, db_index=True, help_text='Owning / primary contact id', null=True)),
                ('tasks', models.JSONField(default=apps.transactions.models.projects.default_tasks, help_text='Backlog tasks + derived counters')),
                ('burndown', models.PositiveSmallIntegerField(default=0, help_text='0-100 percent completion snapshot')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('intent', models.CharField(blank=True, default='', help_text='Short intent tagline / elevator pitch', max_length=255)),
                ('logistics', models.JSONField(default=apps.transactions.models.projects.default_logistics, help_text='Budget / schedule / resource data')),
                ('slug', models.CharField(blank=True, db_index=True, help_text='URL / human friendly identifier derived from intent (unique)', max_length=180)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Projected or realized profit (base currency with cents)', max_digits=14)),
                ('profit_velocity', models.IntegerField(default=0, help_text='Profit per time unit (arbitrary) for trend')),
                ('data', models.JSONField(blank=True, default=apps.transactions.models.projects.default_data, help_text='Arbitrary project-specific data payload (nullable)', null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='project_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['attention'], name='project_attention_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='project_category_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['contact_id'], name='project_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority'], name='project_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='project_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(priority__gte=1, priority__lte=5), name='project_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(burndown__gte=0, burndown__lte=100), name='project_burndown_range'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('slug',)},
        ),
    ]
