# Generated by Django 5.2.8 on 2026-01-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_invoice_is_locked_invoiceline_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO number', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO number', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO number', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO number', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Customer PO number', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=128, null=True),
        ),
    ]
