# Generated by Django 5.2.8 on 2026-07-31 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_add_tax_jurisdiction_exempt'),
        ('transactions', '0017_payment_dt_default_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', help_text='Customer org — received payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', help_text='Vendor org — expense payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_vendor', to='orgs.orgbase'),
        ),
    ]
