# Generated by Django 5.2.8 on 2026-01-16 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_add_terms_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='probability',
            field=models.IntegerField(default=50, help_text='Probability of closing this proposal (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
