# Generated by Django 5.2.5 on 2025-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_purchasereceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='calc',
            new_name='totals',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='calc',
            new_name='prices',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='calc',
        ),
        migrations.AddField(
            model_name='invoice',
            name='action',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='flow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='totals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='totals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='action',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='flow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_no',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='totals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='action',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='flow',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='totals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='requisitionstd',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AlterField(
            model_name='workorderline',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
