# Generated by Django 5.2.8 on 2026-07-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_payment_customer_vendor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, help_text='How they paid: visa_3425, check-WellsFargo, cash, etc. Freehand or select list.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, db_column='paymentmethod_id', help_text='Gateway payment method FK (system use)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.paymentmethod'),
        ),
    ]
