# Generated by Django 5.2.8 on 2026-01-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_merge_20260115_1344'),
        ('transactions', '0019_add_proposal_probability'),
    ]

    operations = [
    ]
