# Generated by Django 5.2.8 on 2026-07-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_payment_method_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
