# Generated by Django 5.2.5 on 2025-09-17 14:06

import apps.transactions.models.base_transaction_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_rename_calc_purchaseorder_totals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='costs',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='prices',
            new_name='finance',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='totals',
            new_name='sell',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='totals',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='totals',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='totals',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='prices',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sell',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sell',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sell',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='sell',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cost',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='finance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sell',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='totals',
            field=models.JSONField(blank=True, default=apps.transactions.models.base_transaction_model.default_totals, null=True),
        ),
    ]
