# Generated by Django 5.2.8 on 2026-07-31 12:09

import common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_add_tax_jurisdiction_exempt'),
        ('transactions', '0020_payment_drop_payment_method_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('dt_transaction', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Transaction date from statement', null=True)),
                ('description', models.CharField(blank=True, help_text='Raw description from statement (merchant name, memo, etc.)', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Signed amount from statement. Negative=charge, positive=credit/refund.', max_digits=15)),
                ('raw_text', models.TextField(blank=True, help_text='Full original line from import (CSV row, OFX record, OCR text)')),
                ('source', models.CharField(blank=True, help_text='Bank or card name: chase_visa_3425, wellsfargo_checking, etc.', max_length=200)),
                ('statement_date', models.DateField(blank=True, help_text='Statement period date (month-end)', null=True)),
                ('batch_id', models.CharField(blank=True, db_index=True, help_text='Import batch ID — groups lines from one import', max_length=100)),
                ('classification', models.CharField(choices=[('unknown', 'Unknown'), ('business', 'Business'), ('personal', 'Personal')], db_index=True, default='unknown', help_text='business, personal, or unknown. User sets, Alice suggests.', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Expense category — same select list as Payment.category', max_length=100)),
                ('merchant', models.CharField(blank=True, help_text='Resolved merchant name (cleaned from description)', max_length=200)),
                ('promoted', models.BooleanField(db_index=True, default=False, help_text='True = already created a Payment record from this line')),
                ('payment_id', models.BigIntegerField(blank=True, help_text='Payment record ID created from this line', null=True)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', help_text='Resolved vendor/merchant contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor_id', help_text='Resolved vendor org', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='orgs.orgbase')),
            ],
            options={
                'db_table': 'statement_lines',
                'ordering': ['-dt_transaction'],
            },
        ),
    ]
