# Generated by Django 5.2.8 on 2026-07-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_statement_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementline',
            name='ledger',
            field=models.CharField(choices=[('post', 'Post'), ('skip', 'Skip'), ('review', 'Review')], db_index=True, default='post', help_text='post=hit GL on promote, skip=already ledgered elsewhere, review=admin decides', max_length=10),
        ),
    ]
