# Generated by Django 5.2.8 on 2026-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_proposal_dt_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='dt_needed',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Date needed (UTC epoch ms) — when customer needs the order', null=True),
        ),
    ]
