# Generated by Django 5.2.8 on 2026-08-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_add_dt_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='ship_via',
            field=models.CharField(blank=True, help_text='Carrier/shipping method (US Postal, UPS, FedEx, etc.)', max_length=50, null=True),
        ),
    ]
