# Generated by Django 5.2.8 on 2026-01-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_rename_purchase_order_to_purchase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseReceipt',
            new_name='Receipt',
        ),
    ]
