# Generated by Django 5.2.8 on 2026-02-01 21:39

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_inventoryadjustmentprocessorrun_options_and_more'),
        ('transactions', '0025_rename_purchasereceipt_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('price_level', models.CharField(blank=True, db_column='price_level', max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.JSONField(blank=True, default=dict, null=True)),
                ('cost', models.JSONField(blank=True, default=dict, null=True)),
                ('tax', models.JSONField(blank=True, default=dict, null=True)),
                ('physical', models.JSONField(blank=True, default=dict, null=True)),
                ('lot', models.CharField(blank=True, help_text='Lot number', max_length=100)),
                ('serial_batch', models.CharField(blank=True, help_text='Serial or batch number', max_length=100)),
                ('adjustment_reason', models.CharField(blank=True, help_text='Reason for adjustment (cycle_count, damage, shrinkage, found, etc.)', max_length=50)),
            ],
            options={
                'db_table': 'inventory_receipt_line',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Overall notes for this receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text='Source purchase order (if source_type=purchase_receipt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='source_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('workorder_completion', 'WorkOrder Completion'), ('inventory_adjustment', 'Inventory Adjustment')], db_index=True, default='purchase_receipt', help_text='Type of receiving transaction', max_length=30),
        ),
        migrations.AddField(
            model_name='receipt',
            name='workorder',
            field=models.ForeignKey(blank=True, help_text='Source work order (if source_type=workorder_completion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='transactions.workorder'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['source_type', 'dt_received'], name='inventory_r_source__4401ab_idx'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='inventory_layer',
            field=models.ForeignKey(blank=True, help_text='Inventory layer/stack created for this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='products.inventorylayer'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='purchase_line',
            field=models.ForeignKey(blank=True, help_text='Source purchase line (if receipt from PO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='transactions.purchaseline'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse where inventory was received', on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='workorder_line',
            field=models.ForeignKey(blank=True, help_text='Source workorder line (if receipt from WO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='transactions.workorderline'),
        ),
        migrations.AddIndex(
            model_name='receiptline',
            index=models.Index(fields=['receipt', 'warehouse'], name='inventory_r_receipt_556bcf_idx'),
        ),
    ]
