# Generated by Django 5.2.8 on 2026-02-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_receipt_and_receiptline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receipt',
            new_name='receipt_source__840ee4_idx',
            old_name='inventory_r_source__4401ab_idx',
        ),
        migrations.RenameIndex(
            model_name='receiptline',
            new_name='receipt_lin_receipt_5c96c3_idx',
            old_name='inventory_r_receipt_556bcf_idx',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='receipt',
        ),
        migrations.AlterModelTable(
            name='receiptline',
            table='receipt_line',
        ),
    ]
