# Generated by Django 5.2.8 on 2026-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_add_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='orderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='line_type',
            field=models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount')], db_index=True, default='product', max_length=20),
        ),
    ]
