# Generated by Django 5.2.8 on 2026-02-04 04:22
# Fixed: DB columns already in correct state, use SeparateDatabaseAndState to fix Django state only

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_inventoryadjustmentprocessorrun_options_and_more'),
        ('transactions', '0027_rename_receipt_tables'),
    ]

    operations = [
        # DB is already in correct state, so we use SeparateDatabaseAndState
        # to update Django's internal state without touching the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='invoiceline',
                    name='invoice_id',
                    field=models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.invoice'),
                ),
                migrations.RenameField(
                    model_name='invoiceline',
                    old_name='invoice_id',
                    new_name='invoice',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='proposalline',
                    name='proposal_id',
                    field=models.ForeignKey(db_column='proposal_id', null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.proposal'),
                ),
                migrations.RenameField(
                    model_name='proposalline',
                    old_name='proposal_id',
                    new_name='proposal',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='workorderline',
                    name='workorder_id',
                    field=models.ForeignKey(db_column='workorder_id', null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.workorder'),
                ),
                migrations.RenameField(
                    model_name='workorderline',
                    old_name='workorder_id',
                    new_name='workorder',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where inventory was received', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
    ]
