# Generated by Django 5.2.8 on 2026-02-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_inventoryadjustmentprocessorrun_options_and_more'),
        ('transactions', '0027_rename_receipt_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='proposalline',
            name='proposal_id',
        ),
        migrations.RemoveField(
            model_name='workorderline',
            name='workorder_id',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.invoice'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='proposal',
            field=models.ForeignKey(db_column='proposal_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.proposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderline',
            name='workorder',
            field=models.ForeignKey(db_column='workorder_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.workorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where inventory was received', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='products.warehouse'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Type of the parent transaction', max_length=20, null=True),
        ),
    ]
