# Generated by Django 5.2.8 on 2026-02-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_remove_invoiceline_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='action',
        ),
        migrations.RemoveField(
            model_name='order',
            name='action',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='action',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='action',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='action',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
