# Generated by Django 5.2.8 on 2026-02-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_remove_invoice_action_remove_order_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.ForeignKey(blank=True, help_text='Invoice this payment is for (nullable for order-level deposits)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.invoice'),
        ),
    ]
