# Generated by Django 5.2.8 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_payment_nullable_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dt_kanban',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Next action / review date for prioritization', null=True),
        ),
    ]
