# Generated by Django 5.2.8 on 2026-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_add_times_used_dt_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='allocation_method',
            field=models.CharField(choices=[('value', 'By Value (cost-proportional)'), ('weight', 'By Weight'), ('quantity', 'By Quantity')], default='value', help_text='How to spread header costs across receipt lines', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='duty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total duties/tariffs for this inshipment', max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='handling',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total handling/insurance/non-product costs', max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total VAT for this inshipment', max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total vendor invoice amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vendor_invoice_freight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total freight on vendor invoice for this inshipment', max_digits=12),
        ),
    ]
