# Generated by Django 5.2.8 on 2026-02-13 23:31
# Hand-edited to use RenameField (preserves existing data).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_project_dt_kanban'),
    ]

    operations = [
        # Step 1: Rename the column (preserves existing data)
        migrations.RenameField(
            model_name='invoice',
            old_name='parent_type',
            new_name='parent_model',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='parent_type',
            new_name='parent_model',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='parent_type',
            new_name='parent_model',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='parent_type',
            new_name='parent_model',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='parent_type',
            new_name='parent_model',
        ),
        # Step 2: Update choices and help_text to match new model definition
        migrations.AlterField(
            model_name='invoice',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('sales_order', 'Sales Order'), ('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('workorder', 'Work Order'), ('requisition', 'Requisition')], db_index=True, help_text='Model of the parent transaction', max_length=20, null=True),
        ),
    ]
