# Generated by Django 5.2.8 on 2026-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining available amount for this payment.', max_digits=15),
        ),
    ]
