# Generated by Django 5.2.8 on 2026-02-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_rename_contact_id_orgbase_address_id_and_more'),
        ('products', '0011_remove_billofmaterial_parent_name_and_more'),
        ('transactions', '0034_invoice_conditions_description_invoice_conditions_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='terms_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='terms_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='terms_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='terms_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='transactions.paymentterm'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='transactions.paymentterm'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='transactions.paymentterm'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='transactions.paymentterm'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='requisitionline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_customer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_manufacturer', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_with_terms', to='transactions.paymentterm'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_vendor', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='item_fk',
            field=models.ForeignKey(blank=True, db_column='item_id_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='products.item'),
        ),
    ]
