# Generated by Django 5.2.8 on 2026-02-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_remove_invoice_contact_id_remove_invoice_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contact_id',
            field=models.ForeignKey(db_column='contact_id', help_text='Contact who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.ForeignKey(blank=True, db_column='invoice_id', help_text='Invoice this payment is for (nullable for order-level deposits)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.invoice'),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod_id',
            field=models.ForeignKey(blank=True, db_column='paymentmethod_id', help_text='Method of payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.paymentmethod'),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentmethod_id',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentterm_id',
            field=models.ForeignKey(blank=True, db_column='paymentterm_id', help_text='Payment term applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactions.paymentterm'),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentterm_id',
            new_name='payment_term',
        ),
        migrations.AlterField(
            model_name='paymentapplication',
            name='invoice_id',
            field=models.ForeignKey(db_column='invoice_id', help_text='The invoice receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='transactions.invoice'),
        ),
        migrations.RenameField(
            model_name='paymentapplication',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='paymentapplication',
            name='payment_id',
            field=models.ForeignKey(db_column='payment_id', help_text='The payment being applied', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transactions.payment'),
        ),
        migrations.RenameField(
            model_name='paymentapplication',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='requisition_id',
            field=models.ForeignKey(db_column='requisition_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.requisition'),
        ),
        migrations.RenameField(
            model_name='requisitionline',
            old_name='requisition_id',
            new_name='requisition',
        ),
        migrations.AlterUniqueTogether(
            name='paymentapplication',
            unique_together={('payment', 'invoice')},
        ),
    ]
