# Generated by Django 5.2.8 on 2026-08-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_add_payment_tendered_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='order',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized to GL. 0=editable, non-zero=locked.'),
        ),
    ]
