# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_payment_add_type_and_purchase 2'),
        ('transactions', '0008_add_commission_field 2'),
        ('transactions', '0009_rename_data_to_config 2'),
        ('transactions', '0010_stage1_invoice_type_payment_dedup 2'),
        ('transactions', '0011_add_source_name 2'),
        ('transactions', '0012_invoice_config_invoiceline_config_order_config_and_more 2'),
        ('transactions', '0013_project_timeline_hierarchy 2'),
        ('transactions', '0014_pendingpaymentapplication_config 2'),
        ('transactions', '0015_payment_add_category 2'),
        ('transactions', '0016_payment_nullable_for_entry 2'),
        ('transactions', '0017_payment_dt_default_now 2'),
        ('transactions', '0018_payment_customer_vendor_fk 2'),
        ('transactions', '0019_payment_method_charfield 2'),
        ('transactions', '0020_payment_drop_payment_method_fk 2'),
        ('transactions', '0021_statement_line 2'),
        ('transactions', '0022_statement_line_ledger 2'),
        ('transactions', '0023_proposal_dt_due 2'),
        ('transactions', '0024_add_dt_needed 2'),
        ('transactions', '0025_add_ship_via 2'),
        ('transactions', '0026_add_company 2'),
        ('transactions', '0027_add_line_type 2'),
        ('transactions', '0028_purpose_to_basemodel 2'),
        ('transactions', '0029_add_dt_approved 2'),
        ('transactions', '0030_add_times_used_dt_last_used 2'),
        ('transactions', '0031_receipt_landed_cost_fields 2'),
        ('transactions', '0032_project_gantt_weight 2'),
        ('transactions', '0033_add_commission_line_type_and_function_category 2'),
        ('transactions', '0034_add_payment_available 2'),
        ('transactions', '0035_add_payment_tendered_change 2'),
        ('transactions', '0036_dt_journaled_consolidation 2'),
        ('transactions', '0036_dt_journaled_consolidation'),
    ]

    operations = [
    ]
