"""Seed the country_master Setting — full ISO 3166-1 list.

Owned by WC_HQ, pushed via sync. Contains code, name, dial code,
alpha3, and address format hints (zip_label, state_label).

Run: python manage.py seed_country_master
"""
from django.core.management.base import BaseCommand
from django.db import transaction


COUNTRIES = {
    "AF": {"name": "Afghanistan", "dial": "93", "alpha3": "AFG", "zip_label": "Postal Code", "state_label": "Province"},
    "AL": {"name": "Albania", "dial": "355", "alpha3": "ALB", "zip_label": "Postal Code", "state_label": "County"},
    "DZ": {"name": "Algeria", "dial": "213", "alpha3": "DZA", "zip_label": "Code Postal", "state_label": "Province"},
    "AD": {"name": "Andorra", "dial": "376", "alpha3": "AND", "zip_label": "Postal Code", "state_label": "Parish"},
    "AO": {"name": "Angola", "dial": "244", "alpha3": "AGO", "zip_label": "Postal Code", "state_label": "Province"},
    "AG": {"name": "Antigua and Barbuda", "dial": "1268", "alpha3": "ATG", "zip_label": "Postal Code", "state_label": "Parish"},
    "AR": {"name": "Argentina", "dial": "54", "alpha3": "ARG", "zip_label": "CPA", "state_label": "Province"},
    "AM": {"name": "Armenia", "dial": "374", "alpha3": "ARM", "zip_label": "Postal Code", "state_label": "Province"},
    "AU": {"name": "Australia", "dial": "61", "alpha3": "AUS", "zip_label": "Postcode", "state_label": "State"},
    "AT": {"name": "Austria", "dial": "43", "alpha3": "AUT", "zip_label": "PLZ", "state_label": "Bundesland"},
    "AZ": {"name": "Azerbaijan", "dial": "994", "alpha3": "AZE", "zip_label": "Postal Code", "state_label": "District"},
    "BS": {"name": "Bahamas", "dial": "1242", "alpha3": "BHS", "zip_label": "Postal Code", "state_label": "Island"},
    "BH": {"name": "Bahrain", "dial": "973", "alpha3": "BHR", "zip_label": "Postal Code", "state_label": "Governorate"},
    "BD": {"name": "Bangladesh", "dial": "880", "alpha3": "BGD", "zip_label": "Postal Code", "state_label": "Division"},
    "BB": {"name": "Barbados", "dial": "1246", "alpha3": "BRB", "zip_label": "Postal Code", "state_label": "Parish"},
    "BY": {"name": "Belarus", "dial": "375", "alpha3": "BLR", "zip_label": "Postal Code", "state_label": "Oblast"},
    "BE": {"name": "Belgium", "dial": "32", "alpha3": "BEL", "zip_label": "Code Postal", "state_label": "Province"},
    "BZ": {"name": "Belize", "dial": "501", "alpha3": "BLZ", "zip_label": "Postal Code", "state_label": "District"},
    "BJ": {"name": "Benin", "dial": "229", "alpha3": "BEN", "zip_label": "Postal Code", "state_label": "Department"},
    "BT": {"name": "Bhutan", "dial": "975", "alpha3": "BTN", "zip_label": "Postal Code", "state_label": "District"},
    "BO": {"name": "Bolivia", "dial": "591", "alpha3": "BOL", "zip_label": "Postal Code", "state_label": "Department"},
    "BA": {"name": "Bosnia and Herzegovina", "dial": "387", "alpha3": "BIH", "zip_label": "Postal Code", "state_label": "Entity"},
    "BW": {"name": "Botswana", "dial": "267", "alpha3": "BWA", "zip_label": "Postal Code", "state_label": "District"},
    "BR": {"name": "Brazil", "dial": "55", "alpha3": "BRA", "zip_label": "CEP", "state_label": "Estado"},
    "BN": {"name": "Brunei", "dial": "673", "alpha3": "BRN", "zip_label": "Postal Code", "state_label": "District"},
    "BG": {"name": "Bulgaria", "dial": "359", "alpha3": "BGR", "zip_label": "Postal Code", "state_label": "Province"},
    "BF": {"name": "Burkina Faso", "dial": "226", "alpha3": "BFA", "zip_label": "Postal Code", "state_label": "Region"},
    "BI": {"name": "Burundi", "dial": "257", "alpha3": "BDI", "zip_label": "Postal Code", "state_label": "Province"},
    "KH": {"name": "Cambodia", "dial": "855", "alpha3": "KHM", "zip_label": "Postal Code", "state_label": "Province"},
    "CM": {"name": "Cameroon", "dial": "237", "alpha3": "CMR", "zip_label": "Postal Code", "state_label": "Region"},
    "CA": {"name": "Canada", "dial": "1", "alpha3": "CAN", "zip_label": "Postal Code", "state_label": "Province"},
    "CV": {"name": "Cape Verde", "dial": "238", "alpha3": "CPV", "zip_label": "Postal Code", "state_label": "Municipality"},
    "CF": {"name": "Central African Republic", "dial": "236", "alpha3": "CAF", "zip_label": "Postal Code", "state_label": "Prefecture"},
    "TD": {"name": "Chad", "dial": "235", "alpha3": "TCD", "zip_label": "Postal Code", "state_label": "Region"},
    "CL": {"name": "Chile", "dial": "56", "alpha3": "CHL", "zip_label": "Postal Code", "state_label": "Region"},
    "CN": {"name": "China", "dial": "86", "alpha3": "CHN", "zip_label": "Postal Code", "state_label": "Province"},
    "CO": {"name": "Colombia", "dial": "57", "alpha3": "COL", "zip_label": "Postal Code", "state_label": "Department"},
    "KM": {"name": "Comoros", "dial": "269", "alpha3": "COM", "zip_label": "Postal Code", "state_label": "Island"},
    "CG": {"name": "Congo", "dial": "242", "alpha3": "COG", "zip_label": "Postal Code", "state_label": "Department"},
    "CD": {"name": "Congo (DRC)", "dial": "243", "alpha3": "COD", "zip_label": "Postal Code", "state_label": "Province"},
    "CR": {"name": "Costa Rica", "dial": "506", "alpha3": "CRI", "zip_label": "Postal Code", "state_label": "Province"},
    "HR": {"name": "Croatia", "dial": "385", "alpha3": "HRV", "zip_label": "Postal Code", "state_label": "County"},
    "CU": {"name": "Cuba", "dial": "53", "alpha3": "CUB", "zip_label": "Postal Code", "state_label": "Province"},
    "CY": {"name": "Cyprus", "dial": "357", "alpha3": "CYP", "zip_label": "Postal Code", "state_label": "District"},
    "CZ": {"name": "Czech Republic", "dial": "420", "alpha3": "CZE", "zip_label": "PSC", "state_label": "Region"},
    "DK": {"name": "Denmark", "dial": "45", "alpha3": "DNK", "zip_label": "Postnummer", "state_label": "Region"},
    "DJ": {"name": "Djibouti", "dial": "253", "alpha3": "DJI", "zip_label": "Postal Code", "state_label": "Region"},
    "DM": {"name": "Dominica", "dial": "1767", "alpha3": "DMA", "zip_label": "Postal Code", "state_label": "Parish"},
    "DO": {"name": "Dominican Republic", "dial": "1809", "alpha3": "DOM", "zip_label": "Postal Code", "state_label": "Province"},
    "EC": {"name": "Ecuador", "dial": "593", "alpha3": "ECU", "zip_label": "Postal Code", "state_label": "Province"},
    "EG": {"name": "Egypt", "dial": "20", "alpha3": "EGY", "zip_label": "Postal Code", "state_label": "Governorate"},
    "SV": {"name": "El Salvador", "dial": "503", "alpha3": "SLV", "zip_label": "Postal Code", "state_label": "Department"},
    "GQ": {"name": "Equatorial Guinea", "dial": "240", "alpha3": "GNQ", "zip_label": "Postal Code", "state_label": "Province"},
    "ER": {"name": "Eritrea", "dial": "291", "alpha3": "ERI", "zip_label": "Postal Code", "state_label": "Region"},
    "EE": {"name": "Estonia", "dial": "372", "alpha3": "EST", "zip_label": "Postal Code", "state_label": "County"},
    "SZ": {"name": "Eswatini", "dial": "268", "alpha3": "SWZ", "zip_label": "Postal Code", "state_label": "District"},
    "ET": {"name": "Ethiopia", "dial": "251", "alpha3": "ETH", "zip_label": "Postal Code", "state_label": "Region"},
    "FJ": {"name": "Fiji", "dial": "679", "alpha3": "FJI", "zip_label": "Postal Code", "state_label": "Division"},
    "FI": {"name": "Finland", "dial": "358", "alpha3": "FIN", "zip_label": "Postinumero", "state_label": "Region"},
    "FR": {"name": "France", "dial": "33", "alpha3": "FRA", "zip_label": "Code Postal", "state_label": "Region"},
    "GA": {"name": "Gabon", "dial": "241", "alpha3": "GAB", "zip_label": "Postal Code", "state_label": "Province"},
    "GM": {"name": "Gambia", "dial": "220", "alpha3": "GMB", "zip_label": "Postal Code", "state_label": "Division"},
    "GE": {"name": "Georgia", "dial": "995", "alpha3": "GEO", "zip_label": "Postal Code", "state_label": "Region"},
    "DE": {"name": "Germany", "dial": "49", "alpha3": "DEU", "zip_label": "PLZ", "state_label": "Bundesland"},
    "GH": {"name": "Ghana", "dial": "233", "alpha3": "GHA", "zip_label": "Postal Code", "state_label": "Region"},
    "GR": {"name": "Greece", "dial": "30", "alpha3": "GRC", "zip_label": "TK", "state_label": "Region"},
    "GD": {"name": "Grenada", "dial": "1473", "alpha3": "GRD", "zip_label": "Postal Code", "state_label": "Parish"},
    "GT": {"name": "Guatemala", "dial": "502", "alpha3": "GTM", "zip_label": "Postal Code", "state_label": "Department"},
    "GN": {"name": "Guinea", "dial": "224", "alpha3": "GIN", "zip_label": "Postal Code", "state_label": "Region"},
    "GW": {"name": "Guinea-Bissau", "dial": "245", "alpha3": "GNB", "zip_label": "Postal Code", "state_label": "Region"},
    "GY": {"name": "Guyana", "dial": "592", "alpha3": "GUY", "zip_label": "Postal Code", "state_label": "Region"},
    "HT": {"name": "Haiti", "dial": "509", "alpha3": "HTI", "zip_label": "Code Postal", "state_label": "Department"},
    "HN": {"name": "Honduras", "dial": "504", "alpha3": "HND", "zip_label": "Postal Code", "state_label": "Department"},
    "HU": {"name": "Hungary", "dial": "36", "alpha3": "HUN", "zip_label": "Postal Code", "state_label": "County"},
    "IS": {"name": "Iceland", "dial": "354", "alpha3": "ISL", "zip_label": "Postal Code", "state_label": "Region"},
    "IN": {"name": "India", "dial": "91", "alpha3": "IND", "zip_label": "PIN", "state_label": "State"},
    "ID": {"name": "Indonesia", "dial": "62", "alpha3": "IDN", "zip_label": "Kode Pos", "state_label": "Province"},
    "IR": {"name": "Iran", "dial": "98", "alpha3": "IRN", "zip_label": "Postal Code", "state_label": "Province"},
    "IQ": {"name": "Iraq", "dial": "964", "alpha3": "IRQ", "zip_label": "Postal Code", "state_label": "Governorate"},
    "IE": {"name": "Ireland", "dial": "353", "alpha3": "IRL", "zip_label": "Eircode", "state_label": "County"},
    "IL": {"name": "Israel", "dial": "972", "alpha3": "ISR", "zip_label": "Postal Code", "state_label": "District"},
    "IT": {"name": "Italy", "dial": "39", "alpha3": "ITA", "zip_label": "CAP", "state_label": "Provincia"},
    "CI": {"name": "Ivory Coast", "dial": "225", "alpha3": "CIV", "zip_label": "Postal Code", "state_label": "District"},
    "JM": {"name": "Jamaica", "dial": "1876", "alpha3": "JAM", "zip_label": "Postal Code", "state_label": "Parish"},
    "JP": {"name": "Japan", "dial": "81", "alpha3": "JPN", "zip_label": "\u3012", "state_label": "Prefecture"},
    "JO": {"name": "Jordan", "dial": "962", "alpha3": "JOR", "zip_label": "Postal Code", "state_label": "Governorate"},
    "KZ": {"name": "Kazakhstan", "dial": "7", "alpha3": "KAZ", "zip_label": "Postal Code", "state_label": "Region"},
    "KE": {"name": "Kenya", "dial": "254", "alpha3": "KEN", "zip_label": "Postal Code", "state_label": "County"},
    "KI": {"name": "Kiribati", "dial": "686", "alpha3": "KIR", "zip_label": "Postal Code", "state_label": "Island"},
    "KW": {"name": "Kuwait", "dial": "965", "alpha3": "KWT", "zip_label": "Postal Code", "state_label": "Governorate"},
    "KG": {"name": "Kyrgyzstan", "dial": "996", "alpha3": "KGZ", "zip_label": "Postal Code", "state_label": "Region"},
    "LA": {"name": "Laos", "dial": "856", "alpha3": "LAO", "zip_label": "Postal Code", "state_label": "Province"},
    "LV": {"name": "Latvia", "dial": "371", "alpha3": "LVA", "zip_label": "Postal Code", "state_label": "Municipality"},
    "LB": {"name": "Lebanon", "dial": "961", "alpha3": "LBN", "zip_label": "Postal Code", "state_label": "Governorate"},
    "LS": {"name": "Lesotho", "dial": "266", "alpha3": "LSO", "zip_label": "Postal Code", "state_label": "District"},
    "LR": {"name": "Liberia", "dial": "231", "alpha3": "LBR", "zip_label": "Postal Code", "state_label": "County"},
    "LY": {"name": "Libya", "dial": "218", "alpha3": "LBY", "zip_label": "Postal Code", "state_label": "District"},
    "LI": {"name": "Liechtenstein", "dial": "423", "alpha3": "LIE", "zip_label": "PLZ", "state_label": "Municipality"},
    "LT": {"name": "Lithuania", "dial": "370", "alpha3": "LTU", "zip_label": "Postal Code", "state_label": "County"},
    "LU": {"name": "Luxembourg", "dial": "352", "alpha3": "LUX", "zip_label": "Code Postal", "state_label": "Canton"},
    "MG": {"name": "Madagascar", "dial": "261", "alpha3": "MDG", "zip_label": "Postal Code", "state_label": "Province"},
    "MW": {"name": "Malawi", "dial": "265", "alpha3": "MWI", "zip_label": "Postal Code", "state_label": "District"},
    "MY": {"name": "Malaysia", "dial": "60", "alpha3": "MYS", "zip_label": "Poskod", "state_label": "State"},
    "MV": {"name": "Maldives", "dial": "960", "alpha3": "MDV", "zip_label": "Postal Code", "state_label": "Atoll"},
    "ML": {"name": "Mali", "dial": "223", "alpha3": "MLI", "zip_label": "Postal Code", "state_label": "Region"},
    "MT": {"name": "Malta", "dial": "356", "alpha3": "MLT", "zip_label": "Postal Code", "state_label": "District"},
    "MH": {"name": "Marshall Islands", "dial": "692", "alpha3": "MHL", "zip_label": "ZIP", "state_label": "Atoll"},
    "MR": {"name": "Mauritania", "dial": "222", "alpha3": "MRT", "zip_label": "Postal Code", "state_label": "Region"},
    "MU": {"name": "Mauritius", "dial": "230", "alpha3": "MUS", "zip_label": "Postal Code", "state_label": "District"},
    "MX": {"name": "Mexico", "dial": "52", "alpha3": "MEX", "zip_label": "C.P.", "state_label": "Estado"},
    "FM": {"name": "Micronesia", "dial": "691", "alpha3": "FSM", "zip_label": "ZIP", "state_label": "State"},
    "MD": {"name": "Moldova", "dial": "373", "alpha3": "MDA", "zip_label": "Postal Code", "state_label": "District"},
    "MC": {"name": "Monaco", "dial": "377", "alpha3": "MCO", "zip_label": "Code Postal", "state_label": "Quarter"},
    "MN": {"name": "Mongolia", "dial": "976", "alpha3": "MNG", "zip_label": "Postal Code", "state_label": "Province"},
    "ME": {"name": "Montenegro", "dial": "382", "alpha3": "MNE", "zip_label": "Postal Code", "state_label": "Municipality"},
    "MA": {"name": "Morocco", "dial": "212", "alpha3": "MAR", "zip_label": "Code Postal", "state_label": "Region"},
    "MZ": {"name": "Mozambique", "dial": "258", "alpha3": "MOZ", "zip_label": "Postal Code", "state_label": "Province"},
    "MM": {"name": "Myanmar", "dial": "95", "alpha3": "MMR", "zip_label": "Postal Code", "state_label": "State/Region"},
    "NA": {"name": "Namibia", "dial": "264", "alpha3": "NAM", "zip_label": "Postal Code", "state_label": "Region"},
    "NR": {"name": "Nauru", "dial": "674", "alpha3": "NRU", "zip_label": "Postal Code", "state_label": "District"},
    "NP": {"name": "Nepal", "dial": "977", "alpha3": "NPL", "zip_label": "Postal Code", "state_label": "Province"},
    "NL": {"name": "Netherlands", "dial": "31", "alpha3": "NLD", "zip_label": "Postcode", "state_label": "Provincie"},
    "NZ": {"name": "New Zealand", "dial": "64", "alpha3": "NZL", "zip_label": "Postcode", "state_label": "Region"},
    "NI": {"name": "Nicaragua", "dial": "505", "alpha3": "NIC", "zip_label": "Postal Code", "state_label": "Department"},
    "NE": {"name": "Niger", "dial": "227", "alpha3": "NER", "zip_label": "Postal Code", "state_label": "Region"},
    "NG": {"name": "Nigeria", "dial": "234", "alpha3": "NGA", "zip_label": "Postal Code", "state_label": "State"},
    "KP": {"name": "North Korea", "dial": "850", "alpha3": "PRK", "zip_label": "Postal Code", "state_label": "Province"},
    "MK": {"name": "North Macedonia", "dial": "389", "alpha3": "MKD", "zip_label": "Postal Code", "state_label": "Municipality"},
    "NO": {"name": "Norway", "dial": "47", "alpha3": "NOR", "zip_label": "Postnummer", "state_label": "County"},
    "OM": {"name": "Oman", "dial": "968", "alpha3": "OMN", "zip_label": "Postal Code", "state_label": "Governorate"},
    "PK": {"name": "Pakistan", "dial": "92", "alpha3": "PAK", "zip_label": "Postal Code", "state_label": "Province"},
    "PW": {"name": "Palau", "dial": "680", "alpha3": "PLW", "zip_label": "ZIP", "state_label": "State"},
    "PS": {"name": "Palestine", "dial": "970", "alpha3": "PSE", "zip_label": "Postal Code", "state_label": "Governorate"},
    "PA": {"name": "Panama", "dial": "507", "alpha3": "PAN", "zip_label": "Postal Code", "state_label": "Province"},
    "PG": {"name": "Papua New Guinea", "dial": "675", "alpha3": "PNG", "zip_label": "Postal Code", "state_label": "Province"},
    "PY": {"name": "Paraguay", "dial": "595", "alpha3": "PRY", "zip_label": "Postal Code", "state_label": "Department"},
    "PE": {"name": "Peru", "dial": "51", "alpha3": "PER", "zip_label": "Postal Code", "state_label": "Department"},
    "PH": {"name": "Philippines", "dial": "63", "alpha3": "PHL", "zip_label": "ZIP", "state_label": "Province"},
    "PL": {"name": "Poland", "dial": "48", "alpha3": "POL", "zip_label": "Kod Pocztowy", "state_label": "Voivodeship"},
    "PT": {"name": "Portugal", "dial": "351", "alpha3": "PRT", "zip_label": "Codigo Postal", "state_label": "District"},
    "QA": {"name": "Qatar", "dial": "974", "alpha3": "QAT", "zip_label": "Postal Code", "state_label": "Municipality"},
    "RO": {"name": "Romania", "dial": "40", "alpha3": "ROU", "zip_label": "Cod Postal", "state_label": "County"},
    "RU": {"name": "Russia", "dial": "7", "alpha3": "RUS", "zip_label": "Postal Code", "state_label": "Oblast"},
    "RW": {"name": "Rwanda", "dial": "250", "alpha3": "RWA", "zip_label": "Postal Code", "state_label": "Province"},
    "KN": {"name": "Saint Kitts and Nevis", "dial": "1869", "alpha3": "KNA", "zip_label": "Postal Code", "state_label": "Parish"},
    "LC": {"name": "Saint Lucia", "dial": "1758", "alpha3": "LCA", "zip_label": "Postal Code", "state_label": "Quarter"},
    "VC": {"name": "Saint Vincent", "dial": "1784", "alpha3": "VCT", "zip_label": "Postal Code", "state_label": "Parish"},
    "WS": {"name": "Samoa", "dial": "685", "alpha3": "WSM", "zip_label": "Postal Code", "state_label": "District"},
    "SM": {"name": "San Marino", "dial": "378", "alpha3": "SMR", "zip_label": "CAP", "state_label": "Municipality"},
    "ST": {"name": "Sao Tome and Principe", "dial": "239", "alpha3": "STP", "zip_label": "Postal Code", "state_label": "District"},
    "SA": {"name": "Saudi Arabia", "dial": "966", "alpha3": "SAU", "zip_label": "Postal Code", "state_label": "Region"},
    "SN": {"name": "Senegal", "dial": "221", "alpha3": "SEN", "zip_label": "Code Postal", "state_label": "Region"},
    "RS": {"name": "Serbia", "dial": "381", "alpha3": "SRB", "zip_label": "Postal Code", "state_label": "District"},
    "SC": {"name": "Seychelles", "dial": "248", "alpha3": "SYC", "zip_label": "Postal Code", "state_label": "District"},
    "SL": {"name": "Sierra Leone", "dial": "232", "alpha3": "SLE", "zip_label": "Postal Code", "state_label": "District"},
    "SG": {"name": "Singapore", "dial": "65", "alpha3": "SGP", "zip_label": "Postal Code", "state_label": "District"},
    "SK": {"name": "Slovakia", "dial": "421", "alpha3": "SVK", "zip_label": "PSC", "state_label": "Region"},
    "SI": {"name": "Slovenia", "dial": "386", "alpha3": "SVN", "zip_label": "Postal Code", "state_label": "Municipality"},
    "SB": {"name": "Solomon Islands", "dial": "677", "alpha3": "SLB", "zip_label": "Postal Code", "state_label": "Province"},
    "SO": {"name": "Somalia", "dial": "252", "alpha3": "SOM", "zip_label": "Postal Code", "state_label": "Region"},
    "ZA": {"name": "South Africa", "dial": "27", "alpha3": "ZAF", "zip_label": "Postal Code", "state_label": "Province"},
    "KR": {"name": "South Korea", "dial": "82", "alpha3": "KOR", "zip_label": "Postal Code", "state_label": "Province"},
    "SS": {"name": "South Sudan", "dial": "211", "alpha3": "SSD", "zip_label": "Postal Code", "state_label": "State"},
    "ES": {"name": "Spain", "dial": "34", "alpha3": "ESP", "zip_label": "Codigo Postal", "state_label": "Provincia"},
    "LK": {"name": "Sri Lanka", "dial": "94", "alpha3": "LKA", "zip_label": "Postal Code", "state_label": "Province"},
    "SD": {"name": "Sudan", "dial": "249", "alpha3": "SDN", "zip_label": "Postal Code", "state_label": "State"},
    "SR": {"name": "Suriname", "dial": "597", "alpha3": "SUR", "zip_label": "Postal Code", "state_label": "District"},
    "SE": {"name": "Sweden", "dial": "46", "alpha3": "SWE", "zip_label": "Postnummer", "state_label": "Lan"},
    "CH": {"name": "Switzerland", "dial": "41", "alpha3": "CHE", "zip_label": "PLZ", "state_label": "Kanton"},
    "SY": {"name": "Syria", "dial": "963", "alpha3": "SYR", "zip_label": "Postal Code", "state_label": "Governorate"},
    "TW": {"name": "Taiwan", "dial": "886", "alpha3": "TWN", "zip_label": "Postal Code", "state_label": "County/City"},
    "TJ": {"name": "Tajikistan", "dial": "992", "alpha3": "TJK", "zip_label": "Postal Code", "state_label": "Region"},
    "TZ": {"name": "Tanzania", "dial": "255", "alpha3": "TZA", "zip_label": "Postal Code", "state_label": "Region"},
    "TH": {"name": "Thailand", "dial": "66", "alpha3": "THA", "zip_label": "Postal Code", "state_label": "Province"},
    "TL": {"name": "Timor-Leste", "dial": "670", "alpha3": "TLS", "zip_label": "Postal Code", "state_label": "District"},
    "TG": {"name": "Togo", "dial": "228", "alpha3": "TGO", "zip_label": "Postal Code", "state_label": "Region"},
    "TO": {"name": "Tonga", "dial": "676", "alpha3": "TON", "zip_label": "Postal Code", "state_label": "Division"},
    "TT": {"name": "Trinidad and Tobago", "dial": "1868", "alpha3": "TTO", "zip_label": "Postal Code", "state_label": "Region"},
    "TN": {"name": "Tunisia", "dial": "216", "alpha3": "TUN", "zip_label": "Code Postal", "state_label": "Governorate"},
    "TR": {"name": "Turkey", "dial": "90", "alpha3": "TUR", "zip_label": "Posta Kodu", "state_label": "Province"},
    "TM": {"name": "Turkmenistan", "dial": "993", "alpha3": "TKM", "zip_label": "Postal Code", "state_label": "Province"},
    "TV": {"name": "Tuvalu", "dial": "688", "alpha3": "TUV", "zip_label": "Postal Code", "state_label": "Island"},
    "UG": {"name": "Uganda", "dial": "256", "alpha3": "UGA", "zip_label": "Postal Code", "state_label": "District"},
    "UA": {"name": "Ukraine", "dial": "380", "alpha3": "UKR", "zip_label": "Postal Code", "state_label": "Oblast"},
    "AE": {"name": "United Arab Emirates", "dial": "971", "alpha3": "ARE", "zip_label": "Postal Code", "state_label": "Emirate"},
    "GB": {"name": "United Kingdom", "dial": "44", "alpha3": "GBR", "zip_label": "Postcode", "state_label": "County"},
    "US": {"name": "United States", "dial": "1", "alpha3": "USA", "zip_label": "ZIP", "state_label": "State"},
    "UY": {"name": "Uruguay", "dial": "598", "alpha3": "URY", "zip_label": "Postal Code", "state_label": "Department"},
    "UZ": {"name": "Uzbekistan", "dial": "998", "alpha3": "UZB", "zip_label": "Postal Code", "state_label": "Region"},
    "VU": {"name": "Vanuatu", "dial": "678", "alpha3": "VUT", "zip_label": "Postal Code", "state_label": "Province"},
    "VA": {"name": "Vatican City", "dial": "379", "alpha3": "VAT", "zip_label": "CAP", "state_label": ""},
    "VE": {"name": "Venezuela", "dial": "58", "alpha3": "VEN", "zip_label": "Postal Code", "state_label": "State"},
    "VN": {"name": "Vietnam", "dial": "84", "alpha3": "VNM", "zip_label": "Postal Code", "state_label": "Province"},
    "YE": {"name": "Yemen", "dial": "967", "alpha3": "YEM", "zip_label": "Postal Code", "state_label": "Governorate"},
    "ZM": {"name": "Zambia", "dial": "260", "alpha3": "ZMB", "zip_label": "Postal Code", "state_label": "Province"},
    "ZW": {"name": "Zimbabwe", "dial": "263", "alpha3": "ZWE", "zip_label": "Postal Code", "state_label": "Province"},
    # Territories
    "PR": {"name": "Puerto Rico", "dial": "1787", "alpha3": "PRI", "zip_label": "ZIP", "state_label": "Municipality"},
    "GU": {"name": "Guam", "dial": "1671", "alpha3": "GUM", "zip_label": "ZIP", "state_label": "Village"},
    "VI": {"name": "US Virgin Islands", "dial": "1340", "alpha3": "VIR", "zip_label": "ZIP", "state_label": "Island"},
    "AS": {"name": "American Samoa", "dial": "1684", "alpha3": "ASM", "zip_label": "ZIP", "state_label": "District"},
    "HK": {"name": "Hong Kong", "dial": "852", "alpha3": "HKG", "zip_label": "", "state_label": "District"},
    "MO": {"name": "Macau", "dial": "853", "alpha3": "MAC", "zip_label": "", "state_label": "Parish"},
}


class Command(BaseCommand):
    help = "Seed country_master Setting — WC_HQ owned, pushed via sync."

    def handle(self, *args, **options):
        from apps.core.models import Setting

        with transaction.atomic():
            setting, created = Setting.objects.get_or_create(
                name='country_master',
                purpose='system',
                defaults={
                    'ida': 'country_master',
                    'scope': 'system',
                    'config': COUNTRIES,
                    'prefs': {'version': 1, 'source': 'WC_HQ', 'count': len(COUNTRIES)},
                },
            )
            if not created:
                setting.config = COUNTRIES
                setting.prefs = {'version': 1, 'source': 'WC_HQ', 'count': len(COUNTRIES)}
                setting.save()

        action = 'Created' if created else 'Updated'
        self.stdout.write(self.style.SUCCESS(
            f"{action} country_master Setting: {len(COUNTRIES)} countries"
        ))
