# Generated by Django 5.2.8 on 2026-02-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.invoice'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='term',
            field=models.ForeignKey(blank=True, db_column='term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.term'),
        ),
    ]
