# Generated by Django 5.2.8 on 2026-08-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='erosion',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Rep or salesperson responsible (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erosion_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
