# Generated by Django 5.2.8 on 2026-08-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('orgs', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='erosion',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Customer or vendor associated with this erosion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erosion_events', to='orgs.orgbase'),
        ),
        migrations.AddIndex(
            model_name='gljournal',
            index=models.Index(fields=['batch_id', 'account'], name='glj_batch_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='gljournal',
            index=models.Index(fields=['division', 'dt_journaled'], name='glj_div_journaled_idx'),
        ),
        migrations.AddField(
            model_name='journalbatch',
            name='run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledger',
            name='gl_account',
            field=models.ForeignKey(blank=True, db_column='gl_account_id', help_text='GL account for FX gain/loss applied to this entry, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.glaccount'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.invoice'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org_id', help_text='Org (customer/vendor) for fast aging queries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='term',
            field=models.ForeignKey(blank=True, db_column='term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.term'),
        ),
        migrations.AddIndex(
            model_name='erosion',
            index=models.Index(fields=['org', 'category'], name='idx_erosion_org_cat'),
        ),
        migrations.AddIndex(
            model_name='erosion',
            index=models.Index(fields=['org', 'dt_event'], name='idx_erosion_org_date'),
        ),
        migrations.AddIndex(
            model_name='erosion',
            index=models.Index(fields=['source_model', 'source_id'], name='idx_erosion_source'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['org', 'model_name'], name='idx_ledger_org_model'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['org', 'dt_due'], name='idx_ledger_org_due'),
        ),
    ]
