# Generated by Django 5.2.8 on 2026-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erosion',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gljournal',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taxjurisdiction',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
    ]
