# Generated by Django 5.2.8 on 2026-09-11 12:16

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_journalbatch_status'),
        ('sync', '0003_add_bundle_model_name'),
        ('transactions', '0008_purchase_capital_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='category',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('receivables', 'Accounts Receivable'), ('payables', 'Accounts Payable'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed Assets'), ('depreciation', 'Depreciation'), ('sales', 'Sales'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('other', 'Other')], help_text='Account category for grouping', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('period', models.CharField(db_index=True, help_text='Period label (e.g., 2026-10, w41_2026, q3_2026 — user-defined)', max_length=20)),
                ('dt_period_start', models.BigIntegerField(db_index=True, default=0, help_text='Period start UTC epoch ms')),
                ('dt_period_end', models.BigIntegerField(db_index=True, default=0, help_text='Period end UTC epoch ms')),
                ('account', models.CharField(db_index=True, help_text='GL account ida (e.g., 6100-SALARY, 6400-TRAVEL)', max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount for this account/period', max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount for this account/period', max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('dt_journaled', models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when locked. 0=editable, non-zero=locked.')),
                ('bundle', models.ForeignKey(blank=True, db_column='bundle_id', help_text='Bundle that imported this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_entries', to='sync.bundle')),
                ('purchase', models.ForeignKey(blank=True, db_column='purchase_id', help_text='Capital asset Purchase (depreciation entries only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='transactions.purchase')),
            ],
            options={
                'db_table': 'budgets',
                'indexes': [models.Index(fields=['period', 'account'], name='idx_budget_period_acct'), models.Index(fields=['dt_period_start', 'dt_period_end'], name='idx_budget_dt_range'), models.Index(fields=['period', 'dt_journaled'], name='idx_budget_period_locked')],
            },
        ),
    ]
