# Generated by Django 5.2.8 on 2026-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_budget_rename_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erosion',
            name='notes',
        ),
        migrations.AlterField(
            model_name='budget',
            name='account_debit',
            field=models.CharField(db_index=True, help_text='GL account being debited (e.g., 6100-SALARY)', max_length=255),
        ),
        migrations.AlterField(
            model_name='budget',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit amount — must equal debit for a balanced entry', max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Debit amount', max_digits=12),
        ),
    ]
