# Generated by Django 5.2.8 on 2026-06-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_enforce_unique_gl_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gljournal',
            name='source_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='source_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
