# Generated by Django 5.2.8 on 2026-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_erosion_notes_alter_budget_account_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='category',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('receivables', 'Accounts Receivable'), ('prepaid', 'Prepaid'), ('payables', 'Accounts Payable'), ('tax', 'Tax'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed Assets'), ('depreciation', 'Depreciation'), ('equity', 'Equity'), ('sales', 'Sales'), ('contra', 'Contra Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('other', 'Other')], help_text='Account category for grouping', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='used_for',
            field=models.CharField(blank=True, choices=[('posting', 'Posting'), ('reporting', 'Reporting (computed, never posted)'), ('cash', 'Cash'), ('receivables', 'Receivables'), ('payables', 'Payables'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('discounts', 'Discounts'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('tax', 'Tax'), ('consolidation', 'Consolidation'), ('other', 'Other')], help_text='Account usage classification', max_length=255, null=True),
        ),
    ]
