# Generated by Django 5.2.8 on 2026-09-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_glaccount_chart_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosion',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('proposal', 'Proposal'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('credit_memo', 'Credit Memo'), ('action', 'Action'), ('question_answer', 'Question / Answer')], help_text='Transaction type being compared (e.g., proposal for margin erosion on invoice)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erosion',
            name='source_model',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('credit_memo', 'Credit Memo'), ('action', 'Action'), ('question_answer', 'Question / Answer')], help_text='Transaction type where erosion was detected', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='batch_type',
            field=models.CharField(choices=[('full', 'Full Batch'), ('invoice', 'Invoices Only'), ('cash', 'Cash Only'), ('purchase', 'Purchases Only')], default='full', max_length=32),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='dt_applied',
            field=models.DateTimeField(blank=True, help_text='When cash was applied (settled). Record remains editable. Non-null = settled.', null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='model_name',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('credit_memo', 'Credit Memo'), ('debit_memo', 'Debit Memo'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='source',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('cash', 'Cash'), ('journal', 'Journal Entry'), ('adjustment', 'Adjustment'), ('import', 'Imported'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='value_available',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current unpaid balance (mutable by cash_entries)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='days_due',
            field=models.IntegerField(blank=True, help_text='Days until cash due (from invoice or dt_begin)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='discount_rate',
            field=models.FloatField(blank=True, help_text='Early cash discount percentage (e.g., 2.0 for 2%)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='period_count',
            field=models.IntegerField(blank=True, help_text='Number of cash installments (1=single cash)', null=True),
        ),

        migrations.AlterField(
            model_name='ledger',
            name='value_available',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current unpaid balance (changed as cash is applied)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='discount_rate',
            field=models.FloatField(blank=True, help_text='Early-payment discount percentage (e.g., 2.0 for 2%)', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='period_count',
            field=models.IntegerField(blank=True, help_text='Number of installments (1=single installment)', null=True),
        ),
    ]
