# Generated by Django 5.2.8 on 2026-07-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gl_journal_division_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glaccount',
            name='uniq_active_gl_account_account_number',
        ),
        migrations.RemoveField(
            model_name='glaccount',
            name='account_number',
        ),
    ]
