# Generated by Django 5.2.8 on 2026-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cash_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erosion',
            name='parent_model',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('credit_memo', 'Credit Memo'), ('action', 'Action'), ('question_answer', 'Question / Answer')], help_text='Transaction type being compared (e.g., quote for margin erosion on invoice)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erosion',
            name='source_model',
            field=models.CharField(choices=[('quote', 'Quote'), ('order', 'Order'), ('invoice', 'Invoice'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('credit_memo', 'Credit Memo'), ('action', 'Action'), ('question_answer', 'Question / Answer')], help_text='Transaction type where erosion was detected', max_length=50),
        ),
    ]
