# Generated by Django 5.2.8 on 2026-09-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_erosion_parent_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='dt_applied',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='dt_journaled',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_cleared',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_void',
        ),
    ]
