# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_prune_ledger_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='erosion',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='glaccount',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='gljournal',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='journalbatch',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='taxjurisdiction',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_deleted',
        ),
    ]
