# Generated by Django 5.2.8 on 2026-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_audit_is_deleted_remove_budget_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='category',
            field=models.CharField(blank=True, choices=[('cash', 'Cash & Bank'), ('receivables', 'Receivables'), ('inventory', 'Inventory'), ('other_current_assets', 'Prepaid & Other Current Assets'), ('fixed_assets', 'Property & Equipment'), ('current_liabilities', 'Current Liabilities'), ('long_term_liabilities', 'Long-Term Liabilities'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of Sales'), ('operating_expenses', 'Operating Expenses'), ('other', 'Other Income & Expense')], help_text='Account category for grouping', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('asset', 'Asset'), ('contra_asset', 'Contra Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('contra_equity', 'Contra Equity'), ('revenue', 'Revenue'), ('contra_revenue', 'Contra Revenue'), ('cost_of_sales', 'Cost of Sales'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], help_text='Account type (asset, liability, equity, revenue, expense)', max_length=255, null=True),
        ),
    ]
