# Generated by Django 5.2.8 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_purpose_to_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='currency',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='erosion',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='term',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
    ]
