# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_comments_flat_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='erosion',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='glaccount',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='gljournal',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='journalbatch',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='taxjurisdiction',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_locked',
        ),
    ]
