# Generated by Django 5.2.8 on 2026-08-10 22:40

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_times_used_dt_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='erosion',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='erosion',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='gljournal',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='gljournal',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='taxjurisdiction',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='taxjurisdiction',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='term',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='term',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
    ]
