# Generated by Django 5.2.8 on 2026-09-30 03:30

"""GL rows are addressed by event, reversals name what they reverse, and the chart gains the
two roles the GL-by-layer plan posts to (Bill, 2026-09-30; plan 2026-09-30-gl-by-layer.md).

- Existing reversal rows are linked to their originals by the rule reverse_gl_entries used until
  now: per record, the first k originals by id are the ones its k reversal rows reversed.
- 2050-received_not_billed exists in the seeded chart; 3050-opening_balance_equity is added.
- The company profile maps received_not_billed and opening_balance_equity when it has not
  mapped them already (a mapped role is never touched).
"""
from django.db import migrations, models

ROLE_ACCOUNTS = {
    'received_not_billed': ('2050-received_not_billed', 'Received Not Billed', 'liability',
                            'current_liabilities'),
    'opening_balance_equity': ('3050-opening_balance_equity', 'Opening Balance Equity', 'equity',
                               'equity'),
}


def link_reversals(apps, schema_editor):
    GlJournal = apps.get_model('accounts', 'GlJournal')
    pairs = (GlJournal.objects.filter(source_model__endswith='_reversal')
             .values_list('source_model', 'source_id').distinct())
    for reversal_model, source_id in pairs:
        model = reversal_model[:-len('_reversal')]
        originals = list(GlJournal.objects.filter(source_model=model, source_id=source_id)
                         .order_by('id').values_list('id', flat=True))
        reversals = list(GlJournal.objects.filter(source_model=reversal_model, source_id=source_id)
                         .order_by('id').values_list('id', flat=True))
        for rev_id, orig_id in zip(reversals, originals):
            GlJournal.objects.filter(pk=rev_id).update(reversal_of=orig_id)


def add_roles(apps, schema_editor):
    GlAccount = apps.get_model('accounts', 'GlAccount')
    Setting = apps.get_model('core', 'Setting')
    for code, name, acct_type, category in ROLE_ACCOUNTS.values():
        if not GlAccount.objects.filter(ida=code).exists():
            GlAccount.objects.create(ida=code, name=name, type=acct_type, category=category,
                                     used_for='posting', is_active=True)
    for setting in Setting.objects.filter(purpose='wc:company_profile'):
        config = setting.config if isinstance(setting.config, dict) else {}
        defaults = dict(config.get('gl_defaults') or {})
        missing = {role: acct[0] for role, acct in ROLE_ACCOUNTS.items() if not defaults.get(role)}
        if missing:
            setting.config = {**config, 'gl_defaults': {**defaults, **missing}}
            setting.save(update_fields=['config'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_is_locked_deleted'),
        ('core', '0023_is_locked_setting_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='gljournal',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gljournal',
            name='reversal_of',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(link_reversals, migrations.RunPython.noop),
        migrations.RunPython(add_roles, migrations.RunPython.noop),
    ]
