# Generated by Django 5.2.8 on 2026-08-11 04:19

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_drop_exchange_rate_and_exchange_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('has_exceptions', 'Has Exceptions')], db_index=True, default='processing', max_length=32)),
                ('batch_type', models.CharField(choices=[('full', 'Full Batch'), ('invoice', 'Invoices Only'), ('payment', 'Payments Only'), ('purchase', 'Purchases Only')], default='full', max_length=32)),
                ('period_year', models.IntegerField(blank=True, null=True)),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('total_debit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('count_posted', models.IntegerField(default=0)),
                ('count_exceptions', models.IntegerField(default=0)),
                ('count_skipped', models.IntegerField(default=0)),
                ('count_absorbed', models.IntegerField(default=0, help_text='FX rounding entries auto-absorbed < $2')),
                ('dt_started', models.BigIntegerField(blank=True, null=True)),
                ('dt_completed', models.BigIntegerField(blank=True, null=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_batches',
                'ordering': ['-dt_created'],
            },
        ),
    ]
