# Generated by Django 5.2.8 on 2026-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_create_journal_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glaccount',
            name='comment',
        ),
    ]
