# Generated by Django 5.2.8 on 2026-08-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_drop_comment_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gljournal',
            name='glj_div_date_idx',
        ),
        migrations.RemoveField(
            model_name='gljournal',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='gljournal',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='dt_posted',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='dt_settled',
        ),
        migrations.AddField(
            model_name='gljournal',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized. 0=editable, non-zero=locked.'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dt_applied',
            field=models.DateTimeField(blank=True, help_text='When payment was applied (settled). Record remains editable.', null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0, help_text='UTC epoch ms when journalized. 0=editable, non-zero=locked.'),
        ),
        migrations.AddIndex(
            model_name='gljournal',
            index=models.Index(fields=['division', 'dt_journaled'], name='glj_div_journaled_idx'),
        ),
    ]
