import { useMemo, useState } from "react";
import ComponentCard from "../../../components/common/ComponentCard";
import PageBreadcrumb from "../../../components/common/PageBreadCrumb";
import ModelScaffold from "./ModelScaffold";
import { modelRegistry, ModelRegistration } from "./modelRegistry";
import { kebabCaseToTitle } from "./scaffoldUtils";

export default function AllModelsWorkbench() {
  const [selected, setSelected] = useState<ModelRegistration | null>(null);

  const grouped = useMemo(() => {
    return modelRegistry.reduce<Record<string, ModelRegistration[]>>((acc, item) => {
      if (!acc[item.app]) acc[item.app] = [];
      acc[item.app].push(item);
      return acc;
    }, {});
  }, []);

  return (
    <div className="space-y-6">
      <PageBreadcrumb pageTitle="Model Workbench" />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <ComponentCard>
          <h3 className="text-lg font-semibold mb-2">Models</h3>
          <p className="text-xs text-gray-500 mb-3">Pick any model to open its list + detail scaffold.</p>
          <div className="space-y-4 max-h-[70vh] overflow-y-auto pr-2">
            {Object.entries(grouped).map(([app, models]) => (
              <div key={app}>
                <p className="text-sm font-semibold text-gray-700 mb-1">{kebabCaseToTitle(app)}</p>
                <div className="grid grid-cols-1 gap-1">
                  {models.map((m) => {
                    const active = selected?.model === m.model;
                    return (
                      <button
                        key={`${m.app}-${m.model}`}
                        onClick={() => setSelected(m)}
                        className={`flex w-full justify-between rounded border px-3 py-2 text-left text-sm transition ${
                          active ? "border-blue-500 bg-blue-50 text-blue-700" : "border-gray-200 hover:border-gray-300"
                        }`}
                      >
                        <span>{m.label}</span>
                        <span className="text-[11px] text-gray-400">{m.model}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </ComponentCard>

        <div className="lg:col-span-2">
          {selected ? (
            <ModelScaffold
              modelName={selected.model}
              title={`${selected.label}`}
              defaultFields={{ list: ["id", "name", "code", "status"], detail: [] }}
              hideBreadcrumb
            />
          ) : (
            <ComponentCard>
              <p className="text-sm text-gray-500">Select a model to load its autogenerated list and detail views.</p>
            </ComponentCard>
          )}
        </div>
      </div>
    </div>
  );
}
