# Generated by Django 5.2.5 on 2025-09-10 20:16

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('comment', models.TextField(blank=True, default='', help_text='General notes')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('scripts', models.JSONField(blank=True, null=True)),
                ('relationships', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('maps', models.JSONField(blank=True, null=True)),
                ('encryption', models.JSONField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('conflicts', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connections',
            },
        )
          
    ]
