# Generated by Django 5.2.1 on 2025-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),

    ]
