# Generated by Django 5.2.8 on 2026-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('', 'Unspecified'), ('api', 'API'), ('sftp', 'SFTP'), ('database', 'Database'), ('webhook', 'Webhook'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=255),
        ),
    ]
