# Generated by Django 5.2.8 on 2025-12-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='connection_id',
            new_name='id_connection',
        ),
    ]
