# Generated by Django 5.2.5 on 2025-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_connection_uuid_alter_exchange_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='actions',
            field=models.JSONField(default=dict, help_text='Next action metadata (searchable)'),
        ),
    ]
