# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_rename_connection_id_bundle_id_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='id_connection',
            new_name='connection_id',
        ),
    ]
