# Generated by Django 5.2.1 on 2025-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_connection_comment_alter_connection_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
