# Generated by Django 5.2.8 on 2026-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)'),
        ),
    ]
