# Generated by Django 5.2.8 on 2026-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_rename_id_connection_bundle_connection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='alert',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('none', 'None'), ('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='direction',
            field=models.CharField(choices=[('', 'Unspecified'), ('push', 'Push'), ('pull', 'Pull'), ('sync', 'Sync')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('ingest', 'Ingest'), ('export', 'Export'), ('bi', 'Business Intelligence'), ('sync', 'Bidirectional Sync'), ('monitor', 'Monitoring')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('retired', 'Retired')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('', 'Unspecified'), ('api', 'API'), ('sftp', 'SFTP'), ('database', 'Database'), ('webhook', 'Webhook'), ('manual', 'Manual')], max_length=255),
        ),
    ]
