# Generated by Django 5.2.8 on 2026-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_add_is_locked_to_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='purpose',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('ingest', 'Ingest'), ('export', 'Export'), ('bi', 'Business Intelligence'), ('sync', 'Bidirectional Sync'), ('monitor', 'Monitoring'), ('deploy', 'Software Deploy'), ('training', 'Knowledge & Training')], max_length=255, null=True),
        ),
    ]
