# Generated by Django 5.2.8 on 2026-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_add_deploy_training_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='dt_processed',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.'),
        ),
    ]
