# Generated by Django 5.2.8 on 2026-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_bundle_alert_alter_bundle_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
        migrations.AddField(
            model_name='connection',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Record is logically locked'),
        ),
    ]
