# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_bundle_is_locked_connection_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='is_locked',
        ),
    ]
