# Generated by Django 5.2.8 on 2026-02-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_remove_bundle_is_locked_remove_connection_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='connection_id',
            field=models.ForeignKey(db_column='connection_id', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='sync.connection'),
        ),
        migrations.RenameField(
            model_name='bundle',
            old_name='connection_id',
            new_name='connection',
        ),
    ]
