# Generated by Django 5.2.8 on 2026-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='comment',
        ),
    ]
