#!/usr/bin/env python3
"""
Generate and execute SQL to insert Document records for every React TSX page/component.
Each record has model_name='react' so they can be queried as a group.
"""
import json
import time
import subprocess

NOW_MS = int(time.time() * 1000)

# ──────────────────────────────────────────────────────────────────────────────
# Document definitions — one dict per page/component
# ──────────────────────────────────────────────────────────────────────────────

DOCS = [
    # ═══════════════════════════════════════════════════════════════════════════
    # ADMIN PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-AdminWorkbench",
        "name": "UI: DataBrowser (Admin Workbench)",
        "category": "admin",
        "file": "src/pages/admin/AdminWorkbench.tsx",
        "route": "/admin-wb",
        "title": "DataBrowser (Admin Workbench)",
        "description": "Two-pane model browser. Left: record list with DataGrid (inline edit, column filters, footer totals, multi-sort, row coloring, bulk update, print, dupe detection). Right: detail form with BehaviorField rendering. Supports dark/light theme, S/M/L font sizes, named layouts (list + detail field order), model picker with Cmd+Shift+M shortcut. Preferences saved to contact.metadata.databrowser. Navigation logged for Alice pattern analysis.",
        "access": "Sidebar > Admin > DataBrowser, or /admin-wb?model=<app.Model>",
        "key_elements": {
            "data-wc='databrowser'": "Root container",
            "data-wc='db-model-picker'": "Model selector dropdown (Cmd+Shift+M)",
            "data-wc='db-search'": "Record search (400ms debounce, Alice-tracked)",
            "data-wc='db-list-toolbar'": "List Order, Sel All, Clear, Show, Omit, pagination",
            "data-wc='db-detail-toolbar'": "+ New, Form Order, Save, Delete",
            "data-wc='db-layout-selector'": "Layout dropdown in FieldOrderDialog"
        },
        "shared_components": ["DataGrid", "BehaviorField", "FieldOrderDialog", "FilterSelect"],
        "data_sources": ["useDataBrowser hook", "wcapi getRecords", "wcapi getModelDetail", "workbench_fields Settings"],
        "state_management": "useDataBrowser hook (all state centralized)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-AccountingDash",
        "name": "UI: Accounting Dashboard",
        "category": "admin",
        "file": "src/pages/admin/AccountingDashboard.tsx",
        "route": "/accounting",
        "title": "Accounting Dashboard",
        "description": "Admin system health overview. Sections: Journal Status (last journalized, pending counts), GL Balance (total debits vs credits, imbalance detection with per-source breakdown), Transaction Volume (counts by type and status), Locked Records (journalized vs editable), AR Aging Summary (current/30/60/90+ buckets), Pending Inventory (unprocessed count + age), Orphan Detection (FK integrity check). Auto-refreshes on load.",
        "access": "Sidebar > Admin > Accounting, or /accounting",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["POST /wcapi/manage/ get_accounting_dashboard", "POST /wcapi/manage/ get_orphan_counts"],
        "state_management": "Local useState",
        "dark_mode": False,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-AliceDashboard",
        "name": "UI: Alice Dashboard",
        "category": "admin",
        "file": "src/pages/admin/AliceDashboard.tsx",
        "route": "/alice-dashboard",
        "title": "Alice Dashboard",
        "description": "Alice's coaching and monitoring dashboard. Six tabs: Coaching (system tips from Settings), Console (captured JS console errors with send-to-Alice), Actions (open actions for current user), Training (published system documents), Health (system status), LLM (Alice LLM configuration: provider, model, endpoint, temperature, max_tokens, system_prompt). Includes 'Ask Alice' text input and console capture toggle.",
        "access": "Sidebar > Admin > Alice, or /alice-dashboard",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["wcapi getRecords (setting, action, document)", "consoleCapture utility"],
        "state_management": "Local useState with tabs",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-AliceTraining",
        "name": "UI: Alice Training",
        "category": "admin",
        "file": "src/pages/admin/AliceTraining.tsx",
        "route": "/training",
        "title": "Alice Training (Inventory Flow)",
        "description": "Interactive inventory flow coaching. Walks users through 6-step commerce cycle: Create Proposal > Convert to Order > Invoice (Ship) > Record Payment > Purchase Order > Receive Goods. Shows live inventory buckets (on_hand, on_so, on_po) as visual bars before/after each step. Alice provides coaching text explaining what happened and why. Uses zzitem + zzCustomer training fixtures (no real data impact). All records flagged metadata.training=True.",
        "access": "Sidebar > Admin > Training, or /training",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["POST /wcapi/manage/ training actions"],
        "state_management": "Local useState, step-by-step progression",
        "dark_mode": False,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-DetailReview",
        "name": "UI: Detail Review",
        "category": "admin",
        "file": "src/pages/admin/DetailReview.tsx",
        "route": "/detail-review",
        "title": "Detail Review",
        "description": "Dev tool that catalogs all 52 Detail.tsx files across the app. Shows each detail component's category, model, file path, pattern (TransactionDetailBase/DetailTabs/SimpleForm/CustomLayout/ReadOnly), and route. Lazy-loads any detail component for inline preview with sample records. Includes approval workflow (reviewed/approved checkboxes), comment field, and filter by category/pattern. Used to audit detail page consistency across models.",
        "access": "/detail-review",
        "key_elements": {},
        "shared_components": ["All Detail components (lazy-loaded)"],
        "data_sources": ["Static DETAIL_FILES inventory", "Lazy imports of 52 detail pages"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-HelpDashboard",
        "name": "UI: Help Dashboard",
        "category": "admin",
        "file": "src/pages/admin/HelpDashboard.tsx",
        "route": "/help",
        "title": "Help Dashboard",
        "description": "Context-aware help center with three-source collection builder. Sources: Local (company docs from Document model), WCHQ (webclerk.net resources), User Groups (community). Features: bookmarks (localStorage-persisted), recently viewed history, glossary (built from alice_coaching field_help), keyboard shortcuts reference, 'report a problem' form, 'was this helpful?' feedback, collection builder. Opens in its own window from Help button. URL params: ?context=&model=&field= for context-specific help.",
        "access": "Help button (any page), or /help?context=invoice&model=invoice&field=total",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["wcapi getRecords (document, setting)", "Static WCHQ_RESOURCES", "Static SHORTCUTS"],
        "state_management": "Local useState + localStorage for bookmarks/recent",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-TestDashboard",
        "name": "UI: Test Dashboard",
        "category": "admin",
        "file": "src/pages/admin/TestDashboard.tsx",
        "route": "/test-dashboard",
        "title": "Test Dashboard",
        "description": "Testing and training dashboard for Alice. Shows all records from test sequences with live inventory state, clickable RecordLink to each record, and a test journal. GL Journal section with 'Batch Journalize (zzz-)' button. Displays inventory impacts (invoice_line, order_line, purchase_line, proposal_line, inventory_layer, pending_adjustment) with quantity deltas. Used for verifying transaction flows end-to-end.",
        "access": "/test-dashboard",
        "key_elements": {},
        "shared_components": ["RecordLink"],
        "data_sources": ["wcapi getRecords (gl_journal)", "wcapi manageAction (batch_journalize)"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-TeamDashboard",
        "name": "UI: Team Dashboard",
        "category": "admin",
        "file": "src/pages/admin/TeamDashboard.tsx",
        "route": "/core/team-dashboard",
        "title": "Team Dashboard",
        "description": "Per-team-member insight dashboard. Groups contacts by name_prefix (each team member tags their 3 contacts: customer/vendor/employee with their first name). Shows four insight categories per member: Record Completeness (filled fields, linked records), Activity & Actions (last modified, version, recent actions), API Usage (UserDailyLog stats: calls, errors, hints), Org Health (linked org summary). Uses lucide-react icons.",
        "access": "Sidebar > Admin > Team, or /core/team-dashboard",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["wcapi getRecords (contact)", "fetchUserDailyLogs"],
        "state_management": "Local useState with collapsible sections",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-UserActivity",
        "name": "UI: User Activity Dashboard",
        "category": "admin",
        "file": "src/pages/admin/UserActivityDashboard.tsx",
        "route": "/core/user-activity",
        "title": "User Activity Dashboard",
        "description": "Admin page showing daily user API usage, response patterns, and diagnostic hints. Fetches UserDailyLog records. Renders stat cards (total calls, errors, avg response time), day-by-day table, expandable hint panels (info/warning/error with color-coded badges), and error detail panels. Uses lucide-react icons. Shows percentage calculations for error rates.",
        "access": "/core/user-activity",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["fetchUserDailyLogs", "fetchDailyLogsByDate"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-AllModelsWB",
        "name": "UI: All Models Workbench",
        "category": "admin",
        "file": "src/apps/utils/scaffold/AllModelsWorkbench.tsx",
        "route": "/model-workbench",
        "title": "All Models Workbench (Scaffold)",
        "description": "Dev tool that lists every registered model grouped by app (from modelRegistry). Click any model to open its auto-generated list + detail scaffold (ModelScaffold component). Three-column layout: model picker on left (1/3), scaffold on right (2/3). Used for testing CRUD on any model without needing a dedicated page.",
        "access": "/model-workbench",
        "key_elements": {},
        "shared_components": ["ModelScaffold", "ComponentCard"],
        "data_sources": ["modelRegistry (static)"],
        "state_management": "Local useState (selected model)",
        "dark_mode": False,
        "maturity": "transitional",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # TOOLS PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-WhitelistTest",
        "name": "UI: Whitelist Tester",
        "category": "tools",
        "file": "src/pages/tools/WhitelistTester.tsx",
        "route": "/whitelist",
        "title": "Whitelist Tester",
        "description": "Interactive API endpoint tester. Presets cover both wcapi gateway and legacy REST paths (301-redirected by RestToWcapiMiddleware). Categories: Auth (login), WCAPI Meta/Discovery (models list, choice catalog, model detail), WCAPI CRUD (get/save/delete records, manage actions), Legacy REST redirects. Each preset shows description, required params, notes, and example payload. Executes requests and displays formatted JSON response with status code and timing.",
        "access": "/whitelist",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["apiClient (axios)", "authClient (axios)"],
        "state_management": "Local useState",
        "dark_mode": False,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-NotionTracker",
        "name": "UI: Notion Tracker",
        "category": "tools",
        "file": "src/pages/notion/NotionTrackerPage.tsx",
        "route": "/notion-tracker",
        "title": "Notion Tracker",
        "description": "Project tracking dashboard using Notion-like progress visualization. Shows module status (Not Started/In Progress/Blocked/Completed) with ApexCharts donut and bar charts. Summary cards: total items, completed, in progress, streak days. Status color-coded badges. Uses useNotionProgress hook for data fetching. Clipboard copy for summary stats.",
        "access": "Sidebar > Tools > Notion Tracker, or /notion-tracker",
        "key_elements": {},
        "shared_components": ["ComponentCard", "PageBreadcrumb"],
        "data_sources": ["useNotionProgress hook"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # TRANSACTION PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-OrderList",
        "name": "UI: Order List",
        "category": "transactions",
        "file": "src/apps/transactions/models/order/pages/OrderList.tsx",
        "route": "/transactions/order/list",
        "title": "Order List",
        "description": "Data table list of all orders. Uses AdvancedDataTable (deprecated, migrating to DataGrid) with ButtonToolbar. Quick filters: All, Open Orders, Last 30/60 Days. Columns: ida, status (color-coded badge), customer_name, vendor_name, total, margin_percentage, margin_amount, line_count, dt_created. Row actions: View, Edit, Delete. Inline detail: opens OrderDetail. Search with database toggle. Column visibility controls. Import/export.",
        "access": "Sidebar > Transactions > Orders, or /transactions/order/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "OrderDetail (inline)"],
        "data_sources": ["fetchOrders", "fetchOrderDetail"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-OrderDetail",
        "name": "UI: Order Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/order/pages/OrderDetail.tsx",
        "route": "/transactions/order/detail/:id?",
        "title": "Order Detail",
        "description": "Full order detail using TransactionDetailBase. Extends base with order-specific fields (order_no, po_number, reference, terms, due_date, ship_date, ship_via, fob). Includes SummaryCard (totals/margins), LinesCard (line items with item search), ShippingPanel, ManageActionPanel (ship, close, cancel actions), AddPaymentModal. Tab-based layout. Uses withDevIdentifier for dev-mode badges.",
        "access": "Click row in Order List, or /transactions/order/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "SummaryCard", "LinesCard", "ShippingPanel", "ManageActionPanel", "AddPaymentModal"],
        "data_sources": ["wcapi getRecord/saveRecord", "apiClient"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-InvoiceList",
        "name": "UI: Invoice List",
        "category": "transactions",
        "file": "src/apps/transactions/models/invoice/pages/InvoiceList.tsx",
        "route": "/transactions/invoice/list",
        "title": "Invoice List",
        "description": "Data table list of all invoices. Same pattern as OrderList: AdvancedDataTable + ButtonToolbar. Columns: invoice_no, status, customer_name, vendor_name, total, margin_percentage, margin_amount, line_count, dt_created. Row actions: View, Edit, Add, Delete. Search with database toggle. Navigation to detail page. Column visibility and filter controls.",
        "access": "Sidebar > Transactions > Invoices, or /transactions/invoice/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard"],
        "data_sources": ["fetchInvoices"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-InvoiceDetail",
        "name": "UI: Invoice Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/invoice/pages/InvoiceDetail.tsx",
        "route": "/transactions/invoice/detail/:id?",
        "title": "Invoice Detail",
        "description": "Full invoice detail using TransactionDetailBase. Extends base with invoice-specific fields (invoice_no, po_number, terms, due_date, ship_date, tax_rate, tax_exempt, discount_percent, discount_amount, balance_due, amount_paid). Includes SummaryCard, LinesCard, ManageActionPanel (journalize, void, apply payment), ApplyPaymentModal, AddPaymentModal. Tab-based layout with withDevIdentifier.",
        "access": "Click row in Invoice List, or /transactions/invoice/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "SummaryCard", "LinesCard", "ManageActionPanel", "ApplyPaymentModal", "AddPaymentModal"],
        "data_sources": ["wcapi getRecord/saveRecord"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ProposalList",
        "name": "UI: Proposal List",
        "category": "transactions",
        "file": "src/apps/transactions/models/proposal/pages/ProposalList.tsx",
        "route": "/transactions/proposal/list",
        "title": "Proposal List",
        "description": "Data table list of all proposals. AdvancedDataTable + ButtonToolbar pattern. Inline ProposalDetail on row select. Standard list features: search, column visibility, filters, import.",
        "access": "Sidebar > Transactions > Proposals, or /transactions/proposal/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "ProposalDetail (inline)"],
        "data_sources": ["fetchProposals", "fetchProposal"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ProposalDetail",
        "name": "UI: Proposal Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/proposal/pages/ProposalDetail.tsx",
        "route": "/transactions/proposal/detail/:id?",
        "title": "Proposal Detail",
        "description": "Full proposal detail using TransactionDetailBase. Extends base with proposal-specific fields (proposal_no, terms, due_date). Custom actions: Convert to Order (convertProposalToOrder), Generate PDF (generateProposalPdf). SummaryCard + LinesCard + ManageActionPanel. Tab-based layout.",
        "access": "Click row in Proposal List, or /transactions/proposal/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "SummaryCard", "LinesCard", "ManageActionPanel"],
        "data_sources": ["convertProposalToOrder", "generateProposalPdf", "wcapi"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-PurchaseList",
        "name": "UI: Purchase List",
        "category": "transactions",
        "file": "src/apps/transactions/models/purchase/pages/PurchaseList.tsx",
        "route": "/transactions/purchase/list",
        "title": "Purchase List",
        "description": "Data table list of all purchase orders. AdvancedDataTable + ButtonToolbar pattern. Inline PurchaseDetail on row select. Includes sanitizeRecord and formatDateTimeValue for data normalization. Standard list features.",
        "access": "Sidebar > Transactions > Purchases, or /transactions/purchase/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "PurchaseDetail (inline)"],
        "data_sources": ["fetchPurchases", "fetchPurchaseDetail"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-PurchaseDetail",
        "name": "UI: Purchase Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/purchase/pages/PurchaseDetail.tsx",
        "route": "/transactions/purchase/detail/:id?",
        "title": "Purchase Detail",
        "description": "Full purchase detail using TransactionDetailBase. Extends base with purchase-specific fields (purchase_no, receipt_id, vendor_pack_list, vendor_pack_date). Includes TransactionItemSearch with resolveItemCode/Description/UnitPrice/UnitCost helpers. SummaryCard + LinesCard. Tab-based layout.",
        "access": "Click row in Purchase List, or /transactions/purchase/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "SummaryCard", "LinesCard", "TransactionItemSearch"],
        "data_sources": ["wcapi getRecord/saveRecord"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-WorkorderList",
        "name": "UI: Work Order List",
        "category": "transactions",
        "file": "src/apps/transactions/models/workorder/pages/WorkorderList.tsx",
        "route": "/transactions/work-order/list",
        "title": "Work Order List",
        "description": "Data table list of all work orders. AdvancedDataTable + ButtonToolbar pattern. Inline WorkorderDetail on row select. Standard list features: search, column visibility, filters.",
        "access": "Sidebar > Transactions > Work Orders, or /transactions/work-order/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "WorkorderDetail (inline)"],
        "data_sources": ["fetchWorkorders", "fetchWorkorderDetail"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-WorkorderDetail",
        "name": "UI: Work Order Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/workorder/pages/WorkorderDetail.tsx",
        "route": "/transactions/work-order/detail/:id?",
        "title": "Work Order Detail",
        "description": "Full work order detail using TransactionDetailBase. Extends base with work order-specific fields (workorder_no, due_date, start_date, end_date, priority, assigned_to, description, notes). Status badge component. LinesCard for line items. Tab-based layout.",
        "access": "Click row in Work Order List, or /transactions/work-order/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "LinesCard", "FieldLabel"],
        "data_sources": ["wcapi getRecord/saveRecord"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ReceiptList",
        "name": "UI: Receipt List",
        "category": "transactions",
        "file": "src/apps/transactions/models/receipt/pages/ReceiptList.tsx",
        "route": "/transactions/receipt/list",
        "title": "Receipt List",
        "description": "Data table list of all receipts. AdvancedDataTable + ButtonToolbar pattern. Inline ReceiptDetail on row select. Standard list features.",
        "access": "Sidebar > Transactions > Receipts, or /transactions/receipt/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "ReceiptDetail (inline)"],
        "data_sources": ["fetchReceipts", "deleteReceipt"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ReceiptDetail",
        "name": "UI: Receipt Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/receipt/pages/ReceiptDetail.tsx",
        "route": "/transactions/receipt/detail/:id?",
        "title": "Receipt Detail",
        "description": "Full receipt detail using TransactionDetailBase. Extends base with receipt-specific fields (source_type: purchase_receipt/workorder_completion/inventory_adjustment, dt_received, notes, purchase_id, workorder_id). TransactionItemSearch for adding line items. Uses withDevIdentifier.",
        "access": "Click row in Receipt List, or /transactions/receipt/detail/:id",
        "key_elements": {},
        "shared_components": ["TransactionDetailBase", "TransactionItemSearch", "FieldLabel"],
        "data_sources": ["wcapi getRecord/saveRecord"],
        "state_management": "TransactionDetailBase state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-PaymentList",
        "name": "UI: Payment List",
        "category": "transactions",
        "file": "src/apps/transactions/models/payment/pages/PaymentListPage.tsx",
        "route": "/transactions/payment/list",
        "title": "Payment List",
        "description": "Data table list of all payments. AdvancedDataTable + ButtonToolbar pattern. Status-colored badges (completed=green, pending=yellow, processing=blue, failed=red, cancelled=gray, refunded=purple). Row actions: View, Edit, Add, Delete. Mirrors WC2 Table 28 Output columns.",
        "access": "Sidebar > Transactions > Payments, or /transactions/payment/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard"],
        "data_sources": ["fetchPayments", "deleteRecord"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-PaymentDetail",
        "name": "UI: Payment Detail",
        "category": "transactions",
        "file": "src/apps/transactions/models/payment/pages/PaymentDetailPage.tsx",
        "route": "/transactions/payment/detail/:id?",
        "title": "Payment Detail",
        "description": "Standalone payment detail (NOT TransactionDetailBase -- Payment is not a TransactionBaseModel). Inspired by WC2 Table 28 Input form (pages 1 & 2). Page 1: customer info, invoice/order refs, status flags, banking. Page 2: core payment fields, currency, credit-card, check, address, comment/history. Three modes: view/edit/add. Status options: pending/processing/completed/failed/cancelled/refunded/partially_refunded. Gateway options: manual/stripe/paypal. Payment applications list.",
        "access": "Click row in Payment List, or /transactions/payment/detail/:id",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "ComponentCard"],
        "data_sources": ["fetchPayment", "createPayment", "updatePayment", "deletePayment", "fetchPaymentMethods", "fetchPaymentApplications"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ApplyPayments",
        "name": "UI: Apply Payments",
        "category": "transactions",
        "file": "src/apps/transactions/pages/ApplyPayments.tsx",
        "route": "/transactions/apply-payments",
        "title": "Apply Payments",
        "description": "Bulk payment application page. Mirrors WC2 ApplyPayments form. Workflow: Customer search/filter > Invoice list (unpaid) > Payment list (available) > Apply payment to selected invoice(s) > Auto-apply to oldest. Features: org search with debounce, days past due calculation, invoice balance tracking, payment available tracking, PaymentDialog for new payments. Uses usePaymentApplication hook.",
        "access": "Sidebar > Transactions > Apply Payments, or /transactions/apply-payments",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "ComponentCard", "PaymentDialog"],
        "data_sources": ["usePaymentApplication hook (getAvailablePayments, getUnpaidInvoices, applyPaymentToInvoice)"],
        "state_management": "Local useState + usePaymentApplication hook",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-InvAdjList",
        "name": "UI: Inventory Adjustment List",
        "category": "transactions",
        "file": "src/apps/transactions/models/inventory_adjustment/pages/InventoryAdjustmentList.tsx",
        "route": "/transactions/adjustment/list",
        "title": "Inventory Adjustment List",
        "description": "Stub page for inventory adjustments. Shows placeholder text: 'This page will list inventory adjustments for manual quantity corrections, cycle counts, and other inventory modifications. Coming soon - API integration pending.' Uses PageBreadcrumb + ComponentCard wrapper.",
        "access": "/transactions/adjustment/list",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "ComponentCard"],
        "data_sources": [],
        "state_management": "None",
        "dark_mode": False,
        "maturity": "stub",
        "ask_bill": True,
        "question": "Is the inventory adjustment API ready? This page is a stub with no data integration.",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # PRODUCT PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-ItemList",
        "name": "UI: Item List",
        "category": "products",
        "file": "src/apps/products/models/item/pages/ItemList.tsx",
        "route": "/products/item/list",
        "title": "Item List",
        "description": "Data table list of all items/products. AdvancedDataTable + ButtonToolbar pattern. Includes ItemDashboard navigation button. valueFrom helper for flexible field access. extractItems normalizes differing API payload shapes into flat array. Standard features: search, column visibility, filters, row actions (View/Edit/Add/Delete), inline ItemDetail.",
        "access": "Sidebar > Products > Items, or /products/item/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "ItemDetail (inline)"],
        "data_sources": ["fetchItems"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ItemDetail",
        "name": "UI: Item Detail",
        "category": "products",
        "file": "src/apps/products/models/item/pages/ItemDetail.tsx",
        "route": "/products/item/detail/:id",
        "title": "Item Detail",
        "description": "Enterprise best practices item detail page. Two-column layout with labels on left (scannable). Logical field groupings in collapsible sections: Basic Info, Pricing (cost/price/margin), Inventory (on_hand/on_so/on_po/reserved/available), Configuration, BOM (Bill of Materials). Uses react-hook-form + zod validation. Tab navigation for sub-sections (overview, comments, documents, raw). SimpleDetailHeader + SimpleDetailToolbar. useDetailFieldAccess for RBAC-driven field visibility. BOMSection component for bill of materials.",
        "access": "Click row in Item List, or /products/item/detail/:id",
        "key_elements": {},
        "shared_components": ["SimpleDetailHeader", "SimpleDetailToolbar", "ComponentCard", "DevBadge", "DetailTabs", "BOMSection"],
        "data_sources": ["wcapi getRecord/saveRecord", "createItem", "updateItem"],
        "state_management": "react-hook-form + zod",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # CORE PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-ActionList",
        "name": "UI: Action List",
        "category": "core",
        "file": "src/apps/core/models/action/pages/ActionList.tsx",
        "route": "/core/actions/list",
        "title": "Action List",
        "description": "Data table list of all actions (tasks/to-dos). AdvancedDataTable + ButtonToolbar pattern. Columns: action text (multilingual), kanban_column, priority (1-4), difficulty (1-5), status, percent_complete, dt_deadline, project_name, assigned_to. Quick patch via patchAction for inline status updates. Badge-styled status/priority indicators. Inline ActionDetail on row select. Search presets (runSearchPreset).",
        "access": "Sidebar > Core > Actions, or /core/actions/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "Badge", "ActionDetail (inline)"],
        "data_sources": ["Actions API", "patchAction", "runSearchPreset"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ActionDetail",
        "name": "UI: Action Detail",
        "category": "core",
        "file": "src/apps/core/models/action/pages/ActionDetail.tsx",
        "route": "/core/actions/detail/:id?",
        "title": "Action Detail",
        "description": "Full action/task detail page. Uses react-hook-form + zod validation. Multilingual fields (action_en/ar/bn, description_en/ar/bn). Fields: kanban_column, priority (1-4), difficulty (1-5), status, percent_complete, dt_deadline, dt_start, dt_end, project_name. HorizontalField layout with configurable column count (ColumnSelector). Tab layout: Overview, Comments, Documents, Q&A, Contact Links. ScalarCard + BaseModelCards for base model fields. SimpleDetailHeader + SimpleDetailToolbar.",
        "access": "Click row in Action List, or /core/actions/detail/:id",
        "key_elements": {},
        "shared_components": ["SimpleDetailHeader", "SimpleDetailToolbar", "DetailTabs", "CommentsPanel", "DocumentsPanel", "QAPanel", "ContactLinksPanel", "ScalarCard", "BaseModelCards", "HorizontalField", "ColumnSelector"],
        "data_sources": ["createAction", "updateAction"],
        "state_management": "react-hook-form + zod",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-APILogList",
        "name": "UI: API Log List",
        "category": "core",
        "file": "src/apps/core/models/api_log/pages/APILogList.tsx",
        "route": "/core/api-log/list",
        "title": "API Log List",
        "description": "Data table list of API log entries. AdvancedDataTable + ButtonToolbar pattern. Columns: source, destination, method, endpoint, status_code, duration_ms, error_message, correlation_id, dt_created, user_id. Badge-styled status codes. Inline APILogDetail on row select. Refresh button. Search and filter controls.",
        "access": "/core/api-log/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "Badge", "APILogDetail (inline)"],
        "data_sources": ["wcapi getRecords (api_log)"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ContactList",
        "name": "UI: Contact List",
        "category": "core",
        "file": "src/apps/core/models/contact/pages/ContactList.tsx",
        "route": "/core/contact/list",
        "title": "Contact List",
        "description": "Data table list of all contacts. AdvancedDataTable + ButtonToolbar pattern. Columns: email, name_first, name_last, company, role, phone, is_active, is_staff. PhoneFormat and EmailFormat display components. Supports multiple detail view variants (ContactDetail, ContactDetail2, ContactDetail3) selected by URL param. Delete via wcapi. Standard list features.",
        "access": "Sidebar > Core > Contacts, or /core/contact/list",
        "key_elements": {},
        "shared_components": ["AdvancedDataTable", "ButtonToolbar", "ComponentCard", "PhoneFormat", "EmailFormat", "ContactDetail (inline)"],
        "data_sources": ["fetchContacts", "wcapi getRecord/deleteRecord"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ContactDetail",
        "name": "UI: Contact Detail",
        "category": "core",
        "file": "src/apps/core/models/contact/pages/ContactDetail.tsx",
        "route": "/core/contact/detail/:id?",
        "title": "Contact Detail (Primary)",
        "description": "Panel-based contact detail with ScalarCard/JsonCard/BaseModelCards, CommLinkPanel, OrgLinkPanel, and EmailGatePanel. View and edit modes share same panel layout. Enterprise UI pattern: Header (title, ID, status, actions) > Toolbar (Save, Cancel) > Basic Information (persistent) > Tab Navigation > Tab Content (scrollable). Uses react-hook-form + zod. Controller components for form fields. Portal-based modals. RippleLoader for loading state.",
        "access": "Click row in Contact List, or /core/contact/detail/:id",
        "key_elements": {},
        "shared_components": ["ScalarCard", "BaseModelCards", "DevBadge", "DetailFeatureBadge", "RippleLoader"],
        "data_sources": ["wcapi getRecord/saveRecord/deleteRecord/getRecords/getContactOptions/getProjectOptions", "createContact", "updateContact"],
        "state_management": "react-hook-form + zod",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-DocumentIndex",
        "name": "UI: Document Index",
        "category": "core",
        "file": "src/apps/docs/models/document/pages/DocumentIndex.tsx",
        "route": "/docs",
        "title": "Documentation Center",
        "description": "Stub page for documentation. Shows 'Documentation functionality will be implemented here.' Uses PageBreadcrumb + ComponentCard wrapper. No data integration yet.",
        "access": "Sidebar > Documents, or /docs",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "ComponentCard"],
        "data_sources": [],
        "state_management": "None",
        "dark_mode": False,
        "maturity": "stub",
        "ask_bill": True,
        "question": "Document Index is a stub. Should it show documents filtered by model_name, or a different view?",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # ORG PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-CustomerPage",
        "name": "UI: Customer Page",
        "category": "orgs",
        "file": "src/apps/orgs/pages/CustomerPage.tsx",
        "route": "/org/customer",
        "title": "Customer Page",
        "description": "Config-driven org page for customers. Wraps shared OrgPage component with orgType='customer'. OrgPage provides: DataGrid list with BehaviorField rendering, detail form, TransactionTabPanel for viewing related orders/invoices/payments, communication links. Shared across all org types (customer/vendor/employee/rep/manufacturer).",
        "access": "Sidebar > Organizations > Customers, or /org/customer",
        "key_elements": {},
        "shared_components": ["OrgPage"],
        "data_sources": ["wcapi (via OrgPage)"],
        "state_management": "OrgPage state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-VendorPage",
        "name": "UI: Vendor Page",
        "category": "orgs",
        "file": "src/apps/orgs/pages/VendorPage.tsx",
        "route": "/org/vendor",
        "title": "Vendor Page",
        "description": "Config-driven org page for vendors. Wraps OrgPage with orgType='vendor'.",
        "access": "Sidebar > Organizations > Vendors, or /org/vendor",
        "key_elements": {},
        "shared_components": ["OrgPage"],
        "data_sources": ["wcapi (via OrgPage)"],
        "state_management": "OrgPage state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-EmployeePage",
        "name": "UI: Employee Page",
        "category": "orgs",
        "file": "src/apps/orgs/pages/EmployeePage.tsx",
        "route": "/org/employee",
        "title": "Employee Page",
        "description": "Config-driven org page for employees. Wraps OrgPage with orgType='employee'.",
        "access": "Sidebar > Organizations > Employees, or /org/employee",
        "key_elements": {},
        "shared_components": ["OrgPage"],
        "data_sources": ["wcapi (via OrgPage)"],
        "state_management": "OrgPage state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-RepPage",
        "name": "UI: Rep Page",
        "category": "orgs",
        "file": "src/apps/orgs/pages/RepPage.tsx",
        "route": "/org/rep",
        "title": "Rep Page",
        "description": "Config-driven org page for sales reps. Wraps OrgPage with orgType='rep'.",
        "access": "Sidebar > Organizations > Reps, or /org/rep",
        "key_elements": {},
        "shared_components": ["OrgPage"],
        "data_sources": ["wcapi (via OrgPage)"],
        "state_management": "OrgPage state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-MfgPage",
        "name": "UI: Manufacturer Page",
        "category": "orgs",
        "file": "src/apps/orgs/pages/ManufacturerPage.tsx",
        "route": "/org/manufacturer",
        "title": "Manufacturer Page",
        "description": "Config-driven org page for manufacturers. Wraps OrgPage with orgType='manufacturer'.",
        "access": "Sidebar > Organizations > Manufacturers, or /org/manufacturer",
        "key_elements": {},
        "shared_components": ["OrgPage"],
        "data_sources": ["wcapi (via OrgPage)"],
        "state_management": "OrgPage state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # AUTH / LAYOUT / UTILITY PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-Home",
        "name": "UI: Home Dashboard",
        "category": "layout",
        "file": "src/pages/Dashboard/Home.tsx",
        "route": "/dashboard",
        "title": "Home Dashboard",
        "description": "Main dashboard after login. Dynamic layout with sections: Stats cards (configurable, normalized from array or object), Notifications (badges, timestamps), Activities timeline, Actions (with severity color: high=rose, medium=amber, low=emerald), Quick Shortcuts (navigation links), Pulse metrics. Network diagnostics: formatNetworkError + logNetworkDiagnostics on API failure. Fetches from POST /wcapi/manage/ get_dashboard. Dark mode supported.",
        "access": "Post-login landing, or /dashboard",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["POST /wcapi/manage/ get_dashboard (via apiClient)"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-UserProfile",
        "name": "UI: User Profile",
        "category": "layout",
        "file": "src/pages/UserProfile.tsx",
        "route": "/profile",
        "title": "User Profile",
        "description": "User profile page with three cards: UserMetaCard (avatar, name, role), UserInfoCard (email, phone, department), UserAddressCard (address fields). Uses PageBreadcrumb + PageMeta. Static layout.",
        "access": "Top-right user menu > Profile, or /profile",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "PageMeta", "UserMetaCard", "UserInfoCard", "UserAddressCard"],
        "data_sources": [],
        "state_management": "Delegated to child cards",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-SignIn",
        "name": "UI: Sign In",
        "category": "auth",
        "file": "src/pages/AuthPages/SignIn.tsx",
        "route": "/",
        "title": "Sign In",
        "description": "Login page. Wraps SignInForm in AuthLayout. PageMeta for SEO. Username/password authentication. Minimal wrapper -- all logic in SignInForm component.",
        "access": "Root URL / (unauthenticated)",
        "key_elements": {},
        "shared_components": ["AuthLayout", "SignInForm", "PageMeta"],
        "data_sources": ["Auth API (via SignInForm)"],
        "state_management": "Delegated to SignInForm",
        "dark_mode": False,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-SignUp",
        "name": "UI: Sign Up",
        "category": "auth",
        "file": "src/pages/AuthPages/SignUp.tsx",
        "route": "/register",
        "title": "Sign Up",
        "description": "Registration page. Wraps SignUpForm in AuthLayout. PageMeta for SEO. Minimal wrapper -- all logic in SignUpForm component.",
        "access": "/register",
        "key_elements": {},
        "shared_components": ["AuthLayout", "SignUpForm", "PageMeta"],
        "data_sources": ["Auth API (via SignUpForm)"],
        "state_management": "Delegated to SignUpForm",
        "dark_mode": False,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-NotFound",
        "name": "UI: 404 Not Found",
        "category": "layout",
        "file": "src/pages/NotFoundPage.tsx",
        "route": "* (catch-all)",
        "title": "404 Not Found",
        "description": "Error page for unmatched routes. Shows '404 Page not found' with current path. Two buttons: Go back (navigate(-1)), Dashboard (navigate to /dashboard). Dashed border card style. Dark mode supported.",
        "access": "Any unmatched URL",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "None",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-Placeholder",
        "name": "UI: Placeholder",
        "category": "layout",
        "file": "src/pages/Placeholder.tsx",
        "route": "Various (e.g., /submit-bonus)",
        "title": "Placeholder",
        "description": "Generic placeholder for pages not yet built. Shows title, 'This page is not yet available', current path, and Go Back button. Used for /submit-bonus and other stub routes. Accepts title and description props.",
        "access": "Various stub routes",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "None",
        "dark_mode": True,
        "maturity": "stub",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # LEGACY / QQQ PAGES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-qqqItemDash",
        "name": "UI: qqq_ItemDashboard (LEGACY)",
        "category": "legacy",
        "file": "src/pages/qqq_ItemDashboard.tsx",
        "route": "Not routed",
        "title": "Item Dashboard (Legacy)",
        "description": "LEGACY (qqq_ prefix = deletable). Direct fetch() to /wcapi/get/ instead of using wcapi module. Placeholder panels for item schema aspects. Superseded by ItemDetail.tsx which uses proper wcapi and react-hook-form patterns.",
        "access": "Not routed -- dead code",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["Direct fetch()"],
        "state_management": "Local useState",
        "dark_mode": False,
        "maturity": "legacy",
        "ask_bill": False,
        "notes": "Deletable. qqq_ prefix marks it as legacy dead code.",
    },
    {
        "ida": "UI-DOC-TestStorefront",
        "name": "UI: Test Storefront",
        "category": "test",
        "file": "src/pages/test/Test.tsx",
        "route": "/test",
        "title": "Test Storefront",
        "description": "Mock grocery storefront UI for testing. Static data: categories (Groceries/Fruits/Beverages/Household/Snacks/Dairy), deals, products with INR prices. Shopping cart mockup. Not connected to real data. Public route (no auth required).",
        "access": "/test (public)",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["Static data"],
        "state_management": "Local useState",
        "dark_mode": False,
        "maturity": "legacy",
        "ask_bill": False,
        "notes": "Test/demo page with hardcoded data. Consider removing or repurposing.",
    },
    {
        "ida": "UI-DOC-QATestPage",
        "name": "UI: QA Test Page",
        "category": "test",
        "file": "src/pages/test/QATestPage.tsx",
        "route": "/test/qa",
        "title": "QA Panel Test Page",
        "description": "Test page for the QAPanel component. Loads available QA question groups, lets you select a group and parent record ID, then renders QAPanel with those params. Used for testing Q&A functionality in isolation. Public route.",
        "access": "/test/qa (public)",
        "key_elements": {},
        "shared_components": ["QAPanel"],
        "data_sources": ["getAllQAQuestionGroups"],
        "state_management": "Local useState",
        "dark_mode": False,
        "maturity": "transitional",
        "ask_bill": False,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # SHARED COMPONENTS (key ones)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "ida": "UI-DOC-DataGrid",
        "name": "UI Component: DataGrid",
        "category": "shared_component",
        "file": "src/components/common/DataGrid.tsx",
        "route": "N/A (component)",
        "title": "DataGrid",
        "description": "Enhanced list table replacing inline table in AdminWorkbench. 10 features: 1) Column filters (per-column dropdown/search/range), 2) Footer totals (sum/count for numeric), 3) Inline cell edit (double-click, Tab/Enter to save), 4) Conditional row coloring (rules from Settings), 5) Multi-sort (Ctrl-click for secondary), 6) Pin first column (sticky left), 7) Row grouping (collapsible), 8) Bulk field update (select rows, set value), 9) Print list, 10) Duplicate detection (highlight potential dupes). XLSX export support. Reusable in any page needing a data table.",
        "access": "N/A -- imported by pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "Props-driven",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "records": "any[] -- data rows",
            "columns": "string[] -- field names (simple mode)",
            "richColumns": "RichColumn[] -- rich column defs (optional, overrides simple)",
            "colWidths": "Record<string, number>",
            "fieldBehaviors": "Record<string, any>",
            "colorRules": "RowColorRule[]",
            "onCellEdit": "(id, field, value) => void",
            "sorts": "SortSpec[]",
        },
        "used_by": ["AdminWorkbench"],
    },
    {
        "ida": "UI-DOC-BehaviorField",
        "name": "UI Component: BehaviorField",
        "category": "shared_component",
        "file": "src/components/common/BehaviorField.tsx",
        "route": "N/A (component)",
        "title": "BehaviorField",
        "description": "Renders one field based on field_behaviors config. Reusable in DataBrowser, OrgPage, any detail page. Handles types: email (mailto link), phone (tel link), address (map link), geo (map), url (link), select (inline dropdown), lookup (FK), currency, boolean, json (expandable editor), textarea, timestamp, readonly, number, text. Label color coding: blue=actionable, green=select, purple=lookup, gray=readonly. Cmd+Option+Shift+click any label opens field-level help in Help Dashboard.",
        "access": "N/A -- imported by pages",
        "key_elements": {},
        "shared_components": ["HelpMenu (openFieldHelp)"],
        "data_sources": [],
        "state_management": "Props-driven",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "name": "string -- field name",
            "value": "unknown -- field value",
            "behavior": "Record<string, any> -- field_behaviors config",
            "onChange": "(value) => void",
            "record": "Record<string, unknown> -- full record for geo pair lookups",
            "fontSize": "number (default 12)",
            "theme": "theme object (inputBg, inputBorder, text, etc.)",
            "rowSize": "number",
        },
        "used_by": ["AdminWorkbench", "OrgPage"],
    },
    {
        "ida": "UI-DOC-FieldOrderDlg",
        "name": "UI Component: FieldOrderDialog",
        "category": "shared_component",
        "file": "src/components/common/FieldOrderDialog.tsx",
        "route": "N/A (component)",
        "title": "FieldOrderDialog",
        "description": "Unified field selection, ordering, and layout management. Used for BOTH list columns and detail fields. Features: Layout selector dropdown (load existing, modify, save), drag-and-drop reordering (HTML5 drag + arrow buttons), checkbox visibility toggles, behavior indicator column (color-coded badges), row size column for text/json fields (detail mode only), save as new layout or overwrite existing, delete layouts. Fetches saved layouts from wcapi Settings.",
        "access": "N/A -- opened from List Order / Form Order buttons",
        "key_elements": {
            "data-wc='db-layout-selector'": "Layout dropdown",
        },
        "shared_components": [],
        "data_sources": ["wcapi getRecords (settings with saved layouts)"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "open": "boolean",
            "mode": "'list' | 'detail'",
            "allFields": "string[]",
            "visibleFields": "string[]",
            "fieldBehaviors": "Record<string, any>",
            "rowSizes": "Record<string, number> (detail mode only)",
            "savedLayouts": "SavedLayout[]",
            "activeLayoutName": "string",
            "onApply": "(fields, rowSizes) => void",
            "onSaveLayout": "(name, listFields, detailFields, rowSizes) => void",
            "onLoadLayout": "(layout) => void",
            "onDeleteLayout": "(name) => void",
            "onClose": "() => void",
            "theme": "'dark' | 'light'",
        },
        "used_by": ["AdminWorkbench"],
    },
    {
        "ida": "UI-DOC-FilterSelect",
        "name": "UI Component: FilterSelect",
        "category": "shared_component",
        "file": "src/components/common/FilterSelect.tsx",
        "route": "N/A (component)",
        "title": "FilterSelect",
        "description": "Standard select list for WC3. Replaces native <select> everywhere. Features: text input with begins-with filtering (configurable to contains), div list with keyboard-navigable highlighted row, Arrow Up/Down moves highlight, Enter selects, Click selects, Escape closes, auto-scroll highlighted item into view, current value shown bold. Optional group headers.",
        "access": "N/A -- imported by pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "Props-driven + local open/filter state",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "items": "FilterSelectItem[] ({value, label, group?})",
            "value": "string",
            "onChange": "(value: string) => void",
            "placeholder": "string",
            "filterMode": "'startsWith' | 'contains'",
            "maxHeight": "number",
            "inline": "boolean (always open, no toggle button)",
        },
        "used_by": ["AdminWorkbench", "FieldOrderDialog"],
    },
    {
        "ida": "UI-DOC-RecordLink",
        "name": "UI Component: RecordLink",
        "category": "shared_component",
        "file": "src/components/common/RecordLink.tsx",
        "route": "N/A (component)",
        "title": "RecordLink",
        "description": "Standard clickable record reference for WC3. Click navigates to detail page. Shift-click opens in DataBrowser (/admin-wb?model=X). Route mapping for all major models: customer, vendor, employee, rep, manufacturer, order, invoice, proposal, purchase, work_order, payment, item, action, contact. Shows label or '#id' fallback.",
        "access": "N/A -- imported by pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "None (stateless)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "model": "string",
            "id": "number | string",
            "label": "string (optional)",
        },
        "used_by": ["TestDashboard", "various detail pages"],
    },
    {
        "ida": "UI-DOC-ManageAction",
        "name": "UI Component: ManageActionPanel",
        "category": "shared_component",
        "file": "src/components/common/ManageActionPanel.tsx",
        "route": "N/A (component)",
        "title": "ManageActionPanel",
        "description": "Config-driven operations panel for transaction detail pages. Shows available wcapi/manage actions for the current model + record. Click an action to call wcapi/manage, shows result. Some actions open a dialog for input (partial ship, serial assign, etc.). Simple actions execute immediately with confirmation. Per-model action configs with key, label, icon, variant, confirm text, needsDialog flag, and param builder.",
        "access": "N/A -- dropped into detail pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["wcapi/manage/ (per-action)"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "modelName": "string",
            "recordId": "number | string",
            "record": "any (optional)",
            "onActionComplete": "() => void (refresh callback)",
        },
        "used_by": ["OrderDetail", "InvoiceDetail", "ProposalDetail", "PurchaseDetail"],
    },
    {
        "ida": "UI-DOC-AliceHintBar",
        "name": "UI Component: AliceHintBar",
        "category": "shared_component",
        "file": "src/components/common/AliceHintBar.tsx",
        "route": "N/A (component)",
        "title": "AliceHintBar",
        "description": "Shows Alice coaching hints, WCHQ tips, and power user suggestions. Drop into any page: <AliceHintBar model='order' />. Shows hints relevant to the current model. Dismissible. Three sources with color coding -- Alice (green), WCHQ (blue), Power users (amber). Dark and light mode variants. Uses AliceContext for hint data.",
        "access": "N/A -- dropped into any page",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["AliceContext (useAlice hook)"],
        "state_management": "AliceContext",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "model": "string (optional)",
            "field": "string (optional)",
            "maxHints": "number (default 3)",
        },
        "used_by": ["Various pages"],
    },
    {
        "ida": "UI-DOC-GetHelpDialog",
        "name": "UI Component: GetHelpDialog",
        "category": "shared_component",
        "file": "src/components/common/GetHelpDialog.tsx",
        "route": "N/A (component)",
        "title": "GetHelpDialog",
        "description": "Paste-to-help dialog. User workflow: Right-click any element, Inspect, Copy Element, Press Cmd+? or click Help > Get Help, paste the element HTML. The data-wc attribute on pasted element identifies component, model context, and field. Alice looks up: AliceObservation records, training documents, field-level help from field_access Settings, WCHQ knowledge base matches. Maps data-wc IDs to human descriptions + help topics.",
        "access": "Cmd+? shortcut or Help menu",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["Static WC_HELP_MAP"],
        "state_management": "Props-driven (open/onClose)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "open": "boolean",
            "onClose": "() => void",
        },
        "used_by": ["HelpMenu"],
    },
    {
        "ida": "UI-DOC-HelpMenu",
        "name": "UI Component: HelpMenu",
        "category": "shared_component",
        "file": "src/components/common/HelpMenu.tsx",
        "route": "N/A (component)",
        "title": "HelpMenu",
        "description": "Context-aware help button. Click opens Help Dashboard in its own window for the current page context. Auto-detects context from URL path (admin-wb, alice-dashboard, invoice, order, etc.). Exports openFieldHelp(model, fieldName) function for Cmd+Option+Shift+click on field labels to open field-specific help.",
        "access": "N/A -- rendered in app layout",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "None (stateless + window.open)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "className": "string (optional)",
        },
        "used_by": ["App layout"],
    },
    {
        "ida": "UI-DOC-DetailTabs",
        "name": "UI Component: DetailTabs",
        "category": "shared_component",
        "file": "src/components/common/DetailTabs.tsx",
        "route": "N/A (component)",
        "title": "DetailTabs",
        "description": "Reusable tab navigation for Detail pages. Standard tabs: Overview, Comments, Actions, Documents, History (admin), Raw (admin). Model-specific tabs injected via additionalTabs prop. Persists active tab to localStorage. Role-based visibility for admin tabs. Auto-renders 5 standard panels when recordData provided: ActionsPanel, CommentsPanel, DocumentsPanel, FinancialsPanel, JsonFieldEditor. Additional panels available via additionalTabs content.",
        "access": "N/A -- imported by detail pages",
        "key_elements": {},
        "shared_components": ["ActionsPanel", "CommentsPanel", "DocumentsPanel", "FinancialsPanel", "JsonFieldEditor"],
        "data_sources": [],
        "state_management": "Local useState + localStorage persistence",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-ComponentCard",
        "name": "UI Component: ComponentCard",
        "category": "shared_component",
        "file": "src/components/common/ComponentCard.tsx",
        "route": "N/A (component)",
        "title": "ComponentCard",
        "description": "Standard card wrapper used across all pages. Rounded corners, border, white background (dark mode: dark background). Optional title and description. The most widely used layout primitive in the application.",
        "access": "N/A -- imported everywhere",
        "key_elements": {},
        "shared_components": ["DevIdentifier (withDevIdentifier)"],
        "data_sources": [],
        "state_management": "None (stateless)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
        "props": {
            "title": "string (optional)",
            "children": "ReactNode",
            "className": "string (optional)",
            "desc": "string (optional)",
        },
        "used_by": ["Nearly all pages"],
    },
    {
        "ida": "UI-DOC-ButtonToolbar",
        "name": "UI Component: ButtonToolbar",
        "category": "shared_component",
        "file": "src/components/common/ButtonToolbar.tsx",
        "route": "N/A (component)",
        "title": "ButtonToolbar",
        "description": "Standard toolbar for list pages. Includes: Search input, Add/Delete/Download/Import/Print buttons, column setup trigger, filter toggle, search presets (SearchPresetDropdown), column setups (ColumnSetupDialog), quick filters (PrintReportDropdown), report generation. Extensive configuration through props. Link to DataBrowser integration. Badge for active search preset.",
        "access": "N/A -- imported by list pages",
        "key_elements": {},
        "shared_components": ["SearchPresetDropdown", "ColumnSetupDialog", "PrintReportDropdown"],
        "data_sources": ["useColumnSetups hook", "getReportsForModel"],
        "state_management": "Props-driven + local dropdown state",
        "dark_mode": True,
        "maturity": "transitional",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-AdvDataTable",
        "name": "UI Component: AdvancedDataTable (DEPRECATED)",
        "category": "shared_component",
        "file": "src/components/common/AdvancedDataTable.tsx",
        "route": "N/A (component)",
        "title": "AdvancedDataTable (Deprecated)",
        "description": "DEPRECATED -- re-exports from AdvancedDataTable_DEPRECATED. Pages should migrate to DataGrid + useListFieldConfig + FieldOrderDialog. Still used by: OrderList, InvoiceList, ProposalList, PurchaseList, WorkorderList, ReceiptList, ActionList, ContactList, APILogList, PaymentListPage, ItemList.",
        "access": "N/A -- imported by list pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "Props-driven",
        "dark_mode": True,
        "maturity": "legacy",
        "ask_bill": True,
        "question": "11 list pages still use deprecated AdvancedDataTable. Priority for migration to DataGrid?",
    },
    {
        "ida": "UI-DOC-DetailShell",
        "name": "UI Component: DetailShell",
        "category": "shared_component",
        "file": "src/components/common/DetailShell.tsx",
        "route": "N/A (component)",
        "title": "DetailShell",
        "description": "Wrapper for simple detail pages. Handles: breadcrumb generation from mode (Add/Edit/View), optional inline mode with cancel button, optional card wrapping via ComponentCard, DevBadge and DetailFeatureBadge for dev-mode indicators. Used by lookup table detail pages.",
        "access": "N/A -- imported by detail pages",
        "key_elements": {},
        "shared_components": ["PageBreadcrumb", "ComponentCard", "DevBadge", "DetailFeatureBadge"],
        "data_sources": [],
        "state_management": "None (stateless)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-TxnTabPanel",
        "name": "UI Component: TransactionTabPanel",
        "category": "shared_component",
        "file": "src/components/common/TransactionTabPanel.tsx",
        "route": "N/A (component)",
        "title": "TransactionTabPanel",
        "description": "Second-row tab bar for navigating transaction sub-types on org detail pages (Customer, Vendor). No 'All' tab -- user chooses one transaction type. Selected type persisted to localStorage (Alice preference key). Data fetched only for selected tab to avoid unnecessary API calls. Tabs: Orders, Invoices, Payments, Proposals, Purchases, Receipts, Work Orders, Ledger. Uses WindowManager for opening records.",
        "access": "N/A -- rendered on org detail pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": ["wcapi getRecords"],
        "state_management": "Local useState + localStorage persistence",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-SimpleDetHdr",
        "name": "UI Component: SimpleDetailHeader",
        "category": "shared_component",
        "file": "src/components/common/SimpleDetailHeader.tsx",
        "route": "N/A (component)",
        "title": "SimpleDetailHeader",
        "description": "Lightweight header for simple Detail pages. Displays: entity type name, record ID (for edit/view), mode indicator (Add/Edit/View with icon), record display name, back navigation button (optional). Includes DevBadge and DetailFeatureBadge. Uses lucide-react icons (ChevronLeft, Plus, Pencil, Eye, X).",
        "access": "N/A -- imported by detail pages",
        "key_elements": {},
        "shared_components": ["DevBadge", "DetailFeatureBadge"],
        "data_sources": [],
        "state_management": "None (stateless)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-SimpleDetTB",
        "name": "UI Component: SimpleDetailToolbar",
        "category": "shared_component",
        "file": "src/components/common/SimpleDetailToolbar.tsx",
        "route": "N/A (component)",
        "title": "SimpleDetailToolbar",
        "description": "Lightweight action toolbar for simple Detail pages. Standard actions: Edit (view mode), Save (edit/add mode), Cancel (edit/add mode), Delete (edit mode, optional, controlled by canDelete prop). Uses lucide-react icons (Save, X, Pencil, Trash2). Saving state indicator.",
        "access": "N/A -- imported by detail pages",
        "key_elements": {},
        "shared_components": [],
        "data_sources": [],
        "state_management": "None (stateless)",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
    {
        "ida": "UI-DOC-LinesPanel",
        "name": "UI Component: LinesPanel",
        "category": "shared_component",
        "file": "src/components/common/LinesPanel.tsx",
        "route": "N/A (component)",
        "title": "LinesPanel",
        "description": "Fetches and displays line items for a transaction record. Given a selection (model + id), loads the record via wcapi getRecord, extracts lines array, renders via LinesCard from transactions. Loading spinner and error handling. Reusable for any model with lines.",
        "access": "N/A -- imported by detail pages",
        "key_elements": {},
        "shared_components": ["LinesCard (from transactions)"],
        "data_sources": ["wcapi getRecord"],
        "state_management": "Local useState",
        "dark_mode": True,
        "maturity": "modern",
        "ask_bill": False,
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# Build and execute SQL
# ──────────────────────────────────────────────────────────────────────────────

def build_sql():
    stmts = []
    for doc in DOCS:
        body = json.dumps(doc, indent=2)
        # Escape single quotes for SQL
        body_escaped = body.replace("'", "''")
        name_escaped = doc["name"].replace("'", "''")
        comment = "Auto-generated React UI documentation — 2026-06-30"
        ida = doc["ida"]

        sql = f"""INSERT INTO documents (ida, name, model_name, body, comment, count_accessed, dt_created, dt_modified, version, is_active, is_deleted, is_archived, is_locked, security_level, health_rating, metadata, refs, prefs, actions, comments, mime_type, status, description)
VALUES (
  '{ida}',
  '{name_escaped}',
  'react',
  '{body_escaped}',
  '{comment}',
  0, {NOW_MS}, {NOW_MS}, 1, true, false, false, false, 0, 100,
  '{{}}'::jsonb, '{{}}'::jsonb, '{{}}'::jsonb, '{{}}'::jsonb, '{{}}'::jsonb,
  'application/json',
  'published',
  '{doc.get("description", "")[:250].replace("'", "''")}'
);"""
        stmts.append(sql)
    return "\n".join(stmts)


if __name__ == "__main__":
    sql = build_sql()
    # Write SQL to file for review
    sql_path = "/tmp/insert_ui_docs.sql"
    with open(sql_path, "w") as f:
        f.write(sql)
    print(f"Generated {len(DOCS)} INSERT statements")
    print(f"SQL written to {sql_path}")

    # Execute
    result = subprocess.run(
        ["psql", "-h", "localhost", "-U", "williamjames", "-d", "commerce_expert", "-f", sql_path],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"SUCCESS: {result.stdout.count('INSERT')} records inserted")
    else:
        print(f"ERRORS:\n{result.stderr}")
        print(f"STDOUT:\n{result.stdout}")
