# Generated by Django 5.2.8 on 2026-09-03 15:32

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('instance_uuid', models.UUIDField(db_index=True, help_text='UUID from the instance Setting(purpose=wc:company_profile).', unique=True)),
                ('business_name', models.CharField(help_text='Display name — the business or store name.', max_length=200)),
                ('api_url', models.URLField(help_text='Public wcapi base URL (e.g. https://bobs-hardware.webclerk.com/wcapi/).', max_length=500)),
                ('latitude', models.FloatField(help_text='Store latitude (WGS84).')),
                ('longitude', models.FloatField(help_text='Store longitude (WGS84).')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('tier', models.CharField(choices=[('free', 'Free — included in network'), ('standard', 'Standard — priority placement'), ('professional', 'Professional — priority + analytics')], db_index=True, default='free', max_length=20)),
                ('dt_last_heartbeat', models.BigIntegerField(default=0, help_text='Last successful heartbeat (epoch ms). Stale > 24h.')),
                ('is_online', models.BooleanField(db_index=True, default=True, help_text='Set False when heartbeat fails 3 consecutive times.')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('athena_token', models.CharField(blank=True, help_text='Token for querying this instance inventory.', max_length=200)),
            ],
            options={
                'db_table': 'webserving_instance',
                'ordering': ['-dt_last_heartbeat'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='ws_lat_lng_idx'), models.Index(fields=['is_online', 'tier'], name='ws_online_tier_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('dt_approved', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved')),
                ('times_used', models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count')),
                ('dt_last_used', models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used')),
                ('purpose', models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('query', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_miles', models.FloatField(default=5.0)),
                ('results_count', models.IntegerField(default=0)),
                ('instances_queried', models.IntegerField(default=0)),
                ('instances_responded', models.IntegerField(default=0)),
                ('elapsed_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'webserving_search_log',
                'ordering': ['-dt_created'],
                'indexes': [models.Index(fields=['-dt_created'], name='ws_search_dt_idx')],
            },
        ),
    ]
