# Generated by Django 5.2.8 on 2026-08-26 18:52

import apps.orgs.models._typed
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_with_terms', to='transactions.paymentterm'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
            ],
            options={
                'verbose_name': 'Other Org',
                'verbose_name_plural': 'Other Orgs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
            ],
            options={
                'verbose_name': 'Rep',
                'verbose_name_plural': 'Reps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.AddIndex(
            model_name='orgbase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['contacts'], name='org_contacts_gin'),
        ),
        migrations.AddIndex(
            model_name='orgbase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='org_rel_gin'),
        ),
        migrations.AddIndex(
            model_name='orgbase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['financial'], name='org_financial_gin'),
        ),
        migrations.AddIndex(
            model_name='orgbase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['domains'], name='org_domains_gin'),
        ),
        migrations.AddConstraint(
            model_name='orgbase',
            constraint=models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='org_display_name_not_empty'),
        ),
    ]
