# Generated by Django 5.2.8 on 2026-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_orgbase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='contact',
        ),
        migrations.AddField(
            model_name='orgbase',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Primary contact id (value, not FK — no cascade)', null=True),
        ),
    ]
