# Generated by Django 5.2.8 on 2026-07-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_add_is_locked_to_lifecycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='data',
            new_name='config',
        ),
    ]
