# Generated by Django 5.2.8 on 2026-09-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_erosion_notes_alter_budget_account_debit_and_more'),
        ('orgs', '0004_fk_to_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbase',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_with_terms', to='accounts.term'),
        ),
    ]
