# Generated by Django 5.2.8 on 2026-07-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gl_journal_division_batch'),
        ('orgs', '0005_rename_data_to_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='tax_exempt_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Empty=taxable. Certificate number=exempt. 'DoTax'=force taxable override.", max_length=80),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='tax_jurisdiction',
            field=models.ForeignKey(blank=True, db_column='tax_jurisdiction_id', help_text='Default tax jurisdiction for this org — drives tax rate on transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs', to='accounts.taxjurisdiction'),
        ),
    ]
