# Generated by Django 5.2.8 on 2026-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_retire_payment_term_repoint_to_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='attention_rep',
            field=models.CharField(blank=True, help_text='The person at the rep, as attention names the person at the org', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='rep_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Rep org assigned to this customer', null=True),
        ),
    ]
