# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_rename_display_name_to_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='is_deleted',
        ),
    ]
