# Generated by Django 5.2.8 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_remove_orgbase_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbase',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
    ]
