# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_comments_flat_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='is_locked',
        ),
    ]
