# Generated by Django 5.2.8 on 2026-08-12 02:54

import apps.orgs.models._typed
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
            ],
            options={
                'verbose_name': 'Other Org',
                'verbose_name_plural': 'Other Orgs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.orgs.models._typed.OrgTypeFinancialMixin, 'orgs.orgbase'),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='org_subtype',
            field=models.CharField(blank=True, db_index=True, help_text="Classification within org_type — e.g. regulator, government, utility, association, bank, insurer. Most useful for 'other' org_type.", max_length=50),
        ),
    ]
