# Generated by Django 5.2.8 on 2026-08-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_add_org_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='org_subtype',
        ),
        migrations.AddField(
            model_name='orgbase',
            name='other_type',
            field=models.CharField(blank=True, db_index=True, help_text="What kind of 'other' org: regulator, government, utility, association, bank, insurer", max_length=50),
        ),
    ]
