# Generated by Django 5.2.8 on 2026-08-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_replace_subtype_with_other_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='other_type',
        ),
        migrations.AddField(
            model_name='orgbase',
            name='type',
            field=models.CharField(blank=True, db_index=True, help_text='Org classification: distributor, end_user, regulator, government, utility, association', max_length=50),
        ),
    ]
