# Generated by Django 5.2.1 on 2025-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_orgbase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='security_level',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification'),
        ),
    ]
