# Generated by Django 5.2.8 on 2026-02-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this address belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this domain belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this email belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this phone belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['contact'], name='locations_contact_2fa128_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['contact'], name='domains_contact_91ca24_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['path'], name='domains_path_ffbbee_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['type', 'status'], name='domains_type_f03f00_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['contact'], name='emails_contact_e2ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email'], name='emails_email_b814fb_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_primary'], name='emails_is_prim_2479c4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['opt_out'], name='emails_opt_out_e796bc_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['contact'], name='phones_contact_9a46af_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['number'], name='phones_number_e13120_idx'),
        ),
    ]
