# Generated by Django 5.2.8 on 2026-08-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this address belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this domain belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this email belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact this phone belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touch',
            name='action',
            field=models.ForeignKey(blank=True, help_text='Action that triggered this touch (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touches', to='core.action'),
        ),
        migrations.AddField(
            model_name='touch',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact who was touched', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['contact'], name='locations_contact_2fa128_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['contact'], name='domains_contact_91ca24_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['path'], name='domains_path_ffbbee_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['type', 'status'], name='domains_type_f03f00_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['contact'], name='emails_contact_e2ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email'], name='emails_email_b814fb_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_primary'], name='emails_is_prim_2479c4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['opt_out'], name='emails_opt_out_e796bc_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['contact'], name='phones_contact_9a46af_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['number'], name='phones_number_e13120_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['contact'], name='touches_contact_87df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['channel'], name='touches_channel_19377a_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['direction'], name='touches_directi_ff989e_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['-dt_created'], name='touches_dt_crea_8dd2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['action'], name='touches_action__9078d2_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['org_model', 'org_id'], name='touches_org_mod_574e26_idx'),
        ),
    ]
