# Generated by Django 5.2.8 on 2026-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='touch',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
    ]
