# Generated by Django 5.2.8 on 2026-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_address_config_domain_config_email_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='purpose',
            field=models.CharField(blank=True, db_index=True, help_text='Why this record exists: team_memory, alice_pending, search, template, etc.', max_length=255, null=True),
        ),
    ]
