# Generated by Django 5.2.8 on 2026-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_domain_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='touch',
            name='touches_contact_87df9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='touch',
            name='touches_action__9078d2_idx',
        ),
        migrations.RemoveField(
            model_name='touch',
            name='action',
        ),
        migrations.RemoveField(
            model_name='touch',
            name='contact',
        ),
        migrations.AddField(
            model_name='touch',
            name='action_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Action id that triggered this touch (value, not FK)', null=True),
        ),
        migrations.AddField(
            model_name='touch',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — no cascade, touches survive deletion)', null=True),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['contact_id'], name='touches_contact_87df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['action_id'], name='touches_action__9078d2_idx'),
        ),
    ]
