# Generated by Django 5.2.8 on 2026-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_purpose_to_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='domain',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='email',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
        migrations.AddField(
            model_name='phone',
            name='dt_approved',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms when record was approved; 0 = not approved'),
        ),
    ]
