# Generated by Django 5.2.8 on 2026-08-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_fk_to_values'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='locations_contact_2fa128_idx',
        ),
        migrations.RemoveIndex(
            model_name='domain',
            name='domains_contact_91ca24_idx',
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='emails_contact_e2ee94_idx',
        ),
        migrations.RemoveIndex(
            model_name='phone',
            name='phones_contact_9a46af_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='email',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='contact',
        ),
        migrations.AddField(
            model_name='address',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — no cascade)', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — no cascade)', null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — no cascade)', null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Contact id (value, not FK — no cascade)', null=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['contact_id'], name='locations_contact_2fa128_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['contact_id'], name='domains_contact_91ca24_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['contact_id'], name='emails_contact_e2ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['contact_id'], name='phones_contact_9a46af_idx'),
        ),
    ]
