# Generated by Django 5.2.8 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_add_dt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='address',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='domain',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='domain',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='email',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='email',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='phone',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='phone',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
    ]
