# Generated by Django 5.2.8 on 2026-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_comms_fk_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='linkage_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Linkage group — ties touch to the transaction graph (quote→order→invoice)', null=True),
        ),
    ]
