# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_alter_touch_linkage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='touch',
            name='is_deleted',
        ),
    ]
