# Generated by Django 5.2.8 on 2026-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_remove_address_is_deleted_remove_domain_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='email',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='comments',
            field=models.JSONField(blank=True, default=dict, help_text='comments.<channel>: stamped entries'),
        ),
    ]
