# Generated by Django 5.2.8 on 2026-08-12 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_add_touch_model'),
        ('core', '0038_rename_predicted_impact_to_impact_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='org_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Organization ID — paired with org_model to link to any org type', null=True),
        ),
        migrations.AddField(
            model_name='touch',
            name='org_model',
            field=models.CharField(blank=True, db_index=True, help_text='Model registry key: customer, vendor, manufacturer, rep, employee', max_length=30),
        ),
        migrations.AddIndex(
            model_name='touch',
            index=models.Index(fields=['org_model', 'org_id'], name='touches_org_mod_574e26_idx'),
        ),
    ]
