# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_comments_flat_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='touch',
            name='is_locked',
        ),
    ]
