# Generated by Django 5.2.8 on 2026-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_change_touch_plan_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='touch',
            name='dt_next',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of next follow-up. Set on save: dt_created + (plan * 86400000). 0 = none. Query: WHERE dt_next <= now() AND dt_next > 0'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='plan',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Follow-up in N days from dt_created. 0 = no follow-up.'),
        ),
    ]
