# Generated by Django 5.2.8 on 2026-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_create_agenda_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='comment',
        ),
    ]
