# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_address_config_domain_config_email_config_and_more 2'),
        ('communications', '0013_add_touch_linkage_id 2'),
        ('communications', '0014_change_touch_plan_to_integer 2'),
        ('communications', '0016_create_agenda_view 2'),
        ('communications', '0017_drop_comment_field 2'),
        ('communications', '0017_drop_comment_field'),
    ]

    operations = [
    ]
