# Generated by Django 5.2.8 on 2026-08-05 04:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('connection_id', models.BigIntegerField(blank=True, help_text='FK to sync.Connection in commerce_expert (not a DB FK — cross-database)', null=True)),
                ('pass_count', models.IntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversion_project',
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(help_text='csv, tsv, xlsx, json, pdf', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256', max_length=64)),
                ('raw_headers', models.JSONField(blank=True, default=list)),
                ('row_count', models.IntegerField(default=0)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('encoding', models.CharField(blank=True, max_length=40)),
                ('delimiter', models.CharField(blank=True, max_length=10)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='conversion.conversionproject')),
            ],
            options={
                'db_table': 'conversion_source_file',
            },
        ),
        migrations.CreateModel(
            name='Oddity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('severity', models.CharField(choices=[('info', 'Info — notable but not blocking'), ('warning', 'Warning — needs human review'), ('error', 'Error — blocks conversion'), ('pattern', 'Pattern — recurring issue across rows')], db_index=True, default='warning', max_length=20)),
                ('category', models.CharField(db_index=True, help_text='Type of oddity: duplicate_sku, ambiguous_uom, missing_price, bad_date, encoding, gl_unmapped, etc.', max_length=80)),
                ('description', models.TextField()),
                ('source_column', models.CharField(blank=True, max_length=255)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('source_value', models.TextField(blank=True, help_text='The actual value that caused the oddity')),
                ('affected_count', models.IntegerField(default=1)),
                ('resolution', models.CharField(blank=True, db_index=True, help_text='pending | auto_fixed | user_fixed | skipped | escalated', max_length=40)),
                ('resolution_detail', models.TextField(blank=True)),
                ('pass_number', models.IntegerField(default=1)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oddities', to='conversion.conversionproject')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oddities', to='conversion.sourcefile')),
            ],
            options={
                'verbose_name_plural': 'oddities',
                'db_table': 'conversion_oddity',
            },
        ),
        migrations.CreateModel(
            name='ColumnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(help_text='Column name as it appears in the file', max_length=255)),
                ('target_model', models.CharField(blank=True, help_text='WC3 model name: Item, OrgBase, BillOfMaterial', max_length=80)),
                ('target_field', models.CharField(blank=True, help_text='WC3 field name or JSON path: price.base, gls.inventory', max_length=80)),
                ('confidence', models.FloatField(default=0.0, help_text="Claude's confidence 0.0-1.0")),
                ('transform', models.CharField(blank=True, help_text='Transformation to apply: normalize_uom, parse_decimal, map_gl, etc.', max_length=255)),
                ('status', models.CharField(db_index=True, default='proposed', help_text='proposed | confirmed | rejected | unmapped', max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('sample_values', models.JSONField(blank=True, default=list)),
                ('pass_number', models.IntegerField(default=1)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_maps', to='conversion.sourcefile')),
            ],
            options={
                'db_table': 'conversion_column_map',
            },
        ),
        migrations.CreateModel(
            name='StagingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField()),
                ('target_model', models.CharField(db_index=True, help_text='Item, BillOfMaterial, OrgBase, etc.', max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='staged', help_text='staged | bundled | rejected | needs_review', max_length=20)),
                ('oddity_ids', models.JSONField(blank=True, default=list, help_text='List of Oddity IDs affecting this row')),
                ('pass_number', models.IntegerField(default=1)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='conversion.sourcefile')),
            ],
            options={
                'db_table': 'conversion_staging_row',
            },
        ),
        migrations.CreateModel(
            name='PassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.IntegerField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('focus', models.TextField(blank=True, help_text='What Alice looked at: initial_mapping, oddity_resolution, validation, etc.')),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_staged', models.IntegerField(default=0)),
                ('rows_rejected', models.IntegerField(default=0)),
                ('oddities_found', models.IntegerField(default=0)),
                ('oddities_resolved', models.IntegerField(default=0)),
                ('llm_model', models.CharField(blank=True, max_length=60)),
                ('llm_calls', models.IntegerField(default=0)),
                ('llm_input_tokens', models.IntegerField(default=0)),
                ('llm_output_tokens', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('dt_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_completed', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='conversion.conversionproject')),
            ],
            options={
                'db_table': 'conversion_pass_log',
                'unique_together': {('project', 'pass_number')},
            },
        ),
    ]
