# Generated by Django 5.2.8 on 2026-03-06 06:56

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('transaction', 'Transaction Activity'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Inter-Location Transfer'), ('receipt', 'Goods Receipt'), ('count', 'Physical Count'), ('reorder', 'Reorder Action'), ('alert', 'System Alert')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('order_line_add', 'Line added to order'), ('order_line_update', 'Line quantity changed'), ('order_line_delete', 'Line removed from order'), ('order_convert_invoice', 'Order converted to invoice'), ('invoice_line_add', 'Line added to invoice'), ('invoice_line_update', 'Invoice line changed'), ('invoice_line_delete', 'Invoice line removed'), ('invoice_pack', 'Invoice lines packed/shipped'), ('po_create', 'Purchase order created'), ('po_line_add', 'PO line added'), ('po_line_update', 'PO line changed'), ('po_line_delete', 'PO line removed'), ('po_receive', 'PO goods received'), ('proposal_line_add', 'Line added to proposal'), ('proposal_line_update', 'Proposal line changed'), ('proposal_line_delete', 'Proposal line removed'), ('qty_adjust_up', 'Quantity increased'), ('qty_adjust_down', 'Quantity decreased'), ('cost_adjust', 'Unit cost changed'), ('below_reorder', 'Fell below reorder point'), ('below_safety', 'Fell below safety stock'), ('overstock', 'Exceeded max stock level'), ('pending_processed', 'Pending record processed')], db_index=True, max_length=30)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('item_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('item_description', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('transaction_ida', models.CharField(blank=True, default='', max_length=50)),
                ('line_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('on_hand', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('on_order', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('on_purchase', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('available', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('llm_summary', models.TextField(blank=True, default='')),
                ('llm_processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_inventory_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'category'], name='ai_inventor_created_b2edb8_idx'), models.Index(fields=['item_id', 'created_at'], name='ai_inventor_item_id_8c03d1_idx'), models.Index(fields=['transaction_id', 'transaction_type'], name='ai_inventor_transac_bcb487_idx')],
            },
        ),
    ]
