# Generated by Django 5.2.8 on 2026-03-06 07:11

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_add_inventory_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('error_text', models.TextField(help_text='The error message or pattern to match')),
                ('error_regex', models.CharField(blank=True, default='', help_text='Optional regex for flexible matching', max_length=500)),
                ('category', models.CharField(choices=[('import', 'Import Error'), ('type', 'Type Error'), ('runtime', 'Runtime Error'), ('test', 'Test Failure'), ('lint', 'Lint / Style'), ('build', 'Build / Compile'), ('db', 'Database'), ('api', 'API / HTTP'), ('config', 'Configuration')], db_index=True, max_length=20)),
                ('cause', models.TextField(help_text='Root cause explanation')),
                ('fix', models.TextField(help_text='How to fix it')),
                ('prevention', models.TextField(blank=True, default='', help_text='How to prevent it in the future')),
                ('occurrences', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('related_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Files commonly involved when this error occurs', size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'error_pattern',
                'ordering': ['-occurrences', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(choices=[('feature', 'New Feature'), ('bugfix', 'Bug Fix'), ('refactor', 'Refactoring'), ('test', 'Testing'), ('docs', 'Documentation'), ('devops', 'DevOps / Infrastructure'), ('debug', 'Debugging Session'), ('exploration', 'Code Exploration'), ('review', 'Code Review')], db_index=True, max_length=20)),
                ('apps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Django apps touched (e.g., ['transactions', 'products'])", size=None)),
                ('models_touched', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Model names touched (e.g., ['Order', 'OrderLine'])", size=None)),
                ('files_changed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='File paths changed during session', size=None)),
                ('problem', models.TextField(blank=True, default='', help_text='What problem was being solved?')),
                ('solution', models.TextField(blank=True, default='', help_text='How was it solved?')),
                ('learnings', models.TextField(blank=True, default='', help_text='Key takeaways, patterns discovered, gotchas to remember')),
                ('errors_encountered', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Error messages encountered during session', size=None)),
                ('error_fixes', models.JSONField(blank=True, default=dict, help_text='Map of error → fix applied')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Semantic tags for categorization', size=None)),
                ('related_sessions', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='UUIDs of related sessions', size=None)),
                ('llm_summary', models.TextField(blank=True, default='', help_text='LLM-generated summary of the session')),
                ('llm_processed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_log', models.TextField(blank=True, default='', help_text='Raw conversation with AI assistant')),
                ('git_commits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Git commit hashes from this session', size=None)),
            ],
            options={
                'db_table': 'coding_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at', 'session_type'], name='coding_sess_started_4bf455_idx'), models.Index(fields=['session_type'], name='coding_sess_session_13d0ab_idx')],
            },
        ),
    ]
