# Generated by Django 5.2.8 on 2026-03-06 07:24

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_add_coding_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('commit_hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('committed_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('files_added', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('files_modified', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('files_deleted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_deleted', models.IntegerField(default=0)),
                ('commit_type', models.CharField(choices=[('feature', 'New Feature'), ('bugfix', 'Bug Fix'), ('refactor', 'Refactoring'), ('docs', 'Documentation'), ('test', 'Test'), ('chore', 'Maintenance'), ('style', 'Code Style'), ('perf', 'Performance'), ('ci', 'CI/CD'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('apps_touched', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('models_touched', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('llm_summary', models.TextField(blank=True, default='')),
                ('llm_processed_at', models.DateTimeField(blank=True, null=True)),
                ('has_drift_issues', models.BooleanField(default=False)),
                ('drift_issues', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'git_event',
                'ordering': ['-committed_at'],
                'indexes': [models.Index(fields=['committed_at', 'author_email'], name='git_event_committ_62bfc4_idx'), models.Index(fields=['commit_type'], name='git_event_commit__96d5b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemaDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('file_path', models.CharField(db_index=True, max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('drift_type', models.CharField(choices=[('deprecated_field', 'Uses deprecated field name'), ('old_api_shape', 'Uses outdated API response shape'), ('banned_pattern', 'Uses banned code pattern'), ('missing_migration', 'Schema change without migration'), ('stale_import', 'Imports from moved/deleted module'), ('type_mismatch', "Type doesn't match current schema")], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('error', 'Error - Must fix'), ('warning', 'Warning - Should fix'), ('info', 'Info - Consider updating')], default='warning', max_length=10)),
                ('description', models.TextField()),
                ('current_value', models.CharField(blank=True, default='', max_length=255)),
                ('expected_value', models.CharField(blank=True, default='', max_length=255)),
                ('fix_suggestion', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100)),
                ('resolved_in_commit', models.CharField(blank=True, default='', max_length=40)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('git_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drift_records', to='ai_assistant.gitevent')),
            ],
            options={
                'db_table': 'schema_drift',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['drift_type', 'is_resolved'], name='schema_drif_drift_t_75f09c_idx'), models.Index(fields=['file_path'], name='schema_drif_file_pa_d7f86b_idx')],
            },
        ),
    ]
