# Generated by Django 5.2.8 on 2026-07-03 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_add_git_observer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliceCoachingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('drill_id', models.CharField(db_index=True, max_length=50)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('drill_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dt_started', models.BigIntegerField(default=0)),
                ('dt_completed', models.BigIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alice_coaching_log',
                'indexes': [models.Index(fields=['contact', 'completed'], name='alicecoach_contact_done_idx'), models.Index(fields=['category'], name='alicecoach_category_idx')],
            },
        ),
        migrations.CreateModel(
            name='AliceObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('category', models.CharField(choices=[('pattern', 'Workflow Pattern'), ('anomaly', 'Data Anomaly'), ('coaching', 'Coaching Suggestion'), ('alert', 'Alert'), ('search', 'Search Pattern'), ('layout', 'Layout Suggestion'), ('performance', 'Performance Issue')], db_index=True, default='pattern', max_length=30)),
                ('source', models.CharField(choices=[('alice', 'Alice (local)'), ('wchq', 'WCHQ (synced)'), ('power_user', 'Power User')], default='alice', max_length=20)),
                ('priority', models.IntegerField(choices=[(0, 'Normal'), (1, 'Important'), (2, 'Urgent')], default=0)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('record_id', models.BigIntegerField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('dt_acknowledged', models.BigIntegerField(default=0)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.TextField(blank=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_observations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alice_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alice_observations',
                'indexes': [models.Index(fields=['category', 'resolved'], name='aliceobs_cat_resolved_idx'), models.Index(fields=['contact', 'acknowledged'], name='aliceobs_contact_ack_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlicePreset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('preset_type', models.CharField(choices=[('search', 'Search Preset'), ('layout', 'Layout'), ('dashboard', 'Dashboard Config'), ('workflow', 'Workflow Sequence'), ('report', 'Report Preset')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('alice', 'Alice (pattern detection)'), ('wchq', 'WCHQ (synced)'), ('power_user', 'Power User')], default='alice', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('use_count', models.IntegerField(default=0)),
                ('dt_last_used', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alice_presets',
                'indexes': [models.Index(fields=['preset_type', 'model_name'], name='alicepreset_type_model_idx')],
            },
        ),
    ]
