# Generated by Django 5.2.8 on 2026-07-29 23:55

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_rename_data_to_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliceInsight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Record is locked and cannot be edited (admin override required)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Application data container — form fields, type-specific content, user-managed data. Separate from metadata (system behavior) by design.')),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('agent', models.CharField(db_index=True, default='alice', help_text='Agent that wrote this insight (alice, athena, or user-defined)', max_length=50)),
                ('subject_type', models.CharField(choices=[('user', 'User Profile'), ('model', 'Model Usage'), ('flow', 'Transaction Flow'), ('sync', 'Sync Pattern'), ('coaching', 'Coaching Track'), ('security', 'Security Review'), ('risk', 'Risk Assessment')], db_index=True, help_text='Category of insight', max_length=20)),
                ('subject_key', models.CharField(blank=True, default='', help_text='Specific subject within the type (model name, flow name, etc.)', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Alice one-line summary for this subject')),
                ('observation_count', models.IntegerField(default=0, help_text='Observations Alice has made on this subject')),
                ('dt_last_interaction', models.BigIntegerField(default=0, help_text='Last time Alice observed activity on this subject (epoch ms)')),
                ('dt_last_updated', models.BigIntegerField(default=0, help_text='Last time Alice updated this insight (epoch ms)')),
                ('contact', models.ForeignKey(help_text='The user Alice is learning about', on_delete=django.db.models.deletion.CASCADE, related_name='alice_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alice_insights',
                'indexes': [models.Index(fields=['agent', 'contact', 'subject_type'], name='aliceins_agent_ct_type_idx'), models.Index(fields=['agent', 'subject_type', 'subject_key'], name='aliceins_agent_type_key_idx'), models.Index(fields=['dt_last_updated'], name='aliceins_last_updated_idx')],
                'unique_together': {('agent', 'contact', 'subject_type', 'subject_key')},
            },
        ),
    ]
