# Generated by Django 5.2.8 on 2026-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_add_commission_line_type_and_function_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliceobservation',
            name='category',
            field=models.CharField(choices=[('pattern', 'Workflow Pattern'), ('anomaly', 'Data Anomaly'), ('coaching', 'Coaching Suggestion'), ('alert', 'Alert'), ('search', 'Search Pattern'), ('layout', 'Layout Suggestion'), ('performance', 'Performance Issue'), ('schema', 'Pydantic Schema Question'), ('console', 'Console Capture'), ('escalation', 'Escalation to Claude'), ('bill_question', 'Question for Bill')], db_index=True, default='pattern', max_length=30),
        ),
    ]
