# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0009_add_dt_approved 2'),
        ('ai_assistant', '0012_add_bill_question_category 2'),
        ('ai_assistant', '0013_alice_models_inherit_basemodel 2'),
        ('ai_assistant', '0013_alice_models_inherit_basemodel'),
    ]

    operations = [
    ]
