BEGIN;
UPDATE actions SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE products_item SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE orgs_orgbase SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE refs_mismatch_log SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE emails SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE settings SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE products_warehouse SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE pending SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE requisitions SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE connections SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE domains SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE projects SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE contacts SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE phones SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE documents SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE acct_currencies SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE products_catalog SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE acct_exchanges SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE acct_exchange_rates SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE templates SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE tags SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE locations SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE proposals SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE qas SET uuid = gen_random_uuid() WHERE uuid IS NULL;
UPDATE orders SET uuid = gen_random_uuid() WHERE uuid IS NULL;
COMMIT;
