# Generated by Django 5.2.8 on 2026-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_billofmaterial_status_alter_catalog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryline',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='status',
            field=models.CharField(blank=True, db_index=True, help_text='Current status of the record', max_length=50, null=True),
        ),
    ]
