# Generated by Django 5.2.8 on 2026-08-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_deliveryline_status_alter_deliveryvisit_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
