# Generated by Django 5.2.8 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_fk_to_values'),
        ('products', '0004_delete_service_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliveryvisit',
            name='delv_customer_sched_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryvisit',
            name='customer_orgbase',
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='customer_orgbase_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Customer org id (value, not FK — visit history survives)', null=True),
        ),
        migrations.AddIndex(
            model_name='deliveryvisit',
            index=models.Index(fields=['customer_orgbase_id', 'dt_scheduled'], name='delv_customer_sched_idx'),
        ),
    ]
