# Generated by Django 5.2.8 on 2026-08-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cascade_fks_to_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogline',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='itemxref',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='products.item'),
        ),
    ]
