# Generated by Django 5.2.8 on 2026-08-28 02:48

import django.contrib.postgres.indexes
import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_item_linked_cascade_to_protect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='item',
        ),
        migrations.AddField(
            model_name='serial',
            name='item_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Item id (value, not FK — serial survives item deletion)', null=True),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['refs'], name='products_se_refs_c28d47_gin'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['prefs'], name='products_se_prefs_f98916_gin'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=django.contrib.postgres.indexes.GinIndex(fields=['actions'], name='products_se_actions_ce7af1_gin'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('status', 'actions'), name='idx_actions_status'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('required', 'actions'), name='idx_actions_required'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('who', 'actions'), name='idx_actions_who'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('when', 'actions'), name='idx_actions_when'),
        ),
    ]
