# Generated by Django 5.2.8 on 2026-09-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_serial_item_to_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryvisit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventorycheck',
            name='notes',
        ),
    ]
