# Generated by Django 5.2.8 on 2026-09-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_deliveryvisit_notes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgitem',
            name='ck_orgitem_qty_min_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orgitem',
            name='ck_orgitem_qty_max_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orgitem',
            name='ck_orgitem_qty_order',
        ),
        migrations.RemoveField(
            model_name='orgitem',
            name='quantity_maximum',
        ),
        migrations.RemoveField(
            model_name='orgitem',
            name='quantity_minimum',
        ),
    ]
