# Generated by Django 5.2.8 on 2026-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_pendinginventoryadjustment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylayer',
            name='dt_locked',
            field=models.DateTimeField(blank=True, help_text='When the lock was acquired. Auto-expires after 5 minutes.', null=True),
        ),
    ]
