# Generated by Django 5.2.8 on 2026-08-05 20:20

import apps.products.models.serial
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_dt_locked_to_inventorylayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='config',
            field=models.JSONField(blank=True, default=apps.products.models.serial.default_serial_config, help_text='Transaction context: customer, vendor, document refs, cost/price, floor plan'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this specific unit', max_length=255),
        ),
        migrations.AlterField(
            model_name='serial',
            name='item_ida',
            field=models.CharField(blank=True, db_index=True, help_text='Item identifier (copied from parent item for fast lookup)', max_length=120),
        ),
        migrations.AlterField(
            model_name='serial',
            name='model_ida',
            field=models.CharField(blank=True, db_index=True, help_text='Model number or variant identifier', max_length=120),
        ),
        migrations.AlterField(
            model_name='serial',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, help_text='QR or barcode value if different from serial_ida', max_length=255),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serial_ida',
            field=models.CharField(help_text='Serial number as printed on the unit', max_length=120),
        ),
        migrations.AlterField(
            model_name='serial',
            name='site',
            field=models.JSONField(blank=True, default=dict, help_text='Current location: warehouse code, bin, zone, geo'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('received', 'Received'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('returned', 'Returned'), ('referenced', 'Referenced'), ('warranty', 'Warranty'), ('damaged', 'Damaged'), ('scrapped', 'Scrapped')], db_index=True, default='received', max_length=40),
        ),
        migrations.AlterField(
            model_name='serial',
            name='warranty',
            field=models.JSONField(blank=True, default=dict, help_text='Warranty details: days, dt_start, dt_end, terms'),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='action',
            field=models.CharField(db_index=True, help_text="Full sentence: 'Issued in invoice', 'Returned from customer', etc.", max_length=120),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Context: doc_type, doc_id, status_before, notes'),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='dt',
            field=models.BigIntegerField(db_index=True, help_text='Unix timestamp of the action'),
        ),
    ]
