# Generated by Django 5.2.8 on 2026-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_delivery_inventory_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='catalogline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inventorylayer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inventorymetricssnapshot',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='inventoryreservation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='itemxref',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='siteinventory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_deleted',
        ),
    ]
