# Generated by Django 5.2.8 on 2026-09-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_billofmaterial_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.item'),
        ),
    ]
