# Generated by Django 5.2.8 on 2026-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_dt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='catalogline',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='deliveryvisit',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentprocessorrun',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventorycheck',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventorymetricssnapshot',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='item',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='item',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='itemxref',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='itemxref',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='orgitem',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='pendinginventoryadjustment',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='pendinginventoryadjustment',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='serial',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='serial',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='service',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='service',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='siteinventory',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='siteinventory',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='specification',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='specification',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='variant',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='variant',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='dt_last_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Epoch ms of last use; 0 = never used'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='times_used',
            field=models.BigIntegerField(db_index=True, default=0, help_text='Lifetime use count'),
        ),
    ]
