# Generated by Django 5.2.8 on 2026-08-10 22:40

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_times_used_dt_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='catalogline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='catalogline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='deliveryvisit',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentprocessorrun',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentprocessorrun',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventorycheck',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventorycheckline',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventorycheckline',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventorylayer',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventorymetricssnapshot',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventorymetricssnapshot',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='itemxref',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='itemxref',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='orgitem',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='service',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
    ]
