# Generated by Django 5.2.8 on 2026-09-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_comments_flat_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryReservation',
        ),
    ]
