# Generated by Django 5.2.8 on 2026-09-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_inventory_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylayer',
            name='dt_locked',
        ),
    ]
