# Generated by Django 5.2.8 on 2026-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_pending_inventory_inherit_coremodel 2'),
        ('products', '0005_item_vendor_manufacturer 2'),
        ('products', '0006_rename_data_to_config 2'),
        ('products', '0007_add_margin_velocity_fields 2'),
        ('products', '0008_add_catalog_pricing_fields 2'),
        ('products', '0009_billofmaterial_config_catalog_config_and_more 2'),
        ('products', '0010_pendinginventoryadjustment_config 2'),
        ('products', '0011_add_dt_locked_to_inventorylayer 2'),
        ('products', '0012_serial_config_and_status 2'),
        ('products', '0013_purpose_to_basemodel 2'),
        ('products', '0014_add_dt_approved 2'),
        ('products', '0015_add_times_used_dt_last_used 2'),
        ('products', '0016_add_commission_line_type_and_function_category 2'),
        ('products', '0017_drop_comment_field 2'),
        ('products', '0017_drop_comment_field'),
    ]

    operations = [
    ]
