# Generated by Django 5.2.8 on 2026-09-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_layer_soft_lock_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='catalogline',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentprocessorrun',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorylayer',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorymetricssnapshot',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='itemusage',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='itemxref',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='siteinventory',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_locked',
        ),
    ]
