"""Layers and movements name the line that caused them (Bill, 2026-09-28 naming rule; GL-by-layer
step 2): parent_model + parent_id replace source / source_doc_type / source_doc_id, and a movement
gets its own dt_journaled.

A source_doc_type that is a model key (workorderline, receiptline, invoiceline) carries over with
its id; a pseudo type (opening_balance, demo_seed, purchase_receipt, split, transfer) is not a
record and becomes empty. Opening layers get a real parent in step 6 (an opening count workorder).
"""
# Generated by Django 5.2.8 on 2026-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_is_locked_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylayer',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='parent_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='dt_journaled',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='parent_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
