# Generated by Django 5.2.8 on 2026-02-18 21:03

import apps.orgs.models.constants
import common.models
import common.relationship_stats_mixin
import common.stats_mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('dt_created', models.BigIntegerField(db_index=True, default=0)),
                ('dt_modified', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Record is logically active')),
                ('security_level', models.IntegerField(blank=True, db_index=True, default=0, help_text='Security level or classification')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Next action metadata (searchable)')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('stats', models.JSONField(blank=True, default=common.stats_mixin.default_stats)),
                ('relationship_stats', models.JSONField(blank=True, default=common.relationship_stats_mixin.default_relationship_stats)),
                ('org_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('rep', 'Rep'), ('employee', 'Employee'), ('manufacturer', 'Manufacturer'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('address_full', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_id', models.IntegerField(blank=True, null=True)),
                ('phone_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('price_level', models.CharField(blank=True, max_length=30, null=True)),
                ('terms', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Unspecified'), ('active', 'Active'), ('prospect', 'Prospect'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('retired', 'Retired')], db_index=True, max_length=30)),
                ('contacts', models.JSONField(default=apps.orgs.models.constants.default_contacts)),
                ('addresses', models.JSONField(default=apps.orgs.models.constants.default_addresses)),
                ('domains', models.JSONField(default=apps.orgs.models.constants.default_domains)),
                ('phones', models.JSONField(default=apps.orgs.models.constants.default_phones)),
                ('emails', models.JSONField(default=apps.orgs.models.constants.default_emails)),
                ('docs', models.JSONField(default=apps.orgs.models.constants.default_docs)),
                ('connections', models.JSONField(default=apps.orgs.models.constants.default_connections)),
                ('relations', models.JSONField(default=apps.orgs.models.constants.default_relations)),
                ('financial', models.JSONField(default=apps.orgs.models.constants.default_financial)),
                ('data', models.JSONField(default=apps.orgs.models.constants.default_data)),
                ('metrics', models.JSONField(default=apps.orgs.models.constants.default_metrics)),
                ('gl_accounts', models.JSONField(default=apps.orgs.models.constants.default_gl_accounts)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_as_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
