# Generated by Django 5.2.1 on 2025-09-04 15:30

import apps.orgs.models.base_org_model
import common.models
import common.relationship_stats_mixin
import common.stats_mixin
import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_dt', models.BigIntegerField(db_index=True, default=0)),
                ('modified_dt', models.BigIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(default=common.models.default_metadata, help_text='Universal metadata envelope')),
                ('refs', models.JSONField(default=common.models.default_refs, help_text='Keywords / tags / lightweight links')),
                ('prefs', models.JSONField(default=common.models.default_prefs, help_text='User preferences / settings')),
                ('comments', models.JSONField(default=common.models.default_comments, help_text='Threaded notes / comment fields')),
                ('health_rating', models.IntegerField(default=0, help_text='Data quality rating (0-100)')),
                ('stats', models.JSONField(blank=True, default=common.stats_mixin.default_stats)),
                ('relationship_stats', models.JSONField(blank=True, default=common.relationship_stats_mixin.default_relationship_stats)),
                ('org_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('rep', 'Rep'), ('employee', 'Employee'), ('manufacturer', 'Manufacturer'), ('other', 'Other')], db_index=True, max_length=20)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contacts', models.JSONField(default=apps.orgs.models.base_org_model.default_contacts)),
                ('locations', models.JSONField(default=apps.orgs.models.base_org_model.default_locations)),
                ('domains', models.JSONField(default=apps.orgs.models.base_org_model.default_domains)),
                ('phones', models.JSONField(default=apps.orgs.models.base_org_model.default_phones)),
                ('emails', models.JSONField(default=apps.orgs.models.base_org_model.default_emails)),
                ('docs', models.JSONField(default=apps.orgs.models.base_org_model.default_docs)),
                ('connections', models.JSONField(default=apps.orgs.models.base_org_model.default_connections)),
                ('relations', models.JSONField(default=apps.orgs.models.base_org_model.default_relations)),
                ('financial', models.JSONField(default=apps.orgs.models.base_org_model.default_financial)),
                ('data', models.JSONField(default=apps.orgs.models.base_org_model.default_data)),
                ('metrics', models.JSONField(default=apps.orgs.models.base_org_model.default_metrics)),
                ('gl_accounts', models.JSONField(default=apps.orgs.models.base_org_model.default_gl_accounts)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['contacts'], name='org_contacts_gin'), django.contrib.postgres.indexes.GinIndex(fields=['relations'], name='org_rel_gin'), django.contrib.postgres.indexes.GinIndex(fields=['financial'], name='org_financial_gin'), django.contrib.postgres.indexes.GinIndex(fields=['domains'], name='org_domains_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='org_display_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orgs.orgbase',),
        ),
        migrations.CreateModel(
            name='EmployeeOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orgs.orgbase',),
        ),
        migrations.CreateModel(
            name='ManufacturerOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orgs.orgbase',),
        ),
        migrations.CreateModel(
            name='RepOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Rep',
                'verbose_name_plural': 'Reps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orgs.orgbase',),
        ),
        migrations.CreateModel(
            name='VendorOrg',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orgs.orgbase',),
        ),
    ]
