# Generated by Django 5.2.5 on 2025-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbase',
            name='org_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('rep', 'Rep'), ('employee', 'Employee'), ('manufacturer', 'Manufacturer'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
    ]
