# Generated by Django 5.2.5 on 2025-11-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='display_name',
            new_name='company',
        ),
    ]
