# Generated by Django 5.2.5 on 2025-08-31 21:47

import common.relationship_stats_mixin
import common.stats_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='relationship_stats',
            field=models.JSONField(blank=True, default=common.relationship_stats_mixin.default_relationship_stats),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='stats',
            field=models.JSONField(blank=True, default=common.stats_mixin.default_stats),
        ),
    ]
