# Generated by Django 5.2.8 on 2026-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbase',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('active', 'Active'), ('prospect', 'Prospect'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('retired', 'Retired')], db_index=True, max_length=30),
        ),
    ]
