# Generated by Django 5.2.8 on 2025-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_orgbase_org_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgbase',
            name='org_company_not_empty',
        ),
        migrations.RenameField(
            model_name='orgbase',
            old_name='company',
            new_name='display_name',
        ),
        migrations.AddConstraint(
            model_name='orgbase',
            constraint=models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='org_display_name_not_empty'),
        ),
    ]
