# Generated by Django 5.2.8 on 2026-01-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_orgbase_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='is_locked',
        ),
    ]
