# Generated by Django 5.2.8 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_remove_orgbase_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='price_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
