# Generated by Django 5.2.8 on 2026-02-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_orgbase_price_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='locations',
            new_name='addresses',
        ),
        migrations.AddField(
            model_name='orgbase',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
