# Generated by Django 5.2.8 on 2026-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_rename_locations_orgbase_addresses_orgbase_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='address_full',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='terms',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='terms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
