# Generated by Django 5.2.8 on 2026-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_orgbase_address_full_orgbase_terms_orgbase_terms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbase',
            name='conditions_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='conditions_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
