# Generated by Django 5.2.8 on 2026-02-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_add_conditions_to_orgbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbase',
            name='conditions_description',
        ),
        migrations.RemoveField(
            model_name='orgbase',
            name='conditions_id',
        ),
    ]
