# Generated by Django 5.2.8 on 2026-02-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_remove_conditions_from_orgbase'),
        ('transactions', '0034_invoice_conditions_description_invoice_conditions_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='contact_id',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='orgbase',
            old_name='terms_id',
            new_name='domain_id',
        ),
        migrations.AddField(
            model_name='orgbase',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='email_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='phone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgbase',
            name='terms_fk',
            field=models.ForeignKey(blank=True, db_column='terms_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs_with_terms', to='transactions.paymentterm'),
        ),
    ]
