# Generated by Django 5.2.8 on 2026-08-10 22:40

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_add_times_used_dt_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbase',
            name='comments',
            field=models.JSONField(blank=True, default=common.models.default_comments, help_text='Threaded notes / comment fields'),
        ),
        migrations.AlterField(
            model_name='orgbase',
            name='prefs',
            field=models.JSONField(blank=True, default=common.models.default_prefs, help_text='User preferences / settings'),
        ),
    ]
