# Generated by Django 5.2.8 on 2026-02-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_rename_contact_id_orgbase_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='contact',
            new_name='contact_id',
        ),
    ]
