# Generated by Django 5.2.8 on 2026-02-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_rename_contact_orgbase_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgbase',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
